table Lengua
	lineageTag: 636c2bcd-f8cb-445b-996e-a5b01d99c66a

	measure PoblacionHablanteIndigena_2020 = ```
			
			CALCULATE(
			    SUM(CensoHechos[Valor]),
			    CensoHechos[id_indicador] = 1005000039,
			    CensoHechos[Año] = 2020
			)
			
			```
		formatString: 0
		lineageTag: 97102955-69c4-4848-bc10-5b37bfc7ceea

		annotation PBI_FormatHint = {"isDecimal":true}

	measure 'PoblacionHablanteRestoLenguas 2020' = ```
			
			CALCULATE(
			    SUM(CensoHechos[Valor]),
			    CensoHechos[id_indicador] = 6200240538
			)
			
			```
		formatString: 0
		lineageTag: 296af613-4fd1-4512-9093-9c57945f6285

		annotation PBI_FormatHint = {"isDecimal":true}

	measure Nahuatl_ = ```
			
			CALCULATE(
			    SUM(CensoHechos[Valor]),
			    CensoHechos[id_indicador] = 6200240496
			)
			
			```
		lineageTag: 788df319-6ae3-436b-a313-f53d2c69f888

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure Maya_ = ```
			
			CALCULATE(
			    SUM(CensoHechos[Valor]),
			    CensoHechos[id_indicador] = 6200240331
			)
			
			```
		lineageTag: bc21c76a-806c-4b2c-8714-1cac979b7560

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure Tseltal_ = ```
			
			CALCULATE(
			    SUM(CensoHechos[Valor]),
			    CensoHechos[id_indicador] = 6200240318
			)
			
			```
		lineageTag: b8d00479-cccf-4669-b349-642095be0e7b

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure Tzotzil_ = ```
			
			CALCULATE(
			    SUM(CensoHechos[Valor]),
			    CensoHechos[id_indicador] = 6200240481
			)
			
			```
		lineageTag: 5c4052a7-631b-461a-beb4-f86d03233892

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure Mixteco_ = ```
			
			CALCULATE(
			    SUM(CensoHechos[Valor]),
			    CensoHechos[id_indicador] = 6200240386
			)
			
			```
		lineageTag: 98579aa3-0774-4077-ab84-8a06f7b6b3f7

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure Nahuatl = ```
			
			CALCULATE(
			    SUM(CensoHechos[Valor]),
			    CensoHechos[id_indicador] = 6200240496,
			    CensoHechos[Año] = 2020
			)
			
			```
		lineageTag: 84c4b90f-8d70-4c5b-b070-10280fe3c13a

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure Maya = ```
			
			CALCULATE(
			    SUM(CensoHechos[Valor]),
			    CensoHechos[id_indicador] = 6200240331,
			    CensoHechos[Año] = 2020
			)
			
			```
		lineageTag: 91d9cc3a-3a3b-44e4-8114-5fe4994ac220

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure Tseltal = ```
			
			CALCULATE(
			    SUM(CensoHechos[Valor]),
			    CensoHechos[id_indicador] = 6200240318,
			    CensoHechos[Año] = 2020
			)
			
			```
		lineageTag: 46500453-63d2-48fa-82ea-08a214dc668f

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure Tzotzil = ```
			
			CALCULATE(
			    SUM(CensoHechos[Valor]),
			    CensoHechos[id_indicador] = 6200240481,
			    CensoHechos[Año] = 2020
			)
			
			```
		lineageTag: 11850eee-e734-4ba6-9dc1-842e11e5e23f

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure Mixteco = ```
			
			CALCULATE(
			    SUM(CensoHechos[Valor]),
			    CensoHechos[id_indicador] = 6200240386,
			    CensoHechos[Año] = 2020
			)
			
			```
		lineageTag: e67c6f08-c901-464d-9f74-ff47d7f6b60f

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure PoblacionHablanteIndigena = ```
			
			CALCULATE(
			    SUM(CensoHechos[Valor]),
			    CensoHechos[id_indicador] = 1005000039
			)
			
			```
		lineageTag: 85c93bd4-0b8d-4bd1-805c-f6334834fd67

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	partition Lengua = m
		mode: import
		source =
				let
				    Origen = Table.FromRows(Json.Document(Binary.Decompress(Binary.FromText("i44FAA==", BinaryEncoding.Base64), Compression.Deflate)), let _t = ((type nullable text) meta [Serialized.Text = true]) in type table [Columna1 = _t]),
				    #"Tipo cambiado" = Table.TransformColumnTypes(Origen,{{"Columna1", type text}}),
				    #"Columnas quitadas" = Table.RemoveColumns(#"Tipo cambiado",{"Columna1"})
				in
				    #"Columnas quitadas"

	annotation PBI_ResultType = Table

