table Migración
	lineageTag: f00508b6-e18f-46ae-8419-3d26f01fa2eb

	measure PoblacionInmigrante = ```
			
			CALCULATE(
			    SUM(CensoHechos[Valor]),
			    CensoHechos[id_indicador] = 6200205252
			)
			
			```
		lineageTag: 74a565cb-16bc-496e-831c-643fbf074d61

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure PoblacionNacidaOtroPais = ```
			
			CALCULATE(
			    SUM(CensoHechos[Valor]),
			    CensoHechos[id_indicador] = 6200205259
			)
			
			```
		formatString: 0
		lineageTag: 6112eba0-f550-43b2-b8bb-001d7508f096

		annotation PBI_FormatHint = {"isDecimal":true}

	measure SaldoNetoMigratorioInterno = ```
			
			CALCULATE(
			    SUM(CensoHechos[Valor]),
			    CensoHechos[id_indicador] = 6200205262
			)
			
			```
		lineageTag: c5d31f78-8220-4bc4-b26a-33700ed9cb16

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure 'Pob. Nacida Otro País Hombres' = ```
			
			CALCULATE(
			    SUM(CensoHechos[Valor]),
			    CensoHechos[id_indicador] = 6200205268
			)
			
			```
		lineageTag: 607ffbf8-a917-4402-ae2e-583aaf8c431a

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure PoblacionEmigrante = ```
			
			CALCULATE(
			    SUM(CensoHechos[Valor]),
			    CensoHechos[id_indicador] = 6200205277
			)
			
			```
		lineageTag: 32d44dff-0b15-48d0-a806-4829abb6c101

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure 'Pob. Nacida Otro País Mujeres' = ```
			
			CALCULATE(
			    SUM(CensoHechos[Valor]),
			    CensoHechos[id_indicador] = 6200205284
			)
			
			```
		lineageTag: d0015f22-fbce-4587-96c0-f107bdd72a0a

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure PoblacionNacidaOtroPais_2020 = ```
			
			CALCULATE(
			    SUM(CensoHechos[Valor]),
			    CensoHechos[id_indicador] = 6200205259,
			    CensoHechos[Año] = 2020
			)
			
			```
		lineageTag: 7b09c747-be39-4a51-a719-8fe650fc18ce

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure PoblacionEmigrante_2020 = ```
			
			CALCULATE(
			    SUM(CensoHechos[Valor]),
			    CensoHechos[id_indicador] = 6200205277,
			    CensoHechos[Año] = 2020
			)
			
			```
		lineageTag: bbd535c9-f476-40ec-93a6-f1f9acd10cac

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure PoblacionInmigrante_2020 = ```
			
			CALCULATE(
			    SUM(CensoHechos[Valor]),
			    CensoHechos[id_indicador] = 6200205252,
			    CensoHechos[Año] = 2020
			)
			
			```
		lineageTag: 3dda8925-d8bb-488c-a95d-5a96f9ff057d

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	partition Migración = m
		mode: import
		source =
				let
				    Origen = Table.FromRows(Json.Document(Binary.Decompress(Binary.FromText("i44FAA==", BinaryEncoding.Base64), Compression.Deflate)), let _t = ((type nullable text) meta [Serialized.Text = true]) in type table [Columna1 = _t]),
				    #"Tipo cambiado" = Table.TransformColumnTypes(Origen,{{"Columna1", type text}}),
				    #"Columnas quitadas" = Table.RemoveColumns(#"Tipo cambiado",{"Columna1"})
				in
				    #"Columnas quitadas"

	annotation PBI_ResultType = Table

