table 'Carencias Promedio'
	lineageTag: 64243599-caf4-45f7-b3ea-5500fb8be62d

	measure 'Poblacion Tres o Mas Carencias Sociales' = ```
			
			CALCULATE(
			    SUM(Pobreza[VALOR]),
			    FILTER(
			        Pobreza,
			        Pobreza[INDICADORES] IN {
			            "POBLACIÓN CON TRES O MAS CARENCIAS SOCIALES PERSONAS 2010",
			            "POBLACIÓN CON TRES O MAS CARENCIAS SOCIALES PERSONAS 2015",
			            "POBLACIÓN CON TRES O MAS CARENCIAS SOCIALES PERSONAS 2020"
			        } &&
			        Pobreza[MUNICIPIO] = "Estatal"
			    )
			)
			
			```
		lineageTag: a3b33708-87d4-46e9-a63d-ce94d6458372

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure 'Poblacion Al Menos Una Carencia Social' = ```
			
			CALCULATE(
			    SUM(Pobreza[VALOR]),
			    FILTER(
			        Pobreza,
			        Pobreza[INDICADORES] IN {
			            "POBLACIÓN CON AL MENOS UNA CARENCIA SOCIAL PERSONAS 2010",
			            "POBLACIÓN CON AL MENOS UNA CARENCIA SOCIAL PERSONAS 2015",
			            "POBLACIÓN CON AL MENOS UNA CARENCIA SOCIAL PERSONAS 2020"
			        } &&
			        Pobreza[MUNICIPIO] = "Estatal"
			    )
			)
			
			```
		lineageTag: 63232bd9-72dd-459c-8185-d6331efd226f

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure 'Pobreza Extrema Carencias Promedio' = ```
			
			CALCULATE(
			    AVERAGE(Pobreza[VALOR]),
			    FILTER(
			        Pobreza,
			        Pobreza[INDICADORES] IN {
			            "POBREZA EXTREMA CARENCIAS PROMEDIO 2010",
			            "POBREZA EXTREMA CARENCIAS PROMEDIO 2015",
			            "POBREZA EXTREMA CARENCIAS PROMEDIO 2020"
			        } &&
			        Pobreza[MUNICIPIO] = "Estatal"
			    )
			)
			
			```
		lineageTag: 9bc21e12-3cdd-43c8-baa0-8d8693336e1a

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure 'Carencias Promedio' = ```
			
			CALCULATE(
			    AVERAGE(Pobreza[VALOR]),
			    FILTER(
			        Pobreza,
			        Pobreza[INDICADORES] IN {
			            "CARENCIAS PROMEDIO 2010",
			            "CARENCIAS PROMEDIO 2015",
			            "CARENCIAS PROMEDIO 2020"
			        } &&
			        Pobreza[MUNICIPIO] = "Estatal"
			    )
			)
			
			```
		lineageTag: 3fc26c05-feaf-46bb-be9a-73a41e5b6320

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	partition 'Carencias Promedio' = m
		mode: import
		source =
				let
				    Origen = Table.FromRows(Json.Document(Binary.Decompress(Binary.FromText("i44FAA==", BinaryEncoding.Base64), Compression.Deflate)), let _t = ((type nullable text) meta [Serialized.Text = true]) in type table [Columna1 = _t]),
				    #"Tipo cambiado" = Table.TransformColumnTypes(Origen,{{"Columna1", type text}}),
				    #"Columnas quitadas" = Table.RemoveColumns(#"Tipo cambiado",{"Columna1"})
				in
				    #"Columnas quitadas"

	annotation PBI_ResultType = Table

