table POBREZA
	lineageTag: 005a63bc-8672-4e1e-a76c-5836d55a6279

	column CVE_ENTIDAD
		dataType: string
		lineageTag: 01aaa899-caca-41a8-9482-f0d6c9144cb4
		summarizeBy: none
		sourceColumn: CVE_ENTIDAD

		annotation SummarizationSetBy = Automatic

	column ENTIDAD
		dataType: string
		lineageTag: 1d84bb47-fc82-4967-b4bf-f75bf0499ea7
		summarizeBy: none
		sourceColumn: ENTIDAD

		annotation SummarizationSetBy = Automatic

	column CVE_MUNICIPIO
		dataType: string
		lineageTag: 76d6a22f-2860-422c-8e3d-c44932f8930f
		summarizeBy: none
		sourceColumn: CVE_MUNICIPIO

		annotation SummarizationSetBy = Automatic

	column MUNICIPIO
		dataType: string
		lineageTag: af1c5f43-5646-4b06-bfa7-50e60706de0e
		summarizeBy: none
		sourceColumn: MUNICIPIO

		annotation SummarizationSetBy = Automatic

	column AÑO
		dataType: string
		lineageTag: 4babf386-b330-4764-809c-762b7c6551bb
		summarizeBy: none
		sourceColumn: AÑO

		changedProperty = DataType

		annotation SummarizationSetBy = Automatic

	column INDICADORES
		dataType: string
		lineageTag: be93144e-a564-434a-8f9c-92948a292bf5
		summarizeBy: none
		sourceColumn: INDICADORES

		annotation SummarizationSetBy = Automatic

	column VALOR
		dataType: double
		lineageTag: 34e58fb5-747e-4776-bbe1-c27b92935ad4
		summarizeBy: sum
		sourceColumn: VALOR

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	partition POBREZA = m
		mode: import
		source =
				let
				    Origen = Table.Combine({#"Concentrado estatal", POBREZAMUNICIPAL}),
				    #"Tipo cambiado" = Table.TransformColumnTypes(Origen,{{"CVE_MUNICIPIO", type text}}),
				    #"Filas filtradas" = Table.SelectRows(#"Tipo cambiado", each true)
				in
				    #"Filas filtradas"

	annotation PBI_NavigationStepName = Navegación

	annotation PBI_ResultType = Table

