table Títulos
	lineageTag: a504dee9-86bf-4bf4-8b9d-916c53549c36

	measure 'Titulo Poblacion' = ```
			
			IF(
			    SELECTEDVALUE(Pobreza[ENTIDAD]) = "Ciudad de México",
			    "Población en la Alcaldía de " & SELECTEDVALUE(Pobreza[MUNICIPIO]),
			    "Población en el Municipio de " & SELECTEDVALUE(Pobreza[MUNICIPIO])
			)
			
			```
		lineageTag: aa8bccb1-0699-4d7e-a735-c534f840ac47

	measure 'Titulo Poblacion No Pobre' = ```
			
			IF(
			    SELECTEDVALUE(Pobreza[ENTIDAD]) = "Ciudad de México",
			    "Población no Pobre, Vulnerable y en Pobreza en la Alcaldía de " & SELECTEDVALUE(Pobreza[MUNICIPIO]),
			    "Población no Pobre,  Vulnerable y en Pobreza en el Municipio de " & SELECTEDVALUE(Pobreza[MUNICIPIO])
			)
			
			```
		lineageTag: 5c918844-8e96-4d42-8768-df9ebc8535e2

	measure 'Titulo Pobreza Moderada y Extrema' = ```
			
			IF(
			    SELECTEDVALUE(Pobreza[ENTIDAD]) = "Ciudad de México",
			    "Población en Pobreza Moderada y Extrema en la Alcaldía de " & SELECTEDVALUE(Pobreza[MUNICIPIO]),
			    "Población en Pobreza Moderada y Extrema en el Municipio de " & SELECTEDVALUE(Pobreza[MUNICIPIO])
			)
			
			```
		lineageTag: 147f5f90-415b-4bf7-ba50-5a5f89b465cc

	measure 'Titulo Ingreso Inferior Linea' = ```
			
			IF(
			    SELECTEDVALUE(Pobreza[ENTIDAD]) = "Ciudad de México",
			    "Líneas de Pobreza por Ingresos y Pobreza Extrema por Ingresos en la Alcaldía de " & SELECTEDVALUE(Pobreza[MUNICIPIO]),
			    "Líneas de Pobreza por Ingresos y Pobreza Extrema por Ingresos en el Municipio de " & SELECTEDVALUE(Pobreza[MUNICIPIO])
			)
			
			```
		lineageTag: 5c9d4140-3527-44d7-bd35-7a800bbc68a0

	measure 'Titulo Poblacion Carencias' = ```
			
			IF(
			    SELECTEDVALUE(Pobreza[ENTIDAD]) = "Ciudad de México",
			    "Población con Carencias en la Alcaldía de " & SELECTEDVALUE(Pobreza[MUNICIPIO]),
			    "Población con Carencias en el Municipio de " & SELECTEDVALUE(Pobreza[MUNICIPIO])
			)
			
			```
		lineageTag: 3e19e0fd-6ea9-466d-a388-424b53766ab9

	measure 'Titulo Carencias Promedio' = ```
			
			IF(
			    SELECTEDVALUE(Pobreza[ENTIDAD]) = "Ciudad de México",
			    "Población con Carencias Promedio en la Alcaldía de " & SELECTEDVALUE(Pobreza[MUNICIPIO]),
			    "Población con Carencias Promedio en el Municipio de " & SELECTEDVALUE(Pobreza[MUNICIPIO])
			)
			
			```
		lineageTag: a7f09602-3aa3-42cc-803f-dd581d4d4dcf

	partition Títulos = m
		mode: import
		source =
				let
				    Origen = Table.FromRows(Json.Document(Binary.Decompress(Binary.FromText("i44FAA==", BinaryEncoding.Base64), Compression.Deflate)), let _t = ((type nullable text) meta [Serialized.Text = true]) in type table [Columna1 = _t]),
				    #"Tipo cambiado" = Table.TransformColumnTypes(Origen,{{"Columna1", type text}}),
				    #"Columnas quitadas" = Table.RemoveColumns(#"Tipo cambiado",{"Columna1"})
				in
				    #"Columnas quitadas"

	annotation PBI_ResultType = Table

