table Salud
	lineageTag: c0dca7cb-2dd8-4beb-bedb-c15c08e669a7

	measure 'Población Derecho habiente Salud_2020' = ```
			
			CALCULATE(
			    SUM(CensoHechos[Valor]),
			    CensoHechos[id_indicador] = 1004000001,
			    CensoHechos[Año] = 2020
			)
			
			```
		lineageTag: 168cc1c6-b544-4206-9223-e8079439294c

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure PorcentajeUsuarioServiciosSalud_2020 = ```
			
			CALCULATE(
			    SUM(CensoHechos[Valor]),
			    CensoHechos[id_indicador] = 6200240321,
			    CensoHechos[Año] = 2020
			)
			
			```
		lineageTag: feea5751-8207-4629-830b-c837b9cade2a

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure PorcentajeDerechohabienteSeguroPopular_2020 = ```
			
			CALCULATE(
			    SUM(CensoHechos[Valor]),
			    CensoHechos[id_indicador] = 6200240323,
			    CensoHechos[Año] = 2020
			)
			
			```
		lineageTag: ee4d989e-08d3-4f6f-a214-b4f9bebd4de0

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure '% PEMEX_2020' = ```
			
			CALCULATE(
			    SUM(CensoHechos[Valor]),
			    CensoHechos[id_indicador] = 6200240414,
			    CensoHechos[Año] = 2020
			)
			
			```
		lineageTag: dfd51e5a-de44-449b-96fd-38e87d3d52e7

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure '% Usuario Servicios Médicos Privados_2020' = ```
			
			CALCULATE(
			    SUM(CensoHechos[Valor]),
			    CensoHechos[id_indicador] = 6200240416,
			    CensoHechos[Año] = 2020
			)
			
			```
		lineageTag: 66d8ff64-4ad5-43f2-88dd-bb488923759d

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure '% ISSSTE_2020' = ```
			
			CALCULATE(
			    SUM(CensoHechos[Valor]),
			    CensoHechos[id_indicador] = 6200240421,
			    CensoHechos[Año] = 2020
			)
			
			```
		lineageTag: 510d1a1c-35c6-4f37-a48f-9236f65445cb

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure '% IMSS_2020' = ```
			
			CALCULATE(
			    SUM(CensoHechos[Valor]),
			    CensoHechos[id_indicador] = 6200240471,
			    CensoHechos[Año] = 2020
			)
			
			```
		lineageTag: cafe48b3-61a4-47b6-8837-04f452d198c3

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure PorcentajeUsuarioServiciosSeguridadSocial_2020 = ```
			
			CALCULATE(
			    SUM(CensoHechos[Valor]),
			    CensoHechos[id_indicador] = 6200240511,
			    CensoHechos[Año] = 2020
			)
			
			```
		lineageTag: 2fa6a3b6-b6b6-4c0b-80b8-5a506afb2e64

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure PorcentajeDerechohabienteOtrasInstituciones_2020 = ```
			
			CALCULATE(
			    SUM(CensoHechos[Valor]),
			    CensoHechos[id_indicador] = 6200240517,
			    CensoHechos[Año] = 2020
			)
			
			```
		lineageTag: 36219c76-349d-4854-a422-44b662bc1871

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure PorcentajeAfiliadaServiciosSalud_2020 = ```
			
			CALCULATE(
			    SUM(CensoHechos[Valor]),
			    CensoHechos[id_indicador] = 6207019018,
			    CensoHechos[Año] = 2020
			)
			
			```
		lineageTag: 19cafbf9-c059-4b59-a60e-5414e81df8c3

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure PoblacionDerechohabienteSalud = ```
			
			CALCULATE(
			    SUM(CensoHechos[Valor]),
			    CensoHechos[id_indicador] = 1004000001
			)
			
			```
		lineageTag: 2c85016a-dc64-4fcb-810e-a90d78e55a8e

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure PorcentajeAfiliadaServiciosSalud = ```
			
			CALCULATE(
			    AVERAGE(CensoHechos[Valor]),
			    CensoHechos[id_indicador] = 6207019018
			)
			
			```
		lineageTag: 8abaf182-6722-4b2c-a39f-e671b2f961f3

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure PorcentajeUsuarioServiciosSalud = ```
			
			CALCULATE(
			    SUM(CensoHechos[Valor]),
			    CensoHechos[id_indicador] = 6200240321
			)
			
			```
		lineageTag: 69cd767d-8015-4fc5-a4a1-d7d7484f1e4f

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure '% Derechohabiente IMSS-Bienestar_2020' = ```
			
			CALCULATE(
			    SUM(CensoHechos[Valor]),
			    CensoHechos[id_indicador] = 6207129818,
			    CensoHechos[Año] = 2020
			)
			
			```
		lineageTag: 96e9c9ff-43e9-4947-b4ae-6d7dbc2c3abb

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure '% IMSS-Bienestar' = ```
			
			CALCULATE(
			    SUM(CensoHechos[Valor]),
			    CensoHechos[id_indicador] = 6207129818
			)
			
			```
		lineageTag: e09f5551-76a7-42a8-9b83-50eeee99dbfa

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	partition Salud = m
		mode: import
		source =
				let
				    Origen = Table.FromRows(Json.Document(Binary.Decompress(Binary.FromText("i44FAA==", BinaryEncoding.Base64), Compression.Deflate)), let _t = ((type nullable text) meta [Serialized.Text = true]) in type table [Columna1 = _t]),
				    #"Tipo cambiado" = Table.TransformColumnTypes(Origen,{{"Columna1", type text}}),
				    #"Columnas quitadas" = Table.RemoveColumns(#"Tipo cambiado",{"Columna1"})
				in
				    #"Columnas quitadas"

	annotation PBI_ResultType = Table

