table Canasta2025pormes
	lineageTag: 2a10dc5e-d92c-4f2f-9a8d-c20b43c38acb

	column FECHA
		dataType: dateTime
		formatString: Long Date
		lineageTag: 97f10207-79f3-4902-8d32-f43a8a3ea5ab
		summarizeBy: none
		sourceColumn: FECHA

		annotation SummarizationSetBy = Automatic

		annotation UnderlyingDateTimeDataType = Date

	column PRODUCTO
		dataType: string
		lineageTag: 44bb1b4c-285d-4ea3-b41f-e046e0db50a7
		summarizeBy: none
		sourceColumn: PRODUCTO

		annotation SummarizationSetBy = Automatic

	column 'PRECIO DICONSA ($)'
		dataType: decimal
		formatString: \$#,0.###############;-\$#,0.###############;\$#,0.###############
		lineageTag: 186646bf-e107-4fbf-a4e8-d3d22ec3d7a1
		summarizeBy: sum
		sourceColumn: PRECIO DICONSA ($)

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"currencyCulture":"es-MX"}

	column 'PRECIO PROFECO ($)'
		dataType: decimal
		formatString: \$#,0.###############;-\$#,0.###############;\$#,0.###############
		lineageTag: 184c58b9-d06b-4090-8e2a-14e69d57e55b
		summarizeBy: sum
		sourceColumn: PRECIO PROFECO ($)

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"currencyCulture":"es-MX"}

	column 'MARGEN DE AHORRO (%)'
		dataType: decimal
		formatString: \$#,0.###############;-\$#,0.###############;\$#,0.###############
		lineageTag: 271eea5e-1c9a-42de-992c-f610b1a9387a
		summarizeBy: sum
		sourceColumn: MARGEN DE AHORRO (%)

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"currencyCulture":"es-MX"}

	column 'Categoria Ahorro' =
			
			SWITCH(
			    TRUE(),
			    Canasta2025pormes[MARGEN DE AHORRO (%)] < 0, "Más Caro en DICONSA",
			    Canasta2025pormes[MARGEN DE AHORRO (%)] <= 25, "Ahorro Bajo (0-25%)",
			    Canasta2025pormes[MARGEN DE AHORRO (%)] <= 50, "Ahorro Moderado (25-50%)",
			    Canasta2025pormes[MARGEN DE AHORRO (%)] <= 100, "Ahorro Alto (50-100%)",
			    "Ahorro Excepcional (>100%)"
			)
		lineageTag: b272f13c-8b1e-4462-b73a-7b5b8945429a
		summarizeBy: none

		annotation SummarizationSetBy = Automatic

	partition Canasta2025pormes = m
		mode: import
		source =
				let
				    Source = Csv.Document(Web.Contents("https://docs.google.com/spreadsheets/d/e/2PACX-1vTgFyHMneyy5sCApuf7ZhLPgRtr6cXOLnbNgpxZ2H5lUvsAEFerjpgDsSpv18uCWWKN9yrKaavHs0bS/pub?output=csv"),[Delimiter=",", Columns=5, Encoding=65001, QuoteStyle=QuoteStyle.None]),
				    #"Promoted Headers" = Table.PromoteHeaders(Source, [PromoteAllScalars=true]),
				    #"Replaced Value" = Table.ReplaceValue(#"Promoted Headers","Insecticidas y Raticidas (230 mL)","Insecticidas y Raticidas (230 ml)",Replacer.ReplaceText,{"PRODUCTO"}),
				    #"Changed Type" = Table.TransformColumnTypes(#"Replaced Value",{{"FECHA", type date}, {"PRECIO DICONSA ($)*", Currency.Type}, {"PRECIO PROFECO ($)**", Currency.Type}, {"MARGEN DE AHORRO (%)", Currency.Type}}),
				    #"Renamed Columns" = Table.RenameColumns(#"Changed Type",{{"PRECIO DICONSA ($)*", "PRECIO DICONSA ($)"}, {"PRECIO PROFECO ($)**", "PRECIO PROFECO ($)"}})
				in
				    #"Renamed Columns"

	annotation PBI_NavigationStepName = Navigation

	annotation PBI_ResultType = Table

