table MUNICIPIOS
	lineageTag: 8a85851e-3746-420a-b4f9-072344d2a45d

	column id
		dataType: string
		isHidden
		lineageTag: 9ce71998-99a3-4c51-b120-1dcb5ec3fc45
		summarizeBy: none
		sourceColumn: id

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

	column id_municipio_completo
		dataType: string
		isHidden
		lineageTag: 3a53d032-3dbe-4dda-af1e-e353d6d692db
		summarizeBy: none
		sourceColumn: id_municipio_completo

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

	column cve_ent
		dataType: string
		isHidden
		lineageTag: 26fa4355-9af5-49ef-a007-bf433f349ae0
		summarizeBy: none
		sourceColumn: cve_ent

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

	column cve_mun
		dataType: string
		isHidden
		lineageTag: e7eeef9c-87da-4733-91af-2ce7f541577b
		summarizeBy: none
		sourceColumn: cve_mun

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

	column municipio
		dataType: string
		lineageTag: eed9f3c7-f742-4089-8ae2-9e46109e4f83
		summarizeBy: none
		sourceColumn: municipio

		annotation SummarizationSetBy = Automatic

	hierarchy Ubicación
		lineageTag: f9b73d31-748e-44a4-b88f-4a9c910d3f46

		level cve_ent
			lineageTag: 87f8fa5f-3c5e-4c08-8adb-b9876f89090f
			column: cve_ent

		level municipio
			lineageTag: e6f9b2ce-e297-4552-86e4-74bf70009810
			column: municipio

	partition MUNICIPIOS = m
		mode: import
		source =
				let
				    Source = Sql.Database("qihyhmenysou5otulys7x473hm-wmsh36vm2hsepif26nl54mytlu.datawarehouse.fabric.microsoft.com", "lh_lokus_denue"),
				    dbo_denue_empresas_mexico_final = Source{[Schema="dbo",Item="denue_empresas_mexico_final"]}[Data],
				    #"Removed Columns" = Table.RemoveColumns(dbo_denue_empresas_mexico_final,{"tipo_vial", "nom_vial", "tipo_v_e_1", "nom_v_e_1", "tipo_v_e_2", "nom_v_e_2", "tipo_v_e_3", "nom_v_e_3", "numero_ext", "letra_ext", "edificio", "edificio_e", "numero_int", "letra_int", "archivo_origen", "nom_CenCom", "num_local", "telefono", "correoelec", "www", "tipoUniEco", "clee", "nom_estab", "raz_social", "codigo_act", "nombre_act", "per_ocu", "tipo_asent", "nomb_asent", "tipoCenCom", "cod_postal", "entidad", "cve_loc", "localidad", "ageb", "manzana", "latitud", "longitud", "fecha_alta", "sector_codigo", "sector_nombre"}),
				    #"Added Custom" = Table.AddColumn(#"Removed Columns", "Personalizado", each Text.PadStart(Text.From([cve_ent]), 2, "0")),
				    #"Removed Columns1" = Table.RemoveColumns(#"Added Custom",{"cve_ent"}),
				    #"Renamed Columns" = Table.RenameColumns(#"Removed Columns1",{{"Personalizado", "cve_ent"}}),
				    #"Reordered Columns" = Table.ReorderColumns(#"Renamed Columns",{"cve_mun", "id", "cve_ent", "municipio"}),
				    #"Added Custom1" = Table.AddColumn(#"Reordered Columns", "Personalizado", each Text.PadStart(Text.From([cve_mun]), 3, "0")),
				    #"Removed Columns2" = Table.RemoveColumns(#"Added Custom1",{"cve_mun"}),
				    #"Renamed Columns1" = Table.RenameColumns(#"Removed Columns2",{{"Personalizado", "cve_mun"}}),
				    #"Reordered Columns1" = Table.ReorderColumns(#"Renamed Columns1",{"id", "cve_ent", "cve_mun", "municipio"}),
				    #"Changed Type" = Table.TransformColumnTypes(#"Reordered Columns1",{{"cve_ent", type text}, {"cve_mun", type text}}),
				    #"Added Custom2" = Table.AddColumn(#"Changed Type", "id_municipio_completo", each [cve_ent] & [cve_mun]),
				    #"Changed Type1" = Table.TransformColumnTypes(#"Added Custom2",{{"id_municipio_completo", type text}}),
				    #"Removed Duplicates" = Table.Distinct(#"Changed Type1", {"id_municipio_completo"}),
				    #"Reordered Columns2" = Table.ReorderColumns(#"Removed Duplicates",{"id", "id_municipio_completo", "cve_ent", "cve_mun", "municipio"})
				in
				    #"Reordered Columns2"

	annotation PBI_NavigationStepName = Navigation

	annotation PBI_ResultType = Table

