table Estados
	lineageTag: ff5b0847-44d0-4a5f-bca3-7fd8f3aafa70

	column CVE_ESTADO
		dataType: string
		lineageTag: 6c95ec9b-6f54-4b16-874c-d0000afb5186
		summarizeBy: none
		sourceColumn: CVE_ESTADO

		annotation SummarizationSetBy = Automatic

	column ESTADO
		dataType: string
		lineageTag: 60e02d3d-6bf3-4b56-b33c-b29702af3555
		summarizeBy: none
		sourceColumn: ESTADO

		annotation SummarizationSetBy = Automatic

	partition Estados = m
		mode: import
		source =
				let
				    Origen = Table.Combine({GRSMUNICPIOS, GRSESTADOS}),
				    #"Duplicados quitados" = Table.Distinct(Origen, {"ESTADO"}),
				    #"Columnas quitadas" = Table.RemoveColumns(#"Duplicados quitados",{"CVE_MUNICIPIO", "MUNICIPIO", "POBLACIÓN TOTAL", "% Población de 15 años o más analfabeta", "% Población de 6 a 14 años que no asiste a la escuela", "% Población de 15 años y más con educación básica incompleta", "% Población sin derechohabiencia a servicios de salud", "% Viviendas con piso de tierra", "% Viviendas que no disponen de excusado o sanitario", "% Viviendas que no disponen de agua entubada de la red pública", "% Viviendas que no disponen de drenaje", "% Viviendas que no disponen de energía eléctrica", "% Viviendas que no disponen de lavadora", "% Viviendas que no disponen de refrigerador", "INDICE DE REZAGO SOCIAL", "GRADO DE REZAGO SOCIAL", "LUGAR QUE OCUPA EN EL CONTEXTO NACIONAL", "AÑO", "ID"})
				in
				    #"Columnas quitadas"

	annotation PBI_NavigationStepName = Navegación

	annotation PBI_ResultType = Table

