table 'POBREZA (3)'
	isHidden
	lineageTag: 0358a3bb-54e7-43a6-9468-d85a115ebfbc

	column CVE_ENTIDAD
		dataType: string
		isHidden
		lineageTag: b82b79bd-f8fe-47ef-a71c-71416b4bb41e
		summarizeBy: none
		sourceColumn: CVE_ENTIDAD

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

	column ENTIDAD
		dataType: string
		isHidden
		lineageTag: bcd1ecfe-7986-48ce-9099-e7b82804ba5f
		summarizeBy: none
		sourceColumn: ENTIDAD

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

	column CVE_MUNICIPIO
		dataType: string
		isHidden
		lineageTag: 59d1a62e-734d-40e0-b94e-c5766bdabddc
		summarizeBy: none
		sourceColumn: CVE_MUNICIPIO

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

	column MUNICIPIO
		dataType: string
		isHidden
		lineageTag: c6e4f84a-ff84-4ad6-99dc-d5916c8501ae
		summarizeBy: none
		sourceColumn: MUNICIPIO

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

	column AÑO
		dataType: int64
		isHidden
		formatString: 0
		lineageTag: 29bcc9f6-6b9e-49f3-be41-deeb745ee7bd
		summarizeBy: sum
		sourceColumn: AÑO

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

	column TEMA
		dataType: string
		isHidden
		lineageTag: 2d60569b-f136-484f-89ad-391c1abc2626
		summarizeBy: none
		sourceColumn: TEMA

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

	column SUBTEMA
		dataType: string
		isHidden
		lineageTag: 4d121748-6090-4da0-8ec8-51608b5df64f
		summarizeBy: none
		sourceColumn: SUBTEMA

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

	column 'VALOR Formateado'
		dataType: double
		isHidden
		lineageTag: b44e1a9b-0a44-4105-834c-9bbfd84b7a50
		summarizeBy: sum
		sourceColumn: VALOR Formateado

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	partition 'POBREZA (3)' = m
		mode: import
		source =
				let
				    Origen = Table.Combine({#"Concentrado estatal", POBREZAMUNICIPAL}),
				    #"Tipo cambiado" = Table.TransformColumnTypes(Origen,{{"CVE_MUNICIPIO", type text}}),
				    #"Filas filtradas" = Table.SelectRows(#"Tipo cambiado", each true),
				    #"Valor reemplazado" = Table.ReplaceValue(#"Filas filtradas","Población 2010","POBLACIÓN 2010",Replacer.ReplaceText,{"INDICADORES"}),
				    #"Valor reemplazado1" = Table.ReplaceValue(#"Valor reemplazado","Población 2015","POBLACIÓN 2015",Replacer.ReplaceText,{"INDICADORES"}),
				    #"Valor reemplazado2" = Table.ReplaceValue(#"Valor reemplazado1","Población 2020","POBLACIÓN 2020",Replacer.ReplaceText,{"INDICADORES"}),
				    #"Valor reemplazado3" = Table.ReplaceValue(#"Valor reemplazado2","POBREZA EXTREMAS CARENCIAS PROMEDIO 2010","POBREZA EXTREMA CARENCIAS PROMEDIO 2010",Replacer.ReplaceText,{"INDICADORES"}),
				    #"Valor reemplazado4" = Table.ReplaceValue(#"Valor reemplazado3","CARENCIA POR CALIDAD Y ESPACIOS DE LA VIVIENDA  PERSONAS 2010","CARENCIAS POR CALIDAD Y ESPACIOS DE LA VIVIENDA  PERSONAS 2010",Replacer.ReplaceText,{"INDICADORES"}),
				    #"Valor reemplazado5" = Table.ReplaceValue(#"Valor reemplazado4","CARENCIA POR CALIDAD Y ESPACIOS DE LA VIVIENDA PORCENTAJE 2010","CARENCIAS POR CALIDAD Y ESPACIOS DE LA VIVIENDA PORCENTAJE 2010",Replacer.ReplaceText,{"INDICADORES"}),
				    #"Valor reemplazado6" = Table.ReplaceValue(#"Valor reemplazado5","CARENCIA POR CALIDAD Y ESPACIOS DE LA VIVIENDA PORCENTAJE 2015","CARENCIAS POR CALIDAD Y ESPACIOS DE LA VIVIENDA PORCENTAJE 2015",Replacer.ReplaceText,{"INDICADORES"}),
				    #"Valor reemplazado7" = Table.ReplaceValue(#"Valor reemplazado6","CARENCIA POR CALIDAD Y ESPACIOS DE LA VIVIENDA  PORCENTAJE 2010","CARENCIAS POR CALIDAD Y ESPACIOS DE LA VIVIENDA  PORCENTAJE 2010",Replacer.ReplaceText,{"INDICADORES"}),
				    #"Valor reemplazado8" = Table.ReplaceValue(#"Valor reemplazado7","CARENCIA POR CALIDAD Y ESPACIOS DE LA VIVIENDA  PORCENTAJE 2015","CARENCIAS POR CALIDAD Y ESPACIOS DE LA VIVIENDA  PORCENTAJE 2015",Replacer.ReplaceText,{"INDICADORES"}),
				    #"Valor reemplazado9" = Table.ReplaceValue(#"Valor reemplazado8","CARENCIA POR CALIDAD Y ESPACIOS DE LA VIVIENDA  PORCENTAJE 2020","CARENCIAS POR CALIDAD Y ESPACIOS DE LA VIVIENDA  PORCENTAJE 2020",Replacer.ReplaceText,{"INDICADORES"}),
				    #"Valor reemplazado10" = Table.ReplaceValue(#"Valor reemplazado9","CARENCIA POR CALIDAD Y ESPACIOS DE LA VIVIENDA  PERSONAS 2015","CARENCIAS POR CALIDAD Y ESPACIOS DE LA VIVIENDA  PERSONAS 2015",Replacer.ReplaceText,{"INDICADORES"}),
				    #"Valor reemplazado11" = Table.ReplaceValue(#"Valor reemplazado10","CARENCIA POR CALIDAD Y ESPACIOS DE LA VIVIENDA  PERSONAS 2020","CARENCIAS POR CALIDAD Y ESPACIOS DE LA VIVIENDA  PERSONAS 2020",Replacer.ReplaceText,{"INDICADORES"}),
				    #"Valor reemplazado12" = Table.ReplaceValue(#"Valor reemplazado11","CARENCIA POR ACCESO A LA ALIMENTACIÓN PORCENTAJE 2010","CARENCIAS POR ACCESO A LA ALIMENTACIÓN PORCENTAJE 2010",Replacer.ReplaceText,{"INDICADORES"}),
				    #"Valor reemplazado13" = Table.ReplaceValue(#"Valor reemplazado12","CARENCIA POR ACCESO A LA ALIMENTACIÓN PORCENTAJE 2015","CARENCIAS POR ACCESO A LA ALIMENTACIÓN PORCENTAJE 2015",Replacer.ReplaceText,{"INDICADORES"}),
				    #"Valor reemplazado14" = Table.ReplaceValue(#"Valor reemplazado13","CARENCIA POR ACCESO A LA ALIMENTACIÓN PORCENTAJE 2020","CARENCIAS POR ACCESO A LA ALIMENTACIÓN PORCENTAJE 2020",Replacer.ReplaceText,{"INDICADORES"}),
				    #"Valor reemplazado15" = Table.ReplaceValue(#"Valor reemplazado14","CARENCIA POR ACCESO A LA ALIMENTACIÓN PERSONAS 2015","CARENCIAS POR ACCESO A LA ALIMENTACIÓN PERSONAS 2015",Replacer.ReplaceText,{"INDICADORES"}),
				    #"Valor reemplazado16" = Table.ReplaceValue(#"Valor reemplazado15","CARENCIA POR ACCESO A LA ALIMENTACIÓN PERSONAS 2020","CARENCIAS POR ACCESO A LA ALIMENTACIÓN PERSONAS 2020",Replacer.ReplaceText,{"INDICADORES"}),
				    #"Valor reemplazado17" = Table.ReplaceValue(#"Valor reemplazado16","CARENCIA POR ACCESO A LA ALIMENTACIÓN PERSONAS 2010","CARENCIAS POR ACCESO A LA ALIMENTACIÓN PERSONAS 2010",Replacer.ReplaceText,{"INDICADORES"}),
				    #"Valor reemplazado18" = Table.ReplaceValue(#"Valor reemplazado17","CARENCIAS POR CALIDAD Y ESPACIOS DE LA VIVIENDA  PERSONAS 2010","CARENCIAS POR CALIDAD Y ESPACIOS DE LA VIVIENDA PERSONAS 2010",Replacer.ReplaceText,{"INDICADORES"}),
				    #"Valor reemplazado19" = Table.ReplaceValue(#"Valor reemplazado18","CARENCIAS POR CALIDAD Y ESPACIOS DE LA VIVIENDA  PORCENTAJE 2010","CARENCIAS POR CALIDAD Y ESPACIOS DE LA VIVIENDA PORCENTAJE 2010",Replacer.ReplaceText,{"INDICADORES"}),
				    #"Valor reemplazado20" = Table.ReplaceValue(#"Valor reemplazado19","CARENCIAS POR CALIDAD Y ESPACIOS DE LA VIVIENDA  PORCENTAJE 2015","CARENCIAS POR CALIDAD Y ESPACIOS DE LA VIVIENDA PORCENTAJE 2015",Replacer.ReplaceText,{"INDICADORES"}),
				    #"Valor reemplazado21" = Table.ReplaceValue(#"Valor reemplazado20","CARENCIAS POR CALIDAD Y ESPACIOS DE LA VIVIENDA  PORCENTAJE 2020","CARENCIAS POR CALIDAD Y ESPACIOS DE LA VIVIENDA PORCENTAJE 2020",Replacer.ReplaceText,{"INDICADORES"}),
				    #"Valor reemplazado22" = Table.ReplaceValue(#"Valor reemplazado21","CARENCIAS POR CALIDAD Y ESPACIOS DE LA VIVIENDA  PERSONAS 2015","CARENCIAS POR CALIDAD Y ESPACIOS DE LA VIVIENDA PERSONAS 2015",Replacer.ReplaceText,{"INDICADORES"}),
				    #"Valor reemplazado23" = Table.ReplaceValue(#"Valor reemplazado22","CARENCIAS POR CALIDAD Y ESPACIOS DE LA VIVIENDA  PERSONAS 2020","CARENCIAS POR CALIDAD Y ESPACIOS DE LA VIVIENDA PERSONAS 2020",Replacer.ReplaceText,{"INDICADORES"}),
				    #"Valor reemplazado24" = Table.ReplaceValue(#"Valor reemplazado23","POBLACIÓN CON INGRESO INFERIOS A LA lP EXTREMA POR INGRESO PORCENTAJE 2010","POBLACIÓN CON INGRESO INFERIOR A LA LINEA DE POBREZA EXTREMA POR INGRESO PORCENTAJE 2010",Replacer.ReplaceText,{"INDICADORES"}),
				    #"Valor reemplazado25" = Table.ReplaceValue(#"Valor reemplazado24","POBLACIÓN CON INGRESO INFERIOS A LA lP EXTREMA POR INGRESO PORCENTAJE 2015","POBLACIÓN CON INGRESO INFERIOR A LA LINEA DE POBREZA EXTREMA POR INGRESO PORCENTAJE 2015",Replacer.ReplaceText,{"INDICADORES"}),
				    #"Valor reemplazado26" = Table.ReplaceValue(#"Valor reemplazado25","POBLACIÓN CON INGRESO INFERIOS A LA lP EXTREMA POR INGRESO PORCENTAJE 2020","POBLACIÓN CON INGRESO INFERIOR A LA LINEA DE POBREZA EXTREMA POR INGRESO PORCENTAJE 2020",Replacer.ReplaceText,{"INDICADORES"}),
				    #"Valor reemplazado27" = Table.ReplaceValue(#"Valor reemplazado26","POBLACIÓN CON INGRESO INFERIOS A LA lP EXTREMA POR INGRESO PERSONAS 2010","POBLACIÓN CON INGRESO INFERIOR A LA LINEA DE POBREZA EXTREMA POR INGRESO PERSONAS 2010",Replacer.ReplaceText,{"INDICADORES"}),
				    #"Valor reemplazado28" = Table.ReplaceValue(#"Valor reemplazado27","POBLACIÓN CON INGRESO INFERIOS A LA lP EXTREMA POR INGRESO PERSONAS 2015","POBLACIÓN CON INGRESO INFERIOR A LA LINEA DE POBREZA EXTREMA POR INGRESO PERSONAS 2015",Replacer.ReplaceText,{"INDICADORES"}),
				    #"Valor reemplazado29" = Table.ReplaceValue(#"Valor reemplazado28","POBLACIÓN CON INGRESO INFERIOS A LA lP EXTREMA POR INGRESO PERSONAS 2020","POBLACIÓN CON INGRESO INFERIOR A LA LINEA DE POBREZA EXTREMA POR INGRESO PERSONAS 2020",Replacer.ReplaceText,{"INDICADORES"}),
				    #"Valor reemplazado30" = Table.ReplaceValue(#"Valor reemplazado29","POBLACIÓN CON UN INGRESO INFERIOR A LA LPI PORCENTAJE 2010","POBLACIÓN CON UN INGRESO INFERIOR A LA LINEA DE POBREZA POR INGRESO PORCENTAJE 2010",Replacer.ReplaceText,{"INDICADORES"}),
				    #"Valor reemplazado31" = Table.ReplaceValue(#"Valor reemplazado30","POBLACIÓN CON UN INGRESO INFERIOR A LA LPI PORCENTAJE 2015","POBLACIÓN CON UN INGRESO INFERIOR A LA LINEA DE POBREZA POR INGRESO PORCENTAJE 2015",Replacer.ReplaceText,{"INDICADORES"}),
				    #"Valor reemplazado32" = Table.ReplaceValue(#"Valor reemplazado31","POBLACIÓN CON UN INGRESO INFERIOR A LA LPI PORCENTAJE 2020","POBLACIÓN CON UN INGRESO INFERIOR A LA LINEA DE POBREZA POR INGRESO PORCENTAJE 2020",Replacer.ReplaceText,{"INDICADORES"}),
				    #"Valor reemplazado33" = Table.ReplaceValue(#"Valor reemplazado32","POBLACIÓN CON UN INGRESO INFERIOR A LA LPI PERSONAS 2010","POBLACIÓN CON UN INGRESO INFERIOR A LA LINEA DE POBREZA POR INGRESO PERSONAS 2010",Replacer.ReplaceText,{"INDICADORES"}),
				    #"Valor reemplazado34" = Table.ReplaceValue(#"Valor reemplazado33","POBLACIÓN CON UN INGRESO INFERIOR A LA LPI PERSONAS 2015","POBLACIÓN CON UN INGRESO INFERIOR A LA LINEA DE POBREZA POR INGRESO PERSONAS 2015",Replacer.ReplaceText,{"INDICADORES"}),
				    #"Valor reemplazado35" = Table.ReplaceValue(#"Valor reemplazado34","POBLACIÓN CON UN INGRESO INFERIOR A LA LPI PERSONAS 2020","POBLACIÓN CON UN INGRESO INFERIOR A LA LINEA DE POBREZA POR INGRESO PERSONAS 2020",Replacer.ReplaceText,{"INDICADORES"}),
				    #"Valor reemplazado36" = Table.ReplaceValue(#"Valor reemplazado35","VULNERABLES POR INGRESOS PORCENTAJE 2015","VULNERABLES POR INGRESO PORCENTAJE 2015",Replacer.ReplaceText,{"INDICADORES"}),
				    #"Valor reemplazado37" = Table.ReplaceValue(#"Valor reemplazado36","POBLACIÓN CON UN INGRESO INFERIOR A LA LPI 2010","POBLACIÓN CON UN INGRESO INFERIOR A LA LINEA DE POBREZA POR INGRESO PERSONAS 2010",Replacer.ReplaceText,{"INDICADORES"}),
				    #"Valor reemplazado38" = Table.ReplaceValue(#"Valor reemplazado37","POBLACIÓN CON UN INGRESO INFERIOR A LA LPI 2015","POBLACIÓN CON UN INGRESO INFERIOR A LA LINEA DE POBREZA POR INGRESO PERSONAS 2015",Replacer.ReplaceText,{"INDICADORES"}),
				    #"Valor reemplazado39" = Table.ReplaceValue(#"Valor reemplazado38","POBLACIÓN CON UN INGRESO INFERIOR A LA LPI 2020","POBLACIÓN CON UN INGRESO INFERIOR A LA LINEA DE POBREZA POR INGRESO PERSONAS 2020",Replacer.ReplaceText,{"INDICADORES"}),
				    #"Valor reemplazado40" = Table.ReplaceValue(#"Valor reemplazado39","POBLACIÓN CON INGRESO INFERIOS A LA lP EXTREMA POR INGRESO 2010","POBLACIÓN CON INGRESO INFERIOR A LA LINEA DE POBREZA EXTREMA POR INGRESO PERSONAS 2010",Replacer.ReplaceText,{"INDICADORES"}),
				    #"Valor reemplazado41" = Table.ReplaceValue(#"Valor reemplazado40","POBLACIÓN CON INGRESO INFERIOS A LA lP EXTREMA POR INGRESO 2015","POBLACIÓN CON INGRESO INFERIOR A LA LINEA DE POBREZA EXTREMA POR INGRESO PERSONAS 2015",Replacer.ReplaceText,{"INDICADORES"}),
				    #"Valor reemplazado42" = Table.ReplaceValue(#"Valor reemplazado41","POBLACIÓN CON INGRESO INFERIOS A LA lP EXTREMA POR INGRESO 2020","POBLACIÓN CON INGRESO INFERIOR A LA LINEA DE POBREZA EXTREMA POR INGRESO PERSONAS 2020",Replacer.ReplaceText,{"INDICADORES"}),
				    #"Valor reemplazado43" = Table.ReplaceValue(#"Valor reemplazado42","CARENCIAS POR ACCESO A LA SEGURIDAD SOCIAL PORCENTAJE  2015","CARENCIAS POR ACCESO A LA SEGURIDAD SOCIAL PORCENTAJE 2015",Replacer.ReplaceText,{"INDICADORES"}),
				    #"Filas filtradas1" = Table.SelectRows(#"Valor reemplazado43", each ([INDICADORES] <> "CARENCIAS POR ACCESO A LA ALIMENTACIÓN PORCENTAJE 2010" and [INDICADORES] <> "CARENCIAS POR ACCESO A LA ALIMENTACIÓN PORCENTAJE 2015" and [INDICADORES] <> "CARENCIAS POR ACCESO A LA ALIMENTACIÓN PORCENTAJE 2020" and [INDICADORES] <> "CARENCIAS POR ACCESO A LA SEGURIDAD SOCIAL PORCENTAJE 2010" and [INDICADORES] <> "CARENCIAS POR ACCESO A LA SEGURIDAD SOCIAL PORCENTAJE 2015" and [INDICADORES] <> "CARENCIAS POR ACCESO A LA SEGURIDAD SOCIAL PORCENTAJE 2020" and [INDICADORES] <> "CARENCIAS POR ACCESO A LOS SERVICIOS BÁSICOS EN LA VIVIENDA PORCENTAJE 2010" and [INDICADORES] <> "CARENCIAS POR ACCESO A LOS SERVICIOS BÁSICOS EN LA VIVIENDA PORCENTAJE 2015" and [INDICADORES] <> "CARENCIAS POR ACCESO A LOS SERVICIOS BÁSICOS EN LA VIVIENDA PORCENTAJE 2020" and [INDICADORES] <> "CARENCIAS POR ACCESO A LOS SERVICIOS DE SALUD PORCENTAJE 2010" and [INDICADORES] <> "CARENCIAS POR ACCESO A LOS SERVICIOS DE SALUD PORCENTAJE 2015" and [INDICADORES] <> "CARENCIAS POR ACCESO A LOS SERVICIOS DE SALUD PORCENTAJE 2020" and [INDICADORES] <> "CARENCIAS POR CALIDAD Y ESPACIOS DE LA VIVIENDA PORCENTAJE 2010" and [INDICADORES] <> "CARENCIAS POR CALIDAD Y ESPACIOS DE LA VIVIENDA PORCENTAJE 2015" and [INDICADORES] <> "CARENCIAS POR CALIDAD Y ESPACIOS DE LA VIVIENDA PORCENTAJE 2020" and [INDICADORES] <> "NO POBRE Y NO VULNERABLE PORCENTAJE 2010" and [INDICADORES] <> "NO POBRE Y NO VULNERABLE PORCENTAJE 2015" and [INDICADORES] <> "NO POBRE Y NO VULNERABLE PORCENTAJE 2020" and [INDICADORES] <> "POBLACIÓN CON AL MENOS UNA CARENCIA SOCIAL PORCENTAJE 2010" and [INDICADORES] <> "POBLACIÓN CON AL MENOS UNA CARENCIA SOCIAL PORCENTAJE 2015" and [INDICADORES] <> "POBLACIÓN CON AL MENOS UNA CARENCIA SOCIAL PORCENTAJE 2020" and [INDICADORES] <> "POBLACIÓN CON INGRESO INFERIOR A LA LINEA DE POBREZA EXTREMA POR INGRESO PORCENTAJE 2010" and [INDICADORES] <> "POBLACIÓN CON INGRESO INFERIOR A LA LINEA DE POBREZA EXTREMA POR INGRESO PORCENTAJE 2015" and [INDICADORES] <> "POBLACIÓN CON INGRESO INFERIOR A LA LINEA DE POBREZA EXTREMA POR INGRESO PORCENTAJE 2020" and [INDICADORES] <> "POBLACIÓN CON TRES O MAS CARENCIAS SOCIALES PORCENTAJE 2010" and [INDICADORES] <> "POBLACIÓN CON TRES O MAS CARENCIAS SOCIALES PORCENTAJE 2015" and [INDICADORES] <> "POBLACIÓN CON TRES O MAS CARENCIAS SOCIALES PORCENTAJE 2020" and [INDICADORES] <> "POBLACIÓN CON UN INGRESO INFERIOR A LA LINEA DE POBREZA POR INGRESO PORCENTAJE 2010" and [INDICADORES] <> "POBLACIÓN CON UN INGRESO INFERIOR A LA LINEA DE POBREZA POR INGRESO PORCENTAJE 2015" and [INDICADORES] <> "POBLACIÓN CON UN INGRESO INFERIOR A LA LINEA DE POBREZA POR INGRESO PORCENTAJE 2020" and [INDICADORES] <> "POBREZA EXTREMA PORCENTAJE 2010" and [INDICADORES] <> "POBREZA EXTREMA PORCENTAJE 2015" and [INDICADORES] <> "POBREZA EXTREMA PORCENTAJE 2020" and [INDICADORES] <> "POBREZA MODERADA PORCENTAJE 2010" and [INDICADORES] <> "POBREZA MODERADA PORCENTAJE 2015" and [INDICADORES] <> "POBREZA MODERADA PORCENTAJE 2020" and [INDICADORES] <> "POBREZA PORCENTAJE 2010" and [INDICADORES] <> "POBREZA PORCENTAJE 2015" and [INDICADORES] <> "POBREZA PORCENTAJE 2020" and [INDICADORES] <> "REZAGO EDUCATIVO PORCENTAJE 2010" and [INDICADORES] <> "REZAGO EDUCATIVO PORCENTAJE 2015" and [INDICADORES] <> "REZAGO EDUCATIVO PORCENTAJE 2020" and [INDICADORES] <> "VULNERABLES POR CARENCIA SOCIAL PORCENTAJE 2010" and [INDICADORES] <> "VULNERABLES POR CARENCIA SOCIAL PORCENTAJE 2015" and [INDICADORES] <> "VULNERABLES POR CARENCIA SOCIAL PORCENTAJE 2020" and [INDICADORES] <> "VULNERABLES POR INGRESO PORCENTAJE 2010" and [INDICADORES] <> "VULNERABLES POR INGRESO PORCENTAJE 2015" and [INDICADORES] <> "VULNERABLES POR INGRESO PORCENTAJE 2020")),
				    #"Dividir columna por delimitador" = Table.SplitColumn(#"Filas filtradas1", "INDICADORES", Splitter.SplitTextByEachDelimiter({" "}, QuoteStyle.Csv, true), {"INDICADORES.1", "INDICADORES.2"}),
				    #"Tipo cambiado1" = Table.TransformColumnTypes(#"Dividir columna por delimitador",{{"INDICADORES.1", type text}, {"INDICADORES.2", Int64.Type}}),
				    #"Columna condicional agregada" = Table.AddColumn(#"Tipo cambiado1", "Personalizado", each if [INDICADORES.1] = "POBLACIÓN" then "POBLACIÓN" else if [INDICADORES.1] = "POBREZA PERSONAS" then "POBLACIÓN: NO POBRE, POBRE Y VULNERABLE" else if [INDICADORES.1] = "VULNERABLES POR CARENCIA SOCIAL PERSONAS" then "POBLACIÓN: NO POBRE, POBRE Y VULNERABLE" else if [INDICADORES.1] = "VULNERABLES POR INGRESO PERSONAS" then "POBLACIÓN: NO POBRE, POBRE Y VULNERABLE" else if [INDICADORES.1] = "NO POBRE Y NO VULNERABLE PERSONAS" then "POBLACIÓN: NO POBRE, POBRE Y VULNERABLE" else if [INDICADORES.1] = "CARENCIAS PROMEDIO" then "CARENCIAS PROMEDIO Y CARFENCIAS PROMEDIO POBREZA EXTREMA" else if [INDICADORES.1] = "POBREZA EXTREMA CARENCIAS PROMEDIO" then "CARENCIAS PROMEDIO Y CARFENCIAS PROMEDIO POBREZA EXTREMA" else if [INDICADORES.1] = "POBREZA EXTREMA PERSONAS" then "POBREZA MODERADA Y POBREZA EXTREMA" else if [INDICADORES.1] = "POBREZA MODERADA PERSONAS" then "POBREZA MODERADA Y POBREZA EXTREMA" else if [INDICADORES.1] = "POBLACIÓN CON AL MENOS UNA CARENCIA SOCIAL PERSONAS" then "POBLACIÓN CON AL MENOS UNA, TRES O MÁS CARENCIAS" else if [INDICADORES.1] = "POBLACIÓN CON TRES O MAS CARENCIAS SOCIALES PERSONAS" then "POBLACIÓN CON AL MENOS UNA, TRES O MÁS CARENCIAS" else if [INDICADORES.1] = "POBLACIÓN CON UN INGRESO INFERIOR A LA LINEA DE POBREZA POR INGRESO PERSONAS" then "LINEA DE POBREZA" else if [INDICADORES.1] = "POBLACIÓN CON INGRESO INFERIOR A LA LINEA DE POBREZA EXTREMA POR INGRESO PERSONAS" then "LINEA DE POBREZA" else "CARENCIAS"),
				    #"Columnas quitadas" = Table.RemoveColumns(#"Columna condicional agregada",{"INDICADORES.2"}),
				    #"Columnas reordenadas" = Table.ReorderColumns(#"Columnas quitadas",{"CVE_ENTIDAD", "ENTIDAD", "CVE_MUNICIPIO", "MUNICIPIO", "AÑO", "Personalizado", "INDICADORES.1", "VALOR"}),
				    #"Columnas con nombre cambiado" = Table.RenameColumns(#"Columnas reordenadas",{{"Personalizado", "TEMA"}}),
				    #"Tipo cambiado2" = Table.TransformColumnTypes(#"Columnas con nombre cambiado",{{"TEMA", type text}}),
				    #"Columnas con nombre cambiado1" = Table.RenameColumns(#"Tipo cambiado2",{{"INDICADORES.1", "SUBTEMA"}}),
				    #"Filas filtradas2" = Table.SelectRows(#"Columnas con nombre cambiado1", each true),
				    #"Valor reemplazado44" = Table.ReplaceValue(#"Filas filtradas2","CARENCIAS PROMEDIO Y CARFENCIAS PROMEDIO POBREZA EXTREMA","CARENCIAS PROMEDIO Y CARENCIAS PROMEDIO POBREZA EXTREMA",Replacer.ReplaceText,{"TEMA"}),
				    #"Columna Formateada" = Table.AddColumn(#"Valor reemplazado44", "VALOR Formateado", each if Value.Is([VALOR], type number) and [VALOR] <> Number.Round([VALOR], 0) then Number.Round([VALOR], 2) else [VALOR]),
				    #"Columnas quitadas1" = Table.RemoveColumns(#"Columna Formateada",{"VALOR"}),
				    #"Tipo cambiado3" = Table.TransformColumnTypes(#"Columnas quitadas1",{{"VALOR Formateado", type number}}),
				    #"Filas filtradas3" = Table.SelectRows(#"Tipo cambiado3", each true)
				in
				    #"Filas filtradas3"

	changedProperty = IsHidden

	annotation PBI_NavigationStepName = Navegación

	annotation PBI_ResultType = Table

