table POBREZA
	lineageTag: 005a63bc-8672-4e1e-a76c-5836d55a6279

	column CVE_ENTIDAD
		dataType: string
		lineageTag: 01aaa899-caca-41a8-9482-f0d6c9144cb4
		summarizeBy: none
		sourceColumn: CVE_ENTIDAD

		annotation SummarizationSetBy = Automatic

	column ENTIDAD
		dataType: string
		lineageTag: 1d84bb47-fc82-4967-b4bf-f75bf0499ea7
		summarizeBy: none
		sourceColumn: ENTIDAD

		annotation SummarizationSetBy = Automatic

	column CVE_MUNICIPIO
		dataType: string
		lineageTag: 76d6a22f-2860-422c-8e3d-c44932f8930f
		summarizeBy: none
		sourceColumn: CVE_MUNICIPIO

		annotation SummarizationSetBy = Automatic

	column MUNICIPIO
		dataType: string
		lineageTag: af1c5f43-5646-4b06-bfa7-50e60706de0e
		summarizeBy: none
		sourceColumn: MUNICIPIO

		annotation SummarizationSetBy = Automatic

	column AÑO
		dataType: string
		lineageTag: 4babf386-b330-4764-809c-762b7c6551bb
		summarizeBy: none
		sourceColumn: AÑO

		changedProperty = DataType

		annotation SummarizationSetBy = Automatic

	column INDICADORES
		dataType: string
		lineageTag: be93144e-a564-434a-8f9c-92948a292bf5
		summarizeBy: none
		sourceColumn: INDICADORES

		annotation SummarizationSetBy = Automatic

	column VALOR
		dataType: double
		lineageTag: 34e58fb5-747e-4776-bbe1-c27b92935ad4
		summarizeBy: sum
		sourceColumn: VALOR

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	partition POBREZA = m
		mode: import
		source =
				let
				    Origen = Table.Combine({#"Concentrado estatal", POBREZAMUNICIPAL}),
				    #"Tipo cambiado" = Table.TransformColumnTypes(Origen,{{"CVE_MUNICIPIO", type text}}),
				    #"Filas filtradas" = Table.SelectRows(#"Tipo cambiado", each true),
				    #"Valor reemplazado" = Table.ReplaceValue(#"Filas filtradas","Población 2010","POBLACIÓN 2010",Replacer.ReplaceText,{"INDICADORES"}),
				    #"Valor reemplazado1" = Table.ReplaceValue(#"Valor reemplazado","Población 2015","POBLACIÓN 2015",Replacer.ReplaceText,{"INDICADORES"}),
				    #"Valor reemplazado2" = Table.ReplaceValue(#"Valor reemplazado1","Población 2020","POBLACIÓN 2020",Replacer.ReplaceText,{"INDICADORES"}),
				    #"Valor reemplazado3" = Table.ReplaceValue(#"Valor reemplazado2","POBREZA EXTREMAS CARENCIAS PROMEDIO 2010","POBREZA EXTREMA CARENCIAS PROMEDIO 2010",Replacer.ReplaceText,{"INDICADORES"}),
				    #"Valor reemplazado4" = Table.ReplaceValue(#"Valor reemplazado3","CARENCIA POR CALIDAD Y ESPACIOS DE LA VIVIENDA  PERSONAS 2010","CARENCIAS POR CALIDAD Y ESPACIOS DE LA VIVIENDA  PERSONAS 2010",Replacer.ReplaceText,{"INDICADORES"}),
				    #"Valor reemplazado5" = Table.ReplaceValue(#"Valor reemplazado4","CARENCIA POR CALIDAD Y ESPACIOS DE LA VIVIENDA PORCENTAJE 2010","CARENCIAS POR CALIDAD Y ESPACIOS DE LA VIVIENDA PORCENTAJE 2010",Replacer.ReplaceText,{"INDICADORES"}),
				    #"Valor reemplazado6" = Table.ReplaceValue(#"Valor reemplazado5","CARENCIA POR CALIDAD Y ESPACIOS DE LA VIVIENDA PORCENTAJE 2015","CARENCIAS POR CALIDAD Y ESPACIOS DE LA VIVIENDA PORCENTAJE 2015",Replacer.ReplaceText,{"INDICADORES"}),
				    #"Valor reemplazado7" = Table.ReplaceValue(#"Valor reemplazado6","CARENCIA POR CALIDAD Y ESPACIOS DE LA VIVIENDA  PORCENTAJE 2010","CARENCIAS POR CALIDAD Y ESPACIOS DE LA VIVIENDA  PORCENTAJE 2010",Replacer.ReplaceText,{"INDICADORES"}),
				    #"Valor reemplazado8" = Table.ReplaceValue(#"Valor reemplazado7","CARENCIA POR CALIDAD Y ESPACIOS DE LA VIVIENDA  PORCENTAJE 2015","CARENCIAS POR CALIDAD Y ESPACIOS DE LA VIVIENDA  PORCENTAJE 2015",Replacer.ReplaceText,{"INDICADORES"}),
				    #"Valor reemplazado9" = Table.ReplaceValue(#"Valor reemplazado8","CARENCIA POR CALIDAD Y ESPACIOS DE LA VIVIENDA  PORCENTAJE 2020","CARENCIAS POR CALIDAD Y ESPACIOS DE LA VIVIENDA  PORCENTAJE 2020",Replacer.ReplaceText,{"INDICADORES"}),
				    #"Valor reemplazado10" = Table.ReplaceValue(#"Valor reemplazado9","CARENCIA POR CALIDAD Y ESPACIOS DE LA VIVIENDA  PERSONAS 2015","CARENCIAS POR CALIDAD Y ESPACIOS DE LA VIVIENDA  PERSONAS 2015",Replacer.ReplaceText,{"INDICADORES"}),
				    #"Valor reemplazado11" = Table.ReplaceValue(#"Valor reemplazado10","CARENCIA POR CALIDAD Y ESPACIOS DE LA VIVIENDA  PERSONAS 2020","CARENCIAS POR CALIDAD Y ESPACIOS DE LA VIVIENDA  PERSONAS 2020",Replacer.ReplaceText,{"INDICADORES"}),
				    #"Valor reemplazado12" = Table.ReplaceValue(#"Valor reemplazado11","CARENCIA POR ACCESO A LA ALIMENTACIÓN PORCENTAJE 2010","CARENCIAS POR ACCESO A LA ALIMENTACIÓN PORCENTAJE 2010",Replacer.ReplaceText,{"INDICADORES"}),
				    #"Valor reemplazado13" = Table.ReplaceValue(#"Valor reemplazado12","CARENCIA POR ACCESO A LA ALIMENTACIÓN PORCENTAJE 2015","CARENCIAS POR ACCESO A LA ALIMENTACIÓN PORCENTAJE 2015",Replacer.ReplaceText,{"INDICADORES"}),
				    #"Valor reemplazado14" = Table.ReplaceValue(#"Valor reemplazado13","CARENCIA POR ACCESO A LA ALIMENTACIÓN PORCENTAJE 2020","CARENCIAS POR ACCESO A LA ALIMENTACIÓN PORCENTAJE 2020",Replacer.ReplaceText,{"INDICADORES"}),
				    #"Valor reemplazado15" = Table.ReplaceValue(#"Valor reemplazado14","CARENCIA POR ACCESO A LA ALIMENTACIÓN PERSONAS 2015","CARENCIAS POR ACCESO A LA ALIMENTACIÓN PERSONAS 2015",Replacer.ReplaceText,{"INDICADORES"}),
				    #"Valor reemplazado16" = Table.ReplaceValue(#"Valor reemplazado15","CARENCIA POR ACCESO A LA ALIMENTACIÓN PERSONAS 2020","CARENCIAS POR ACCESO A LA ALIMENTACIÓN PERSONAS 2020",Replacer.ReplaceText,{"INDICADORES"}),
				    #"Valor reemplazado17" = Table.ReplaceValue(#"Valor reemplazado16","CARENCIA POR ACCESO A LA ALIMENTACIÓN PERSONAS 2010","CARENCIAS POR ACCESO A LA ALIMENTACIÓN PERSONAS 2010",Replacer.ReplaceText,{"INDICADORES"}),
				    #"Valor reemplazado18" = Table.ReplaceValue(#"Valor reemplazado17","CARENCIAS POR CALIDAD Y ESPACIOS DE LA VIVIENDA  PERSONAS 2010","CARENCIAS POR CALIDAD Y ESPACIOS DE LA VIVIENDA PERSONAS 2010",Replacer.ReplaceText,{"INDICADORES"}),
				    #"Valor reemplazado19" = Table.ReplaceValue(#"Valor reemplazado18","CARENCIAS POR CALIDAD Y ESPACIOS DE LA VIVIENDA  PORCENTAJE 2010","CARENCIAS POR CALIDAD Y ESPACIOS DE LA VIVIENDA PORCENTAJE 2010",Replacer.ReplaceText,{"INDICADORES"}),
				    #"Valor reemplazado20" = Table.ReplaceValue(#"Valor reemplazado19","CARENCIAS POR CALIDAD Y ESPACIOS DE LA VIVIENDA  PORCENTAJE 2015","CARENCIAS POR CALIDAD Y ESPACIOS DE LA VIVIENDA PORCENTAJE 2015",Replacer.ReplaceText,{"INDICADORES"}),
				    #"Valor reemplazado21" = Table.ReplaceValue(#"Valor reemplazado20","CARENCIAS POR CALIDAD Y ESPACIOS DE LA VIVIENDA  PORCENTAJE 2020","CARENCIAS POR CALIDAD Y ESPACIOS DE LA VIVIENDA PORCENTAJE 2020",Replacer.ReplaceText,{"INDICADORES"}),
				    #"Valor reemplazado22" = Table.ReplaceValue(#"Valor reemplazado21","CARENCIAS POR CALIDAD Y ESPACIOS DE LA VIVIENDA  PERSONAS 2015","CARENCIAS POR CALIDAD Y ESPACIOS DE LA VIVIENDA PERSONAS 2015",Replacer.ReplaceText,{"INDICADORES"}),
				    #"Valor reemplazado23" = Table.ReplaceValue(#"Valor reemplazado22","CARENCIAS POR CALIDAD Y ESPACIOS DE LA VIVIENDA  PERSONAS 2020","CARENCIAS POR CALIDAD Y ESPACIOS DE LA VIVIENDA PERSONAS 2020",Replacer.ReplaceText,{"INDICADORES"}),
				    #"Valor reemplazado24" = Table.ReplaceValue(#"Valor reemplazado23","POBLACIÓN CON INGRESO INFERIOS A LA lP EXTREMA POR INGRESO PORCENTAJE 2010","POBLACIÓN CON INGRESO INFERIOR A LA LINEA DE POBREZA EXTREMA POR INGRESO PORCENTAJE 2010",Replacer.ReplaceText,{"INDICADORES"}),
				    #"Valor reemplazado25" = Table.ReplaceValue(#"Valor reemplazado24","POBLACIÓN CON INGRESO INFERIOS A LA lP EXTREMA POR INGRESO PORCENTAJE 2015","POBLACIÓN CON INGRESO INFERIOR A LA LINEA DE POBREZA EXTREMA POR INGRESO PORCENTAJE 2015",Replacer.ReplaceText,{"INDICADORES"}),
				    #"Valor reemplazado26" = Table.ReplaceValue(#"Valor reemplazado25","POBLACIÓN CON INGRESO INFERIOS A LA lP EXTREMA POR INGRESO PORCENTAJE 2020","POBLACIÓN CON INGRESO INFERIOR A LA LINEA DE POBREZA EXTREMA POR INGRESO PORCENTAJE 2020",Replacer.ReplaceText,{"INDICADORES"}),
				    #"Valor reemplazado27" = Table.ReplaceValue(#"Valor reemplazado26","POBLACIÓN CON INGRESO INFERIOS A LA lP EXTREMA POR INGRESO PERSONAS 2010","POBLACIÓN CON INGRESO INFERIOR A LA LINEA DE POBREZA EXTREMA POR INGRESO PERSONAS 2010",Replacer.ReplaceText,{"INDICADORES"}),
				    #"Valor reemplazado28" = Table.ReplaceValue(#"Valor reemplazado27","POBLACIÓN CON INGRESO INFERIOS A LA lP EXTREMA POR INGRESO PERSONAS 2015","POBLACIÓN CON INGRESO INFERIOR A LA LINEA DE POBREZA EXTREMA POR INGRESO PERSONAS 2015",Replacer.ReplaceText,{"INDICADORES"}),
				    #"Valor reemplazado29" = Table.ReplaceValue(#"Valor reemplazado28","POBLACIÓN CON INGRESO INFERIOS A LA lP EXTREMA POR INGRESO PERSONAS 2020","POBLACIÓN CON INGRESO INFERIOR A LA LINEA DE POBREZA EXTREMA POR INGRESO PERSONAS 2020",Replacer.ReplaceText,{"INDICADORES"}),
				    #"Valor reemplazado30" = Table.ReplaceValue(#"Valor reemplazado29","POBLACIÓN CON UN INGRESO INFERIOR A LA LPI PORCENTAJE 2010","POBLACIÓN CON UN INGRESO INFERIOR A LA LINEA DE POBREZA POR INGRESO PORCENTAJE 2010",Replacer.ReplaceText,{"INDICADORES"}),
				    #"Valor reemplazado31" = Table.ReplaceValue(#"Valor reemplazado30","POBLACIÓN CON UN INGRESO INFERIOR A LA LPI PORCENTAJE 2015","POBLACIÓN CON UN INGRESO INFERIOR A LA LINEA DE POBREZA POR INGRESO PORCENTAJE 2015",Replacer.ReplaceText,{"INDICADORES"}),
				    #"Valor reemplazado32" = Table.ReplaceValue(#"Valor reemplazado31","POBLACIÓN CON UN INGRESO INFERIOR A LA LPI PORCENTAJE 2020","POBLACIÓN CON UN INGRESO INFERIOR A LA LINEA DE POBREZA POR INGRESO PORCENTAJE 2020",Replacer.ReplaceText,{"INDICADORES"}),
				    #"Valor reemplazado33" = Table.ReplaceValue(#"Valor reemplazado32","POBLACIÓN CON UN INGRESO INFERIOR A LA LPI PERSONAS 2010","POBLACIÓN CON UN INGRESO INFERIOR A LA LINEA DE POBREZA POR INGRESO PERSONAS 2010",Replacer.ReplaceText,{"INDICADORES"}),
				    #"Valor reemplazado34" = Table.ReplaceValue(#"Valor reemplazado33","POBLACIÓN CON UN INGRESO INFERIOR A LA LPI PERSONAS 2015","POBLACIÓN CON UN INGRESO INFERIOR A LA LINEA DE POBREZA POR INGRESO PERSONAS 2015",Replacer.ReplaceText,{"INDICADORES"}),
				    #"Valor reemplazado35" = Table.ReplaceValue(#"Valor reemplazado34","POBLACIÓN CON UN INGRESO INFERIOR A LA LPI PERSONAS 2020","POBLACIÓN CON UN INGRESO INFERIOR A LA LINEA DE POBREZA POR INGRESO PERSONAS 2020",Replacer.ReplaceText,{"INDICADORES"}),
				    #"Valor reemplazado36" = Table.ReplaceValue(#"Valor reemplazado35","VULNERABLES POR INGRESOS PORCENTAJE 2015","VULNERABLES POR INGRESO PORCENTAJE 2015",Replacer.ReplaceText,{"INDICADORES"}),
				    #"Valor reemplazado37" = Table.ReplaceValue(#"Valor reemplazado36","POBLACIÓN CON UN INGRESO INFERIOR A LA LPI 2010","POBLACIÓN CON UN INGRESO INFERIOR A LA LINEA DE POBREZA POR INGRESO PERSONAS 2010",Replacer.ReplaceText,{"INDICADORES"}),
				    #"Valor reemplazado38" = Table.ReplaceValue(#"Valor reemplazado37","POBLACIÓN CON UN INGRESO INFERIOR A LA LPI 2015","POBLACIÓN CON UN INGRESO INFERIOR A LA LINEA DE POBREZA POR INGRESO PERSONAS 2015",Replacer.ReplaceText,{"INDICADORES"}),
				    #"Valor reemplazado39" = Table.ReplaceValue(#"Valor reemplazado38","POBLACIÓN CON UN INGRESO INFERIOR A LA LPI 2020","POBLACIÓN CON UN INGRESO INFERIOR A LA LINEA DE POBREZA POR INGRESO PERSONAS 2020",Replacer.ReplaceText,{"INDICADORES"}),
				    #"Valor reemplazado40" = Table.ReplaceValue(#"Valor reemplazado39","POBLACIÓN CON INGRESO INFERIOS A LA lP EXTREMA POR INGRESO 2010","POBLACIÓN CON INGRESO INFERIOR A LA LINEA DE POBREZA EXTREMA POR INGRESO PERSONAS 2010",Replacer.ReplaceText,{"INDICADORES"}),
				    #"Valor reemplazado41" = Table.ReplaceValue(#"Valor reemplazado40","POBLACIÓN CON INGRESO INFERIOS A LA lP EXTREMA POR INGRESO 2015","POBLACIÓN CON INGRESO INFERIOR A LA LINEA DE POBREZA EXTREMA POR INGRESO PERSONAS 2015",Replacer.ReplaceText,{"INDICADORES"}),
				    #"Valor reemplazado42" = Table.ReplaceValue(#"Valor reemplazado41","POBLACIÓN CON INGRESO INFERIOS A LA lP EXTREMA POR INGRESO 2020","POBLACIÓN CON INGRESO INFERIOR A LA LINEA DE POBREZA EXTREMA POR INGRESO PERSONAS 2020",Replacer.ReplaceText,{"INDICADORES"}),
				    #"Valor reemplazado43" = Table.ReplaceValue(#"Valor reemplazado42","CARENCIAS POR ACCESO A LA SEGURIDAD SOCIAL PORCENTAJE  2015","CARENCIAS POR ACCESO A LA SEGURIDAD SOCIAL PORCENTAJE 2015",Replacer.ReplaceText,{"INDICADORES"})
				in
				    #"Valor reemplazado43"

	annotation PBI_NavigationStepName = Navegación

	annotation PBI_ResultType = Table

