table ESTADOS
	lineageTag: 94b08ce0-6b63-4381-9cc7-ad10a5f093fb

	column CVE_ENTIDAD
		dataType: string
		lineageTag: b27750de-fcf2-49fa-bd61-d6971a741a6f
		summarizeBy: none
		sourceColumn: CVE_ENTIDAD

		annotation SummarizationSetBy = Automatic

	column ENTIDAD
		dataType: string
		lineageTag: 67d37997-04fe-476c-9267-9fd9d5e1d34f
		dataCategory: StateOrProvince
		summarizeBy: none
		sourceColumn: ENTIDAD

		annotation SummarizationSetBy = Automatic

	partition ESTADOS = m
		mode: import
		source =
				let
				    Origen = Table.Combine({#"Concentrado estatal", POBREZAMUNICIPAL}),
				    #"Columnas quitadas" = Table.RemoveColumns(Origen,{"CVE_MUNICIPIO", "MUNICIPIO", "AÑO", "INDICADORES", "VALOR"}),
				    #"Duplicados quitados" = Table.Distinct(#"Columnas quitadas", {"CVE_ENTIDAD"})
				in
				    #"Duplicados quitados"

	annotation PBI_ResultType = Table

