table MEDIDAS
	lineageTag: 8ad03f2a-97de-4bdc-8a7a-de3fb9810344

	measure '% Cumplimiento Metas' =
			
			AVERAGEX(
			    FAIS,
			    DIVIDE([META_MODIFICADA_U], [APROBADO], 0)
			)
		lineageTag: 30e17e9f-69b6-4491-b97f-72c7414cfce0

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure PROYECTOS = COUNTROWS(FAIS)
		formatString: 0
		lineageTag: 0efd9e04-a5b9-4d78-a2d9-a190fedf89c2

	measure 'PORCENTAJE EJECUCIÓN' = DIVIDE(SUM(FAIS[EJERCIDO]), SUM(FAIS[APROBADO]), 0)
		formatString: 0.00\ %;-0.00\ %;0.00\ %
		lineageTag: 20c05881-ba85-4564-b5b6-a7b0d2fb9710

	measure 'Costo por proyectos' = SUM(FAIS[APROBADO])
		formatString: \$#,0.###############;-\$#,0.###############;\$#,0.###############
		lineageTag: 4ecbab4b-0007-4422-852b-ef9c1b46b900

		annotation PBI_FormatHint = {"currencyCulture":"es-MX"}

	measure 'Costo por Beneficiario' =
			
			DIVIDE(
			    [Costo por proyectos],
			    [Beneficiarios Hombres] + [Beneficiarios Mujeres],
			    0
			)
		lineageTag: 5f34b031-0b59-4fd1-b685-585649a4887a

	measure 'Beneficiarios Mujeres' = SUM(FAIS[MUJERES])
		formatString: 0
		lineageTag: fae4e5be-f099-4cce-bdce-a035d92b4ab2

	measure 'Beneficiarios Hombres' = SUM(FAIS[HOMBRES])
		formatString: 0
		lineageTag: 2379c9c7-6557-4471-aaa2-deb4987de141

	measure Beneficiarios = [Beneficiarios Mujeres]+[Beneficiarios Hombres]
		formatString: 0
		lineageTag: dc5c3e1b-7a26-4f20-8c86-8ae42fd05197

	measure '% Ejecución' = AVERAGE(FAIS[AVANCE])
		formatString: 0.00\ %;-0.00\ %;0.00\ %
		lineageTag: 170e909c-4d15-4677-bdc7-793820452af9

	measure Última_Actualización = FORMAT(NOW(), "DD/MM/YYYY HH:mm:ss")
		lineageTag: 000988d5-df80-40cb-8e15-961e3ce4f3fe

	partition MEDIDAS = m
		mode: import
		source =
				let
				    Source = Table.FromRows(Json.Document(Binary.Decompress(Binary.FromText("i44FAA==", BinaryEncoding.Base64), Compression.Deflate)), let _t = ((type nullable text) meta [Serialized.Text = true]) in type table [Columna1 = _t]),
				    #"Removed Columns" = Table.RemoveColumns(Source,{"Columna1"})
				in
				    #"Removed Columns"

	annotation PBI_ResultType = Table

