table INGRESOS
	lineageTag: 440606a2-c81a-48e7-bc16-4ca87e1d726a

	measure 'Ingresos Totales' =
			
			CALCULATE(
			    SUM('HECHO EGRESOS-INGRESOS'[VALOR]),
			    'HECHO EGRESOS-INGRESOS'[TEMA] = "Ingresos",
			    'HECHO EGRESOS-INGRESOS'[CATEGORIA] = "Tema",
			    'HECHO EGRESOS-INGRESOS'[DESCRIPCION_CATEGORIA] = "Total de ingresos"
			)
		formatString: 0
		lineageTag: 154c7763-c4d9-414d-aab1-3d9fa9aa7f4a

	measure TotalIngresosPorCapitulo = ```
			
			CALCULATE(
			    SUM('HECHO EGRESOS-INGRESOS'[VALOR]),
			    'HECHO EGRESOS-INGRESOS'[TEMA] = "Ingresos",
			    'HECHO EGRESOS-INGRESOS'[CATEGORIA] = "Capítulo"
			)
			
			```
		formatString: 0
		lineageTag: 1629e16c-a53a-4c93-9a93-55298ade420f

	measure TotalIngresosPorConcepto = ```
			
			CALCULATE(
			    SUM('HECHO EGRESOS-INGRESOS'[VALOR]),
			    'HECHO EGRESOS-INGRESOS'[TEMA] = "Ingresos",
			    'HECHO EGRESOS-INGRESOS'[CATEGORIA] = "Concepto"
			)
			
			```
		formatString: 0
		lineageTag: 7da5c0e0-0b2d-42c0-be46-39ec27fab092

	measure TotalIngresosPorPartidaGenerica = ```
			
			CALCULATE(
			    SUM('HECHO EGRESOS-INGRESOS'[VALOR]),
			    'HECHO EGRESOS-INGRESOS'[TEMA] = "Ingresos",
			    'HECHO EGRESOS-INGRESOS'[CATEGORIA] = "Partida Genérica"
			)
			
			```
		formatString: 0
		lineageTag: b58c4b0c-7550-4e21-b63b-2e97151c8b91

	measure TotalIngresosPorSubpartidaGenerica = ```
			
			CALCULATE(
			    SUM('HECHO EGRESOS-INGRESOS'[VALOR]),
			    'HECHO EGRESOS-INGRESOS'[TEMA] = "Ingresos",
			    'HECHO EGRESOS-INGRESOS'[CATEGORIA] = "Subpartida Genérica"
			)
			
			```
		formatString: 0
		lineageTag: 12fe7b41-a9e7-4b80-b84b-cd922ad86812

	measure 'Ingresos 2023' = ```
			
			CALCULATE(
			    SUM('HECHO EGRESOS-INGRESOS'[VALOR]),
			    'HECHO EGRESOS-INGRESOS'[TEMA] = "Ingresos",
			    'HECHO EGRESOS-INGRESOS'[CATEGORIA] = "Tema",
			    'HECHO EGRESOS-INGRESOS'[DESCRIPCION_CATEGORIA] = "Total de ingresos",
			    'HECHO EGRESOS-INGRESOS'[Año]= 2023
			)
			
			```
		formatString: \$#,0.###############;(\$#,0.###############);\$#,0.###############
		lineageTag: d99a2c15-783d-49f7-b3e6-63a1fc43d734

	measure 'Ingresos Año Anterior' = ```
			
			CALCULATE(
			    [Ingresos Totales],
			    PARALLELPERIOD('HECHO EGRESOS-INGRESOS'[Año], -1, YEAR)
			)
			
			```
		formatString: 0
		lineageTag: 3cdcd8a7-7994-4e48-b75c-fb54ba6fa11b

	measure 'Variación de Ingresos en %' = ```
			
			IF(
			    ISBLANK([Ingresos Año Anterior]),
			    BLANK(),
			    DIVIDE([Ingresos Totales] - [Ingresos Año Anterior], [Ingresos Año Anterior], 0)
			)
			
			```
		lineageTag: 7a21685e-79d9-4f9c-b74f-0926808ada03

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	partition INGRESOS = m
		mode: import
		source =
				let
				    Origen = Table.FromRows(Json.Document(Binary.Decompress(Binary.FromText("i44FAA==", BinaryEncoding.Base64), Compression.Deflate)), let _t = ((type nullable text) meta [Serialized.Text = true]) in type table [Columna1 = _t]),
				    #"Tipo cambiado" = Table.TransformColumnTypes(Origen,{{"Columna1", type text}}),
				    #"Columnas quitadas" = Table.RemoveColumns(#"Tipo cambiado",{"Columna1"})
				in
				    #"Columnas quitadas"

	annotation PBI_ResultType = Table

