table MEDIDAS
	lineageTag: 5c730d26-70a2-41f3-9d97-539e94e41896

	measure 'Ingreso inferior a la línea de pobreza por ingresos' = ```
			
			CALCULATE(
			    VALUES(Pobreza[Valor])*100,
			    Pobreza[Indicador] = "Población con ingreso inferior a la línea de pobreza por ingresos"
			)
			
			```
		lineageTag: 0b59870e-5d82-4145-bcdb-80b2d1b3c971

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure 'Ingreso inferior a la línea de pobreza extrema por ingresos' = ```
			
			CALCULATE(
			    VALUES(Pobreza[Valor])*100,
			    Pobreza[Indicador] = "Población con ingreso inferior a la línea de pobreza extrema por ingresos"
			)
			
			```
		lineageTag: 0aee6be1-fd64-46d2-88dd-f50ab7e3f374

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure 'Carencia por acceso a la alimentación nutritiva y de calidad' = ```
			
			CALCULATE(
			    VALUES(Pobreza[Valor])*1000,
			    Pobreza[Indicador] = "Carencia por acceso a la alimentación nutritiva y de calidad"
			)
			
			```
		lineageTag: 003cf92f-2816-491e-9c8b-4c49e61ec87a

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure 'Carencia por acceso a los servicios básicos en la vivienda' = ```
			
			CALCULATE(
			    VALUES(Pobreza[Valor])*1000,
			    Pobreza[Indicador] = "Carencia por acceso a los servicios básicos en la vivienda"
			)
			
			```
		lineageTag: 205bea66-bec8-4c05-9e69-1898cd5fe00d

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure 'Carencia por calidad y espacios de la vivienda' = ```
			
			CALCULATE(
			    VALUES(Pobreza[Valor])*1000,
			    Pobreza[Indicador] = "Carencia por calidad y espacios de la vivienda"
			)
			
			```
		lineageTag: bde19c08-d02c-48ae-befd-0ff3f7813bdd

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure 'Carencia por acceso a la seguridad social' = ```
			
			CALCULATE(
			    VALUES(Pobreza[Valor])*1000,
			    Pobreza[Indicador] = "Carencia por acceso a la seguridad social"
			)
			
			```
		lineageTag: dccb890a-4d37-4894-a64a-af486ee6c607

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure 'Carencia por acceso a los servicios de salud' = ```
			
			CALCULATE(
			    VALUES(Pobreza[Valor])*1000,
			    Pobreza[Indicador] = "Carencia por acceso a los servicios de salud"
			)
			
			```
		lineageTag: 2edf5560-cc83-421b-9aa6-ea000976a00a

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure 'Rezago educativo' = ```
			
			CALCULATE(
			    VALUES(Pobreza[Valor]),
			    Pobreza[Indicador] = "Rezago educativo"
			)
			
			```
		lineageTag: 006761be-2eb5-4297-aab1-a411ae5ad991

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure 'Población con al menos tres carencias sociales' = ```
			
			CALCULATE(
			    VALUES(Pobreza[Valor]),
			    Pobreza[Indicador] = "Población con al menos tres carencias sociales"
			)
			
			```
		lineageTag: a21989b8-0550-42ec-a251-2add3729cead

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure 'Población con al menos una carencia social' = ```
			
			CALCULATE(
			    VALUES(Pobreza[Valor]),
			    Pobreza[Indicador] = "Población con al menos una carencia social"
			)
			
			```
		lineageTag: 728b62fc-e56a-4f2f-83b6-7217b42c2541

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure 'No pobre y no vulnerable' = ```
			
			CALCULATE(
			    VALUES(Pobreza[Valor])*1000,
			    Pobreza[Indicador] = "Población no pobre y no vulnerable"
			)
			
			```
		lineageTag: f77caca8-89f0-4c98-b944-d50f46d0aa01

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure 'Vulnerable por ingresos' = ```
			
			CALCULATE(
			    VALUES(Pobreza[Valor])*1000,
			    Pobreza[Indicador] = "Población vulnerable por ingresos"
			)
			
			```
		lineageTag: 951b3e1e-3123-4a76-b611-4368da20e41d

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure 'Vulnerable por carencias sociales' = ```
			
			CALCULATE(
			    VALUES(Pobreza[Valor])*1000,
			    Pobreza[Indicador] = "Población vulnerable por carencias sociales"
			)
			
			```
		lineageTag: 95d8af7d-dfeb-465e-8ece-cb7c864ff6f0

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure 'Población en situación de pobreza extrema' = ```
			
			CALCULATE(
			    VALUES(Pobreza[Valor])*1000,
			    Pobreza[Indicador] = "Población en situación de pobreza extrema"
			)
			
			```
		lineageTag: f8903065-b9fd-4c5c-9536-b64a6f4fa6ea

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure 'Población en situación de pobreza moderada' = ```
			
			CALCULATE(
			    VALUES(Pobreza[Valor])*100,
			    Pobreza[Indicador] = "Población en situación de pobreza moderada"
			)
			
			```
		lineageTag: 17abd7c4-0188-440b-9480-83698c5a4cff

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure 'En pobreza' = ```
			
			CALCULATE(
			    VALUES(Pobreza[Valor])*1000,
			    Pobreza[Indicador] = "Población en situación de pobreza"
			)
			
			```
		lineageTag: 17d8ab4c-8d65-499b-bd9c-9aa20d2a0593

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	partition MEDIDAS = m
		mode: import
		source =
				let
				    Origen = Table.FromRows(Json.Document(Binary.Decompress(Binary.FromText("i44FAA==", BinaryEncoding.Base64), Compression.Deflate)), let _t = ((type nullable text) meta [Serialized.Text = true]) in type table [Columna1 = _t]),
				    #"Tipo cambiado" = Table.TransformColumnTypes(Origen,{{"Columna1", type text}}),
				    #"Columnas quitadas" = Table.RemoveColumns(#"Tipo cambiado",{"Columna1"})
				in
				    #"Columnas quitadas"

	annotation PBI_ResultType = Table

