table TÍTULOS
	lineageTag: 978f4ee4-e73a-4d7e-b3e6-162838ca8a16

	measure 'Título Dinámico' = ```
			
			VAR EstadoSeleccionado = SELECTEDVALUE(Estados[NOM_ENTIDAD])
			RETURN
			SWITCH(
			    EstadoSeleccionado,
			    "Ciudad de México", "Población no pobre y no vulnerable, en vulnerabilidad y en pobreza en la Ciudad de México",
			    "Estados Unidos Mexicanos", "Población no pobre y no vulnerable, en vulnerabilidad y en pobreza en Estados Unidos Mexicanos",
			    "Población no pobre y no vulnerable, en vulnerabilidad y en pobreza en el estado de " & EstadoSeleccionado
			)
			
			```
		lineageTag: 85fdb715-ec4e-42f7-806f-f3cb17ca656e

	measure 'Título Dinámico Pobreza Extrema y Moderada' = ```
			
			VAR EstadoSeleccionado = SELECTEDVALUE(Estados[NOM_ENTIDAD])
			RETURN
			SWITCH(
			    EstadoSeleccionado,
			    "Ciudad de México", "Población en pobreza extrema y moderada en la Ciudad de México",
			    "Estados Unidos Mexicanos", "Población en pobreza extrema y moderada en Estados Unidos Mexicanos",
			    "Población en pobreza extrema y moderada en el estado de " & EstadoSeleccionado
			)
			
			```
		lineageTag: 9c93d062-5822-4205-bbf2-9954613d1827

	measure 'Título Dinámico Pobreza Extrema y por Ingreso' = ```
			
			VAR EstadoSeleccionado = SELECTEDVALUE(Estados[NOM_ENTIDAD])
			RETURN
			SWITCH(
			    EstadoSeleccionado,
			    "Ciudad de México", "Población con un ingreso inferior a la Línea de Pobreza Extrema y por Ingreso en la Ciudad de México",
			    "Estados Unidos Mexicanos", "Población con un ingreso inferior a la Línea de Pobreza Extrema y por Ingreso en Estados Unidos Mexicanos",
			    "Población con un ingreso inferior a la Línea de Pobreza Extrema y por Ingreso en el estado de " & EstadoSeleccionado
			)
			
			```
		lineageTag: a74e8a82-67f1-4318-b67d-cd54524dd774

	measure 'Título Dinámico Carencias Sociales' = ```
			
			VAR EstadoSeleccionado = SELECTEDVALUE(Estados[NOM_ENTIDAD])
			RETURN
			SWITCH(
			    EstadoSeleccionado,
			    "Ciudad de México", "Población en Carencias Sociales en la Ciudad de México",
			    "Estados Unidos Mexicanos", "Población en Carencias Sociales en Estados Unidos Mexicanos",
			    "Población en Carencias Sociales en el estado de " & EstadoSeleccionado
			)
			
			```
		lineageTag: f10dcd99-7102-4ee7-a23d-c5889ab82345

	partition TÍTULOS = m
		mode: import
		source =
				let
				    Origen = Table.FromRows(Json.Document(Binary.Decompress(Binary.FromText("i44FAA==", BinaryEncoding.Base64), Compression.Deflate)), let _t = ((type nullable text) meta [Serialized.Text = true]) in type table [Columna1 = _t]),
				    #"Tipo cambiado" = Table.TransformColumnTypes(Origen,{{"Columna1", type text}}),
				    #"Columnas quitadas" = Table.RemoveColumns(#"Tipo cambiado",{"Columna1"})
				in
				    #"Columnas quitadas"

	annotation PBI_ResultType = Table

