table DimMunicipio
	lineageTag: 5facc96f-1574-419c-9e78-710e37a38551

	column MunicipioID
		dataType: string
		lineageTag: 52478660-2e59-4778-9013-ec06699eb687
		summarizeBy: none
		sourceColumn: MunicipioID

		annotation SummarizationSetBy = Automatic

	column Municipio
		dataType: string
		lineageTag: d0586c13-8687-4849-ac4f-b3cac91efd59
		summarizeBy: none
		sourceColumn: Municipio

		annotation SummarizationSetBy = Automatic

	column EstadoID
		dataType: string
		lineageTag: de57cbc5-3cdb-4445-9d4e-25e88e5d5e59
		summarizeBy: none
		sourceColumn: EstadoID

		annotation SummarizationSetBy = Automatic

	column MunicipioCompuestoID
		dataType: string
		lineageTag: 938fecc5-0e31-4753-a517-294b0b1b787a
		summarizeBy: none
		sourceColumn: MunicipioCompuestoID

		annotation SummarizationSetBy = Automatic

	partition DimMunicipio = m
		mode: import
		source =
				let
				    Source = Csv.Document(File.Contents("C:\\Users\\hello\\OneDrive - JHRJDATA\\JHRJDATA\\Bases\\InegiArchivos\\CensoHechos.csv"), [Delimiter=",", Columns=9, Encoding=65001, QuoteStyle=QuoteStyle.None]),
				    PromotedHeaders = Table.PromoteHeaders(Source, [PromoteAllScalars=true]),
				    DimMunicipio = Table.Distinct(Table.SelectColumns(PromotedHeaders, {"cve_municipio", "desc_municipio", "cve_entidad"})),
				    RenameColumns = Table.RenameColumns(DimMunicipio,{{"cve_municipio", "MunicipioID"}, {"desc_municipio", "MunicipioNombre"}, {"cve_entidad", "EstadoID"}}),
				    AddCompositeID = Table.AddColumn(RenameColumns, "MunicipioCompuestoID", each Text.From([EstadoID]) & "-" & Text.PadStart(Text.From([MunicipioID]), 5, "0"), type text),
				    #"Columnas reordenadas" = Table.ReorderColumns(AddCompositeID,{"MunicipioCompuestoID", "MunicipioID", "MunicipioNombre", "EstadoID"}),
				    #"Columnas con nombre cambiado" = Table.RenameColumns(#"Columnas reordenadas",{{"MunicipioNombre", "Municipio"}})
				in
				    #"Columnas con nombre cambiado"

	annotation PBI_NavigationStepName = Navegación

	annotation PBI_ResultType = Table

