table Vivienda
	lineageTag: ba8b3a8f-8b8b-4db1-b970-847184c6cc39

	measure 'Total Viviendas Habitadas' = ```
			
			CALCULATE(
			    SUM(CensoHechos[Valor]),
			    CensoHechos[id_indicador] = 1003000001
			)
			
			```
		lineageTag: ec4aa1a5-d2b4-4922-99e6-6581b6a91d65

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure '% Viviendas Piso Tierra_2020' = ```
			
			CALCULATE(
			    SUM(CensoHechos[Valor]),
			    CensoHechos[id_indicador] = 3114004001,
			    CensoHechos[Año] = 2020
			)
			
			```
		lineageTag: e4b3af09-9253-4e2f-997b-18819d31659e

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure '% Viviendas Techos Resistentes_2020' = ```
			
			CALCULATE(
			    SUM(CensoHechos[Valor]),
			    CensoHechos[id_indicador] = 6200108938,
			    CensoHechos[Año] = 2020
			)
			
			```
		lineageTag: 395b8e9b-b24f-4879-a2be-3f79b21f3883

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure 'Tasa Crecimiento Viviendas_2020' = ```
			
			CALCULATE(
			    SUM(CensoHechos[Valor]),
			    CensoHechos[id_indicador] = 6200240389
			)
			
			```
		lineageTag: 20692188-5c32-4b2b-bb00-c954d573345e

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure 'Promedio Ocupantes Cuarto' = ```
			
			CALCULATE(
			    SUM(CensoHechos[Valor]),
			    CensoHechos[id_indicador] = 6207020035
			)
			
			```
		lineageTag: eeed04bf-08ad-4c81-8e4b-fde884699e8b

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure 'Promedio Ocupantes Dormitorio_2020' = ```
			
			CALCULATE(
			    SUM(CensoHechos[Valor]),
			    CensoHechos[id_indicador] = 6207129630,
			    CensoHechos[Año] = 2020
			)
			
			```
		lineageTag: 0ee29372-dcbb-4f74-bb51-9b509d5f1bdc

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	partition Vivienda = m
		mode: import
		source =
				let
				    Origen = Table.FromRows(Json.Document(Binary.Decompress(Binary.FromText("i44FAA==", BinaryEncoding.Base64), Compression.Deflate)), let _t = ((type nullable text) meta [Serialized.Text = true]) in type table [Columna1 = _t]),
				    #"Tipo cambiado" = Table.TransformColumnTypes(Origen,{{"Columna1", type text}}),
				    #"Columnas quitadas" = Table.RemoveColumns(#"Tipo cambiado",{"Columna1"})
				in
				    #"Columnas quitadas"

	annotation PBI_ResultType = Table

