table censo_ageb_2020_nacional_coordenadas
	lineageTag: 6efa2781-bef0-4a7c-9803-427e78e914fb

	measure 'Indice Habitabilidad' = ```
			
			VAR ServiciosBasicos = [Indice Servicios Basicos]
			VAR ConectividadDigital = [Indice Digital]
			RETURN
			IF(
			    NOT ISBLANK(ServiciosBasicos) && NOT ISBLANK(ConectividadDigital),
			    (ServiciosBasicos * 0.6 + ConectividadDigital * 0.4),
			    BLANK()
			)
			
			
			```
		lineageTag: 3a30c9dd-4988-45dc-ac81-133f1598e107

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure 'Acceso Servicios Integral' = ```
			
			VAR VulnerabilidadInv = 100 - [Indice Vulnerabilidad Social] * 10  // Convertir a 0-100
			VAR EducativoNorm = [Indice Educativo]
			RETURN
			IF(
			    NOT ISBLANK(VulnerabilidadInv) && NOT ISBLANK(EducativoNorm),
			    (VulnerabilidadInv * 0.5 + EducativoNorm * 0.5),
			    BLANK()
			)
			
			
			```
		lineageTag: bbfb8eb9-4bea-4356-9620-c7d87c03ed57

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure 'Potencial Economico Integral' = ```
			
			VAR PotencialMercado = [Indice Potencial Mercado]
			VAR DinamLaboral = [Indice Dinamismo Laboral]
			RETURN
			IF(
			    NOT ISBLANK(PotencialMercado) && NOT ISBLANK(DinamLaboral),
			    (PotencialMercado * 0.5 + DinamLaboral * 0.5),
			    BLANK()
			)
			
			
			```
		lineageTag: 0b956b7d-7be7-4a7d-b26f-c74ee094c346

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure 'Bienestar Social Compuesto' = ```
			
			VAR AccesoServicios = [Acceso Servicios Integral]
			VAR Habitabilidad = [Indice Habitabilidad]
			RETURN
			IF(
			    NOT ISBLANK(AccesoServicios) && NOT ISBLANK(Habitabilidad),
			    (AccesoServicios * 0.6 + Habitabilidad * 0.4),
			    BLANK()
			)
			
			
			```
		lineageTag: 5b89ca02-ff58-4db9-8473-645e0b929eb9

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure 'Indice Calidad Vida Urbana' = ```
			
			VAR Habitabilidad = [Indice Habitabilidad]
			VAR AccesoServicios = [Acceso Servicios Integral] 
			VAR PotencialEconomico = [Potencial Economico Integral]
			RETURN
			IF(
			    NOT ISBLANK(Habitabilidad) && NOT ISBLANK(AccesoServicios) && NOT ISBLANK(PotencialEconomico),
			    (Habitabilidad * 0.4 + AccesoServicios * 0.35 + PotencialEconomico * 0.25),
			    BLANK()
			)
			
			
			```
		lineageTag: 0d2f56ce-eb25-4004-ab32-45524c4a4f90

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure 'Clasificacion Calidad Vida' = ```
			
			VAR IndiceCV = [Indice Calidad Vida Urbana]
			RETURN
			IF(
			    NOT ISBLANK(IndiceCV),
			    SWITCH(
			        TRUE(),
			        IndiceCV >= 90, "🌟 EXCELENTE",
			        IndiceCV >= 80, "✅ MUY BUENA", 
			        IndiceCV >= 70, "⭐ BUENA",
			        IndiceCV >= 60, "⚠️ REGULAR",
			        "📉 DEFICIENTE"
			    ),
			    "📊 SIN DATOS"
			)
			
			
			```
		lineageTag: cf5c9fe3-2b7e-48a6-98df-e32bde762b34

	measure 'Ranking Calidad Vida' = ```
			
			RANKX(
			    ALL(censo_ageb_2020_nacional_coordenadas[CVE_AGEB]),
			    [Indice Calidad Vida Urbana],
			    ,
			    DESC
			)
			
			
			```
		formatString: 0
		lineageTag: 4fe3b215-c72e-420a-abd0-86dfa795f498

	measure 'Componente Economico IDT' = ```
			
			VAR PotencialMercado = [Indice Potencial Mercado]
			VAR DinamLaboral = [Indice Dinamismo Laboral]
			RETURN
			IF(
			    NOT ISBLANK(PotencialMercado) && NOT ISBLANK(DinamLaboral),
			    (PotencialMercado * 0.6 + DinamLaboral * 0.4),
			    BLANK()
			)
			
			
			```
		lineageTag: d910eb9d-acbf-4bc6-9401-fc18b60f3cc2

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure 'Componente Social IDT' = ```
			
			VAR EducativoNorm = [Indice Educativo]
			VAR VulnerabilidadInv = 100 - ([Indice Vulnerabilidad Social] * 10)  // Invertir y normalizar
			RETURN
			IF(
			    NOT ISBLANK(EducativoNorm) && NOT ISBLANK(VulnerabilidadInv),
			    (EducativoNorm * 0.6 + VulnerabilidadInv * 0.4),
			    BLANK()
			)
			
			
			```
		lineageTag: b1355bc8-72d4-4b61-a7a2-694957512a19

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure 'Componente Infraestructura IDT' = ```
			
			VAR ServiciosBasicos = [Indice Servicios Basicos]
			VAR ConectividadDigital = [Indice Digital]
			RETURN
			IF(
			    NOT ISBLANK(ServiciosBasicos) && NOT ISBLANK(ConectividadDigital),
			    (ServiciosBasicos * 0.6 + ConectividadDigital * 0.4),
			    BLANK()
			)
			
			
			```
		lineageTag: 076ed3dc-d8b0-4e4a-b440-fd1d2ce3ff1e

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure 'Componente Territorial IDT' = ```
			
			VAR CalidadVida = [Indice Calidad Vida Urbana]
			VAR Habitabilidad = [Indice Habitabilidad]
			RETURN
			IF(
			    NOT ISBLANK(CalidadVida) && NOT ISBLANK(Habitabilidad),
			    (CalidadVida * 0.7 + Habitabilidad * 0.3),
			    BLANK()
			)
			
			
			```
		lineageTag: f7b09911-a5eb-46bb-b11e-9ad1ef8c8a96

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure 'IDT Global' = ```
			
			VAR CompEconomico = [Componente Economico IDT]
			VAR CompSocial = [Componente Social IDT]
			VAR CompInfraestructura = [Componente Infraestructura IDT]
			VAR CompTerritorial = [Componente Territorial IDT]
			RETURN
			IF(
			    NOT ISBLANK(CompEconomico) && NOT ISBLANK(CompSocial) && 
			    NOT ISBLANK(CompInfraestructura) && NOT ISBLANK(CompTerritorial),
			    (CompEconomico * 0.30 + CompSocial * 0.30 + CompInfraestructura * 0.25 + CompTerritorial * 0.15),
			    BLANK()
			)
			
			
			```
		lineageTag: e4759311-9a2c-4203-94ee-6c5ddb2ae383

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure 'Clasificacion IDT' = ```
			
			VAR IDT = [IDT Global]
			RETURN
			IF(
			    NOT ISBLANK(IDT),
			    SWITCH(
			        TRUE(),
			        IDT >= 85, "🌟 DESARROLLO ALTO",
			        IDT >= 70, "✅ DESARROLLO BUENO",
			        IDT >= 55, "⚠️ DESARROLLO MEDIO",
			        IDT >= 40, "📉 DESARROLLO BAJO",
			        "🚨 DESARROLLO CRÍTICO"
			    ),
			    "📊 SIN DATOS"
			)
			
			
			```
		lineageTag: ea84ff93-2454-4d11-aba0-6827ae819e16

	measure 'Ranking Nacional IDT' = ```
			
			RANKX(
			    ALL(censo_ageb_2020_nacional_coordenadas[CVE_AGEB]),
			    [IDT Global],
			    ,
			    DESC
			)
			
			
			```
		formatString: 0
		lineageTag: 4bc783a7-6a54-4c68-ad09-7e913404eb4c

	measure 'Percentil IDT' = ```
			
			VAR IDTActual = [IDT Global]
			VAR TotalAGEBs = COUNTROWS(ALL(censo_ageb_2020_nacional_coordenadas[CVE_AGEB]))
			VAR AGEBsMenores = COUNTROWS(
			    FILTER(
			        ALL(censo_ageb_2020_nacional_coordenadas[CVE_AGEB]),
			        CALCULATE([IDT Global]) < IDTActual
			    )
			)
			RETURN
			IF(
			    NOT ISBLANK(IDTActual),
			    DIVIDE(AGEBsMenores, TotalAGEBs, 0) * 100,
			    BLANK()
			)
			
			
			```
		lineageTag: 05b0489c-5cc3-4de9-b9bb-cc61d56b1418

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure 'Cuadrante Desarrollo' = ```
			
			VAR CompEcon = [Componente Economico IDT]
			VAR CompSocial = [Componente Social IDT]
			VAR MediaEcon = 75  // Umbral medio
			VAR MediaSocial = 75  // Umbral medio
			RETURN
			IF(
			    NOT ISBLANK(CompEcon) && NOT ISBLANK(CompSocial),
			    SWITCH(
			        TRUE(),
			        CompEcon >= MediaEcon && CompSocial >= MediaSocial, "🚀 ALTO-ALTO",
			        CompEcon >= MediaEcon && CompSocial < MediaSocial, "💰 ALTO-BAJO",
			        CompEcon < MediaEcon && CompSocial >= MediaSocial, "🎓 BAJO-ALTO",
			        "⚠️ BAJO-BAJO"
			    ),
			    "📊 SIN DATOS"
			)
			
			
			```
		lineageTag: 80b5f7d5-92ef-4412-b0f0-b59bc137ce97

	measure 'Brecha Desarrollo' = ```
			
			VAR IDTActual = [IDT Global]
			VAR IDTMaximo = MAXX(ALL(censo_ageb_2020_nacional_coordenadas[CVE_AGEB]), CALCULATE([IDT Global]))
			RETURN
			IF(
			    NOT ISBLANK(IDTActual) && NOT ISBLANK(IDTMaximo),
			    IDTMaximo - IDTActual,
			    BLANK()
			)
			
			
			```
		lineageTag: ff2f4617-3d6e-4439-97d1-ec7d39c2057c

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column CVE_ENT
		dataType: string
		lineageTag: 90ab61ba-8851-40ca-82c0-d1c5e79adc25
		summarizeBy: none
		sourceColumn: CVE_ENT

		annotation SummarizationSetBy = Automatic

	column CVE_MUN
		dataType: string
		lineageTag: 62f88114-2b71-4776-9193-132a33388a97
		summarizeBy: none
		sourceColumn: CVE_MUN

		annotation SummarizationSetBy = Automatic

	column CVE_LOC
		dataType: string
		lineageTag: a58f1519-0b7a-4f6d-8482-0b98b0050725
		summarizeBy: none
		sourceColumn: CVE_LOC

		annotation SummarizationSetBy = Automatic

	column ENTIDAD
		dataType: string
		lineageTag: 05209ef9-221d-4329-a209-8476fa0e18b8
		summarizeBy: none
		sourceColumn: ENTIDAD

		annotation SummarizationSetBy = Automatic

	column NOM_ENT
		dataType: string
		lineageTag: c6ec4dcd-acae-4bfb-af23-d706f6032343
		summarizeBy: none
		sourceColumn: NOM_ENT

		annotation SummarizationSetBy = Automatic

	column MUN
		dataType: string
		lineageTag: 893751ad-6930-4517-901d-697a04b4954a
		summarizeBy: none
		sourceColumn: MUN

		annotation SummarizationSetBy = Automatic

	column NOM_MUN
		dataType: string
		lineageTag: 2a484b57-3c15-4182-81c1-addc42134010
		summarizeBy: none
		sourceColumn: NOM_MUN

		annotation SummarizationSetBy = Automatic

	column LOC
		dataType: string
		lineageTag: 2a314dac-35e2-4a5e-af35-3e637219883f
		summarizeBy: none
		sourceColumn: LOC

		annotation SummarizationSetBy = Automatic

	column NOM_LOC
		dataType: string
		lineageTag: 709e2c12-0554-4c4d-b452-777f5be506f4
		summarizeBy: none
		sourceColumn: NOM_LOC

		annotation SummarizationSetBy = Automatic

	column AGEB
		dataType: string
		lineageTag: b12da5d0-5038-424e-9851-594e52a49de7
		summarizeBy: none
		sourceColumn: AGEB

		annotation SummarizationSetBy = Automatic

	column MZA
		dataType: string
		lineageTag: b1373dc8-eb7e-4d0f-bc0b-586ccff432be
		summarizeBy: none
		sourceColumn: MZA

		annotation SummarizationSetBy = Automatic

	column POBTOT
		dataType: int64
		formatString: 0
		lineageTag: 1aa93436-1453-450c-9dc6-ee688e5f2f1d
		summarizeBy: sum
		sourceColumn: POBTOT

		annotation SummarizationSetBy = Automatic

	column POBFEM
		dataType: int64
		formatString: 0
		lineageTag: d0772957-f7f9-4f84-830b-e0d93f3a6926
		summarizeBy: sum
		sourceColumn: POBFEM

		annotation SummarizationSetBy = Automatic

	column POBMAS
		dataType: int64
		formatString: 0
		lineageTag: 6681f92a-2f2a-43b8-afb3-71a308e49ee5
		summarizeBy: sum
		sourceColumn: POBMAS

		annotation SummarizationSetBy = Automatic

	column P_0A2
		dataType: int64
		formatString: 0
		lineageTag: b55c00cf-6909-49bc-887f-b14ef2b900d1
		summarizeBy: sum
		sourceColumn: P_0A2

		annotation SummarizationSetBy = Automatic

	column P_0A2_F
		dataType: int64
		formatString: 0
		lineageTag: 690bc59d-b3ec-46d7-a831-fd114cb87ebb
		summarizeBy: sum
		sourceColumn: P_0A2_F

		annotation SummarizationSetBy = Automatic

	column P_0A2_M
		dataType: int64
		formatString: 0
		lineageTag: 41c57f16-408f-44c0-a4ed-cd146b483e5e
		summarizeBy: sum
		sourceColumn: P_0A2_M

		annotation SummarizationSetBy = Automatic

	column P_3YMAS
		dataType: int64
		formatString: 0
		lineageTag: 2e78517c-ab80-4cd3-a02d-bce1d9774af7
		summarizeBy: sum
		sourceColumn: P_3YMAS

		annotation SummarizationSetBy = Automatic

	column P_3YMAS_F
		dataType: int64
		formatString: 0
		lineageTag: d35b820c-b1c6-4239-b953-705e5d4f5a3c
		summarizeBy: sum
		sourceColumn: P_3YMAS_F

		annotation SummarizationSetBy = Automatic

	column P_3YMAS_M
		dataType: int64
		formatString: 0
		lineageTag: 1a8400c7-6624-4ba3-9446-340cf85f7e94
		summarizeBy: sum
		sourceColumn: P_3YMAS_M

		annotation SummarizationSetBy = Automatic

	column P_5YMAS
		dataType: int64
		formatString: 0
		lineageTag: 198e714f-3954-4426-8db6-d7a0b288c5de
		summarizeBy: sum
		sourceColumn: P_5YMAS

		annotation SummarizationSetBy = Automatic

	column P_5YMAS_F
		dataType: int64
		formatString: 0
		lineageTag: ca5ad350-7f73-408d-a6e8-6c4246ceba6e
		summarizeBy: sum
		sourceColumn: P_5YMAS_F

		annotation SummarizationSetBy = Automatic

	column P_5YMAS_M
		dataType: int64
		formatString: 0
		lineageTag: ad61f381-22f5-426a-a14a-88f273991271
		summarizeBy: sum
		sourceColumn: P_5YMAS_M

		annotation SummarizationSetBy = Automatic

	column P_12YMAS
		dataType: int64
		formatString: 0
		lineageTag: 2b996f3e-7664-43c3-9add-a47335ec97ed
		summarizeBy: sum
		sourceColumn: P_12YMAS

		annotation SummarizationSetBy = Automatic

	column P_12YMAS_F
		dataType: int64
		formatString: 0
		lineageTag: 80de6c85-dc40-472c-819a-cee6d43c1565
		summarizeBy: sum
		sourceColumn: P_12YMAS_F

		annotation SummarizationSetBy = Automatic

	column P_12YMAS_M
		dataType: int64
		formatString: 0
		lineageTag: 702253f1-0007-494f-85dd-bd6bd554988e
		summarizeBy: sum
		sourceColumn: P_12YMAS_M

		annotation SummarizationSetBy = Automatic

	column P_15YMAS
		dataType: int64
		formatString: 0
		lineageTag: b40db088-bd5c-4b31-a2c5-831aa65910cb
		summarizeBy: sum
		sourceColumn: P_15YMAS

		annotation SummarizationSetBy = Automatic

	column P_15YMAS_F
		dataType: int64
		formatString: 0
		lineageTag: 95f4510e-cda9-49dd-b93b-884f00636eba
		summarizeBy: sum
		sourceColumn: P_15YMAS_F

		annotation SummarizationSetBy = Automatic

	column P_15YMAS_M
		dataType: int64
		formatString: 0
		lineageTag: 7b6796cc-973d-4b46-8b7a-bcfa31f0da89
		summarizeBy: sum
		sourceColumn: P_15YMAS_M

		annotation SummarizationSetBy = Automatic

	column P_18YMAS
		dataType: int64
		formatString: 0
		lineageTag: ed1cc307-564a-45fc-9655-1f7d5750913b
		summarizeBy: sum
		sourceColumn: P_18YMAS

		annotation SummarizationSetBy = Automatic

	column P_18YMAS_F
		dataType: int64
		formatString: 0
		lineageTag: 1dcec725-5086-49c1-93ce-8ff234c4fd43
		summarizeBy: sum
		sourceColumn: P_18YMAS_F

		annotation SummarizationSetBy = Automatic

	column P_18YMAS_M
		dataType: int64
		formatString: 0
		lineageTag: 0ecf1091-8e1a-4ec1-8175-98a3ec8359d7
		summarizeBy: sum
		sourceColumn: P_18YMAS_M

		annotation SummarizationSetBy = Automatic

	column P_3A5
		dataType: int64
		formatString: 0
		lineageTag: eb5b6d66-edc8-4848-b9ff-f89dc171eb5c
		summarizeBy: sum
		sourceColumn: P_3A5

		annotation SummarizationSetBy = Automatic

	column P_3A5_F
		dataType: int64
		formatString: 0
		lineageTag: 7c7b1742-78ae-43ae-b82e-eab54070d1c3
		summarizeBy: sum
		sourceColumn: P_3A5_F

		annotation SummarizationSetBy = Automatic

	column P_3A5_M
		dataType: int64
		formatString: 0
		lineageTag: 78c79614-2f70-4881-852f-d9e529bc26db
		summarizeBy: sum
		sourceColumn: P_3A5_M

		annotation SummarizationSetBy = Automatic

	column P_6A11
		dataType: int64
		formatString: 0
		lineageTag: cdd32d49-275e-4d36-88df-7e3640b4e135
		summarizeBy: sum
		sourceColumn: P_6A11

		annotation SummarizationSetBy = Automatic

	column P_6A11_F
		dataType: int64
		formatString: 0
		lineageTag: 1561d852-8e5b-4561-8a06-c06d55489162
		summarizeBy: sum
		sourceColumn: P_6A11_F

		annotation SummarizationSetBy = Automatic

	column P_6A11_M
		dataType: int64
		formatString: 0
		lineageTag: c1d5e5b6-6273-4f3e-b953-7b990cc02f2b
		summarizeBy: sum
		sourceColumn: P_6A11_M

		annotation SummarizationSetBy = Automatic

	column P_8A14
		dataType: int64
		formatString: 0
		lineageTag: 7496e42b-1bba-4be6-9017-83d0d5ba9bdd
		summarizeBy: sum
		sourceColumn: P_8A14

		annotation SummarizationSetBy = Automatic

	column P_8A14_F
		dataType: int64
		formatString: 0
		lineageTag: c8c728f0-cf12-48c0-aad9-f0219cabe0bd
		summarizeBy: sum
		sourceColumn: P_8A14_F

		annotation SummarizationSetBy = Automatic

	column P_8A14_M
		dataType: int64
		formatString: 0
		lineageTag: fd569e1d-222a-4454-aa08-b094b1e67232
		summarizeBy: sum
		sourceColumn: P_8A14_M

		annotation SummarizationSetBy = Automatic

	column P_12A14
		dataType: int64
		formatString: 0
		lineageTag: 9f9462b9-3fe7-44d8-914e-c9298aa34e29
		summarizeBy: sum
		sourceColumn: P_12A14

		annotation SummarizationSetBy = Automatic

	column P_12A14_F
		dataType: int64
		formatString: 0
		lineageTag: 98dac01a-832f-45ec-bee0-c3d324ea8b3a
		summarizeBy: sum
		sourceColumn: P_12A14_F

		annotation SummarizationSetBy = Automatic

	column P_12A14_M
		dataType: int64
		formatString: 0
		lineageTag: e3f47a38-8e29-418a-b61b-115386a3a3e9
		summarizeBy: sum
		sourceColumn: P_12A14_M

		annotation SummarizationSetBy = Automatic

	column P_15A17
		dataType: int64
		formatString: 0
		lineageTag: 6fb112f2-4f17-44a9-a73a-f83e96887d87
		summarizeBy: sum
		sourceColumn: P_15A17

		annotation SummarizationSetBy = Automatic

	column P_15A17_F
		dataType: int64
		formatString: 0
		lineageTag: a45fab75-f600-45a6-82b7-910137e0884d
		summarizeBy: sum
		sourceColumn: P_15A17_F

		annotation SummarizationSetBy = Automatic

	column P_15A17_M
		dataType: int64
		formatString: 0
		lineageTag: 1cc4b353-952d-4c57-9c87-0fb1e05f3428
		summarizeBy: sum
		sourceColumn: P_15A17_M

		annotation SummarizationSetBy = Automatic

	column P_18A24
		dataType: int64
		formatString: 0
		lineageTag: 6ac5a215-7831-44c2-8832-dcb627c523e7
		summarizeBy: sum
		sourceColumn: P_18A24

		annotation SummarizationSetBy = Automatic

	column P_18A24_F
		dataType: int64
		formatString: 0
		lineageTag: ffa704a5-f1ae-4744-95c6-38f1ae60cca0
		summarizeBy: sum
		sourceColumn: P_18A24_F

		annotation SummarizationSetBy = Automatic

	column P_18A24_M
		dataType: int64
		formatString: 0
		lineageTag: 27c35dc9-e2d4-4166-ab1b-2df86f521363
		summarizeBy: sum
		sourceColumn: P_18A24_M

		annotation SummarizationSetBy = Automatic

	column P_15A49_F
		dataType: int64
		formatString: 0
		lineageTag: 35315724-650d-431b-a2b7-4315ceef57f3
		summarizeBy: sum
		sourceColumn: P_15A49_F

		annotation SummarizationSetBy = Automatic

	column P_60YMAS
		dataType: int64
		formatString: 0
		lineageTag: f05308b9-aad3-4967-a3ff-bcadf5684fcb
		summarizeBy: sum
		sourceColumn: P_60YMAS

		annotation SummarizationSetBy = Automatic

	column P_60YMAS_F
		dataType: int64
		formatString: 0
		lineageTag: 620eca06-ccb8-4312-b22e-166139cef4b7
		summarizeBy: sum
		sourceColumn: P_60YMAS_F

		annotation SummarizationSetBy = Automatic

	column P_60YMAS_M
		dataType: int64
		formatString: 0
		lineageTag: c0edd3ce-68da-417a-a058-7205d15bae20
		summarizeBy: sum
		sourceColumn: P_60YMAS_M

		annotation SummarizationSetBy = Automatic

	column REL_H_M
		dataType: double
		lineageTag: 72f32541-78cf-4ba0-9526-ad6277390512
		summarizeBy: sum
		sourceColumn: REL_H_M

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column POB0_14
		dataType: int64
		formatString: 0
		lineageTag: 9e154417-34d2-4673-a3e1-33d5c6630662
		summarizeBy: sum
		sourceColumn: POB0_14

		annotation SummarizationSetBy = Automatic

	column POB15_64
		dataType: int64
		formatString: 0
		lineageTag: 3b094705-5d7d-4cef-b8ec-dd1278f778f7
		summarizeBy: sum
		sourceColumn: POB15_64

		annotation SummarizationSetBy = Automatic

	column POB65_MAS
		dataType: int64
		formatString: 0
		lineageTag: ffd08bc6-386d-441c-aa51-753d399dfd40
		summarizeBy: sum
		sourceColumn: POB65_MAS

		annotation SummarizationSetBy = Automatic

	column PROM_HNV
		dataType: double
		lineageTag: 5ddd25fb-2480-4e07-bb89-837cbfd73471
		summarizeBy: sum
		sourceColumn: PROM_HNV

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column PNACENT
		dataType: int64
		formatString: 0
		lineageTag: 4851888f-ca64-47bc-ba72-caa37fd153fb
		summarizeBy: sum
		sourceColumn: PNACENT

		annotation SummarizationSetBy = Automatic

	column PNACENT_F
		dataType: int64
		formatString: 0
		lineageTag: 9ae8338c-de26-4d81-afae-568029da361d
		summarizeBy: sum
		sourceColumn: PNACENT_F

		annotation SummarizationSetBy = Automatic

	column PNACENT_M
		dataType: int64
		formatString: 0
		lineageTag: 0a6627c1-f251-492f-b63d-98cdfbfe84ec
		summarizeBy: sum
		sourceColumn: PNACENT_M

		annotation SummarizationSetBy = Automatic

	column PNACOE
		dataType: int64
		formatString: 0
		lineageTag: a3644e07-412e-4a98-8fc1-c5b8c3bef2d6
		summarizeBy: sum
		sourceColumn: PNACOE

		annotation SummarizationSetBy = Automatic

	column PNACOE_F
		dataType: int64
		formatString: 0
		lineageTag: b1c777d4-aefd-4712-bd36-acdeaf38d142
		summarizeBy: sum
		sourceColumn: PNACOE_F

		annotation SummarizationSetBy = Automatic

	column PNACOE_M
		dataType: int64
		formatString: 0
		lineageTag: 823f969a-363c-43e1-bed9-5fe97bb41e77
		summarizeBy: sum
		sourceColumn: PNACOE_M

		annotation SummarizationSetBy = Automatic

	column PRES2015
		dataType: int64
		formatString: 0
		lineageTag: bc63642d-0a65-405b-99af-3be35f687c11
		summarizeBy: sum
		sourceColumn: PRES2015

		annotation SummarizationSetBy = Automatic

	column PRES2015_F
		dataType: int64
		formatString: 0
		lineageTag: 2f75231c-a03d-4e6e-9ed1-72d89dcc063f
		summarizeBy: sum
		sourceColumn: PRES2015_F

		annotation SummarizationSetBy = Automatic

	column PRES2015_M
		dataType: int64
		formatString: 0
		lineageTag: d6870e8a-4b5b-48af-b53c-8ac867f675dc
		summarizeBy: sum
		sourceColumn: PRES2015_M

		annotation SummarizationSetBy = Automatic

	column PRESOE15
		dataType: int64
		formatString: 0
		lineageTag: bd851146-0383-4a69-becd-67339e6865da
		summarizeBy: sum
		sourceColumn: PRESOE15

		annotation SummarizationSetBy = Automatic

	column PRESOE15_F
		dataType: int64
		formatString: 0
		lineageTag: 8b269650-37e7-4874-8cfb-fa704cd1da35
		summarizeBy: sum
		sourceColumn: PRESOE15_F

		annotation SummarizationSetBy = Automatic

	column PRESOE15_M
		dataType: int64
		formatString: 0
		lineageTag: d9be7af4-a0a5-46c0-a9c3-7acfe39d2842
		summarizeBy: sum
		sourceColumn: PRESOE15_M

		annotation SummarizationSetBy = Automatic

	column P3YM_HLI
		dataType: int64
		formatString: 0
		lineageTag: 546d4c51-fa15-489a-857b-e384670caa52
		summarizeBy: sum
		sourceColumn: P3YM_HLI

		annotation SummarizationSetBy = Automatic

	column P3YM_HLI_F
		dataType: int64
		formatString: 0
		lineageTag: 8d9bc977-91ae-41a0-9528-d08cd2186680
		summarizeBy: sum
		sourceColumn: P3YM_HLI_F

		annotation SummarizationSetBy = Automatic

	column P3YM_HLI_M
		dataType: int64
		formatString: 0
		lineageTag: 57a2cbca-c187-47a5-9202-6333de253eb4
		summarizeBy: sum
		sourceColumn: P3YM_HLI_M

		annotation SummarizationSetBy = Automatic

	column P3HLINHE
		dataType: int64
		formatString: 0
		lineageTag: 174d5d37-88ee-4ab3-8244-9db50b769196
		summarizeBy: sum
		sourceColumn: P3HLINHE

		annotation SummarizationSetBy = Automatic

	column P3HLINHE_F
		dataType: int64
		formatString: 0
		lineageTag: 72eba7b9-7c7a-4f53-be04-c6c87921c318
		summarizeBy: sum
		sourceColumn: P3HLINHE_F

		annotation SummarizationSetBy = Automatic

	column P3HLINHE_M
		dataType: int64
		formatString: 0
		lineageTag: 41a4fdcd-0c8a-4945-8368-e3596fb3a336
		summarizeBy: sum
		sourceColumn: P3HLINHE_M

		annotation SummarizationSetBy = Automatic

	column P3HLI_HE
		dataType: int64
		formatString: 0
		lineageTag: 6ed6ddb2-5581-47c4-818a-7c08c78eb3f7
		summarizeBy: sum
		sourceColumn: P3HLI_HE

		annotation SummarizationSetBy = Automatic

	column P3HLI_HE_F
		dataType: int64
		formatString: 0
		lineageTag: 7a646190-8ebb-48c3-8d6a-63bd1de15a40
		summarizeBy: sum
		sourceColumn: P3HLI_HE_F

		annotation SummarizationSetBy = Automatic

	column P3HLI_HE_M
		dataType: int64
		formatString: 0
		lineageTag: 334289f1-a47a-46a9-a780-7029f623c659
		summarizeBy: sum
		sourceColumn: P3HLI_HE_M

		annotation SummarizationSetBy = Automatic

	column P5_HLI
		dataType: int64
		formatString: 0
		lineageTag: 4c4d85e0-1356-472b-978b-c8b1696338e4
		summarizeBy: sum
		sourceColumn: P5_HLI

		annotation SummarizationSetBy = Automatic

	column P5_HLI_NHE
		dataType: int64
		formatString: 0
		lineageTag: 6aee2f13-0e0d-47d0-a4d6-6b206c773cd8
		summarizeBy: sum
		sourceColumn: P5_HLI_NHE

		annotation SummarizationSetBy = Automatic

	column P5_HLI_HE
		dataType: int64
		formatString: 0
		lineageTag: cc2b3668-08a9-497a-8a1f-a48da0887fc1
		summarizeBy: sum
		sourceColumn: P5_HLI_HE

		annotation SummarizationSetBy = Automatic

	column PHOG_IND
		dataType: int64
		formatString: 0
		lineageTag: fff1bbbc-d35f-4a61-b565-3137003b27da
		summarizeBy: sum
		sourceColumn: PHOG_IND

		annotation SummarizationSetBy = Automatic

	column POB_AFRO
		dataType: int64
		formatString: 0
		lineageTag: dab85e97-74ae-44ca-8c8f-7a6c544a1fe4
		summarizeBy: sum
		sourceColumn: POB_AFRO

		annotation SummarizationSetBy = Automatic

	column POB_AFRO_F
		dataType: int64
		formatString: 0
		lineageTag: c3299222-224c-4eab-9f08-74279a7bd1d4
		summarizeBy: sum
		sourceColumn: POB_AFRO_F

		annotation SummarizationSetBy = Automatic

	column POB_AFRO_M
		dataType: int64
		formatString: 0
		lineageTag: 74faaf03-e236-4765-9e21-6598aaab6fd8
		summarizeBy: sum
		sourceColumn: POB_AFRO_M

		annotation SummarizationSetBy = Automatic

	column PCON_DISC
		dataType: int64
		formatString: 0
		lineageTag: 9ad21308-f2f4-4800-90c2-796db8a37d3b
		summarizeBy: sum
		sourceColumn: PCON_DISC

		annotation SummarizationSetBy = Automatic

	column PCDISC_MOT
		dataType: int64
		formatString: 0
		lineageTag: 866072fc-7179-4e31-b6e5-cf61644462dc
		summarizeBy: sum
		sourceColumn: PCDISC_MOT

		annotation SummarizationSetBy = Automatic

	column PCDISC_VIS
		dataType: int64
		formatString: 0
		lineageTag: 4d9047fe-55e7-46ae-8a84-8bbb5d528283
		summarizeBy: sum
		sourceColumn: PCDISC_VIS

		annotation SummarizationSetBy = Automatic

	column PCDISC_LENG
		dataType: int64
		formatString: 0
		lineageTag: 66bb18c1-37bf-4f64-bb17-ae0990118c77
		summarizeBy: sum
		sourceColumn: PCDISC_LENG

		annotation SummarizationSetBy = Automatic

	column PCDISC_AUD
		dataType: int64
		formatString: 0
		lineageTag: bce3c3b4-9566-4d50-ae77-b4e4a88580d0
		summarizeBy: sum
		sourceColumn: PCDISC_AUD

		annotation SummarizationSetBy = Automatic

	column PCDISC_MOT2
		dataType: int64
		formatString: 0
		lineageTag: cc5dbb50-2c87-47de-a7b8-5ff5bf331789
		summarizeBy: sum
		sourceColumn: PCDISC_MOT2

		annotation SummarizationSetBy = Automatic

	column PCDISC_MEN
		dataType: int64
		formatString: 0
		lineageTag: 9758f844-eab7-494a-8013-2cd4496cdee0
		summarizeBy: sum
		sourceColumn: PCDISC_MEN

		annotation SummarizationSetBy = Automatic

	column PCON_LIMI
		dataType: int64
		formatString: 0
		lineageTag: f8f650cd-9174-4b9e-b58c-d7b6716a2fab
		summarizeBy: sum
		sourceColumn: PCON_LIMI

		annotation SummarizationSetBy = Automatic

	column PCLIM_CSB
		dataType: int64
		formatString: 0
		lineageTag: 9adcb0b6-500c-4174-aa34-570a4a0db7c6
		summarizeBy: sum
		sourceColumn: PCLIM_CSB

		annotation SummarizationSetBy = Automatic

	column PCLIM_VIS
		dataType: int64
		formatString: 0
		lineageTag: 1136b3e6-3d2b-41ce-b71c-fbc95b5628ee
		summarizeBy: sum
		sourceColumn: PCLIM_VIS

		annotation SummarizationSetBy = Automatic

	column PCLIM_HACO
		dataType: int64
		formatString: 0
		lineageTag: 7eba8882-a3d2-437c-b452-bf4541404918
		summarizeBy: sum
		sourceColumn: PCLIM_HACO

		annotation SummarizationSetBy = Automatic

	column PCLIM_OAUD
		dataType: int64
		formatString: 0
		lineageTag: e9ce81fc-f6f9-4302-9d1c-da305f153148
		summarizeBy: sum
		sourceColumn: PCLIM_OAUD

		annotation SummarizationSetBy = Automatic

	column PCLIM_MOT2
		dataType: int64
		formatString: 0
		lineageTag: 63045e77-2dfc-408e-b88d-8225a30c7366
		summarizeBy: sum
		sourceColumn: PCLIM_MOT2

		annotation SummarizationSetBy = Automatic

	column PCLIM_RE_CO
		dataType: int64
		formatString: 0
		lineageTag: 4d3a2668-71b6-4e02-b837-a718d2cc4a93
		summarizeBy: sum
		sourceColumn: PCLIM_RE_CO

		annotation SummarizationSetBy = Automatic

	column PCLIM_PMEN
		dataType: int64
		formatString: 0
		lineageTag: d8a631d3-88c0-44ab-a48e-6cf425d0c03c
		summarizeBy: sum
		sourceColumn: PCLIM_PMEN

		annotation SummarizationSetBy = Automatic

	column PSIND_LIM
		dataType: int64
		formatString: 0
		lineageTag: 2d72fa14-8100-41c7-a745-b1fdac25a86d
		summarizeBy: sum
		sourceColumn: PSIND_LIM

		annotation SummarizationSetBy = Automatic

	column P3A5_NOA
		dataType: int64
		formatString: 0
		lineageTag: 6c6254a2-6836-4ea1-90a0-d77c0ef491df
		summarizeBy: sum
		sourceColumn: P3A5_NOA

		annotation SummarizationSetBy = Automatic

	column P3A5_NOA_F
		dataType: int64
		formatString: 0
		lineageTag: 7a4c64b5-9f5f-4d50-856c-aaa8b53c6f00
		summarizeBy: sum
		sourceColumn: P3A5_NOA_F

		annotation SummarizationSetBy = Automatic

	column P3A5_NOA_M
		dataType: int64
		formatString: 0
		lineageTag: 931a495c-084c-4966-a2e7-5d6629cfcd1a
		summarizeBy: sum
		sourceColumn: P3A5_NOA_M

		annotation SummarizationSetBy = Automatic

	column P6A11_NOA
		dataType: int64
		formatString: 0
		lineageTag: 489f3c19-c94b-4bdb-9f55-388160767fa7
		summarizeBy: sum
		sourceColumn: P6A11_NOA

		annotation SummarizationSetBy = Automatic

	column P6A11_NOAF
		dataType: int64
		formatString: 0
		lineageTag: 751b6906-b510-472e-9f1f-2c6448e559bb
		summarizeBy: sum
		sourceColumn: P6A11_NOAF

		annotation SummarizationSetBy = Automatic

	column P6A11_NOAM
		dataType: int64
		formatString: 0
		lineageTag: 43623b56-49b0-4ce3-9bb3-462d686a1a58
		summarizeBy: sum
		sourceColumn: P6A11_NOAM

		annotation SummarizationSetBy = Automatic

	column P12A14NOA
		dataType: int64
		formatString: 0
		lineageTag: c5b6c53b-d477-463b-a7df-15c3d0c38fae
		summarizeBy: sum
		sourceColumn: P12A14NOA

		annotation SummarizationSetBy = Automatic

	column P12A14NOAF
		dataType: int64
		formatString: 0
		lineageTag: 12230b72-80c0-4fb1-98c6-68e426755c45
		summarizeBy: sum
		sourceColumn: P12A14NOAF

		annotation SummarizationSetBy = Automatic

	column P12A14NOAM
		dataType: int64
		formatString: 0
		lineageTag: 9ebbf6b9-cd81-4f2b-ad18-939d731c1bef
		summarizeBy: sum
		sourceColumn: P12A14NOAM

		annotation SummarizationSetBy = Automatic

	column P15A17A
		dataType: int64
		formatString: 0
		lineageTag: 0540bfe1-7473-4aee-ad92-5baeae9ec603
		summarizeBy: sum
		sourceColumn: P15A17A

		annotation SummarizationSetBy = Automatic

	column P15A17A_F
		dataType: int64
		formatString: 0
		lineageTag: 7590908b-98ab-4d6c-9adf-035cac3f0750
		summarizeBy: sum
		sourceColumn: P15A17A_F

		annotation SummarizationSetBy = Automatic

	column P15A17A_M
		dataType: int64
		formatString: 0
		lineageTag: dfa8179e-6f66-425c-90ac-454aaf872ce0
		summarizeBy: sum
		sourceColumn: P15A17A_M

		annotation SummarizationSetBy = Automatic

	column P18A24A
		dataType: int64
		formatString: 0
		lineageTag: 8605de8a-2477-4ef9-a4b3-571eab72cd41
		summarizeBy: sum
		sourceColumn: P18A24A

		annotation SummarizationSetBy = Automatic

	column P18A24A_F
		dataType: int64
		formatString: 0
		lineageTag: 5fac79c3-5e5c-4649-8a87-1be9e07bb4d9
		summarizeBy: sum
		sourceColumn: P18A24A_F

		annotation SummarizationSetBy = Automatic

	column P18A24A_M
		dataType: int64
		formatString: 0
		lineageTag: 116a10e8-7bea-4b7b-b1f3-2a07d94ce6a6
		summarizeBy: sum
		sourceColumn: P18A24A_M

		annotation SummarizationSetBy = Automatic

	column P8A14AN
		dataType: int64
		formatString: 0
		lineageTag: 20d4f927-7096-4db8-bf05-515ea0919033
		summarizeBy: sum
		sourceColumn: P8A14AN

		annotation SummarizationSetBy = Automatic

	column P8A14AN_F
		dataType: int64
		formatString: 0
		lineageTag: 40d07243-e14b-4ed4-bda2-8e93a64455d6
		summarizeBy: sum
		sourceColumn: P8A14AN_F

		annotation SummarizationSetBy = Automatic

	column P8A14AN_M
		dataType: int64
		formatString: 0
		lineageTag: 83c4f4e4-cc53-4b60-9d4f-d1c4b1c6e302
		summarizeBy: sum
		sourceColumn: P8A14AN_M

		annotation SummarizationSetBy = Automatic

	column P15YM_AN
		dataType: int64
		formatString: 0
		lineageTag: 58492804-a14f-42a9-8aec-5eafef1f22b7
		summarizeBy: sum
		sourceColumn: P15YM_AN

		annotation SummarizationSetBy = Automatic

	column P15YM_AN_F
		dataType: int64
		formatString: 0
		lineageTag: c202d61c-08e4-409a-bb61-b3fcff7660c8
		summarizeBy: sum
		sourceColumn: P15YM_AN_F

		annotation SummarizationSetBy = Automatic

	column P15YM_AN_M
		dataType: int64
		formatString: 0
		lineageTag: 2f714d98-259d-42ba-8ab6-4f12721cdc9e
		summarizeBy: sum
		sourceColumn: P15YM_AN_M

		annotation SummarizationSetBy = Automatic

	column P15YM_SE
		dataType: int64
		formatString: 0
		lineageTag: 374c1a05-908c-4809-a1bb-bb70a43775f9
		summarizeBy: sum
		sourceColumn: P15YM_SE

		annotation SummarizationSetBy = Automatic

	column P15YM_SE_F
		dataType: int64
		formatString: 0
		lineageTag: 2b331a29-5b26-4cdb-aaf4-cac20255a48b
		summarizeBy: sum
		sourceColumn: P15YM_SE_F

		annotation SummarizationSetBy = Automatic

	column P15YM_SE_M
		dataType: int64
		formatString: 0
		lineageTag: 09ac093a-e6e8-4419-b9f1-da5653b9defa
		summarizeBy: sum
		sourceColumn: P15YM_SE_M

		annotation SummarizationSetBy = Automatic

	column P15PRI_IN
		dataType: int64
		formatString: 0
		lineageTag: 5d4c7f7c-bebc-4818-ab26-426f4971e42f
		summarizeBy: sum
		sourceColumn: P15PRI_IN

		annotation SummarizationSetBy = Automatic

	column P15PRI_INF
		dataType: int64
		formatString: 0
		lineageTag: 5626487d-0faf-4d90-b4f2-7248efecba64
		summarizeBy: sum
		sourceColumn: P15PRI_INF

		annotation SummarizationSetBy = Automatic

	column P15PRI_INM
		dataType: int64
		formatString: 0
		lineageTag: 1520f60b-0666-412d-aa79-8b9b57096aae
		summarizeBy: sum
		sourceColumn: P15PRI_INM

		annotation SummarizationSetBy = Automatic

	column P15PRI_CO
		dataType: int64
		formatString: 0
		lineageTag: 057a496c-2d74-44af-9b3d-61e242ba151a
		summarizeBy: sum
		sourceColumn: P15PRI_CO

		annotation SummarizationSetBy = Automatic

	column P15PRI_COF
		dataType: int64
		formatString: 0
		lineageTag: 60435c70-66b7-486d-9727-e598d9298f4a
		summarizeBy: sum
		sourceColumn: P15PRI_COF

		annotation SummarizationSetBy = Automatic

	column P15PRI_COM
		dataType: int64
		formatString: 0
		lineageTag: 5c74ca7a-14d5-47f0-897e-f86fd268a383
		summarizeBy: sum
		sourceColumn: P15PRI_COM

		annotation SummarizationSetBy = Automatic

	column P15SEC_IN
		dataType: int64
		formatString: 0
		lineageTag: 463583b0-b231-47cd-8fe5-688e77e1f1e5
		summarizeBy: sum
		sourceColumn: P15SEC_IN

		annotation SummarizationSetBy = Automatic

	column P15SEC_INF
		dataType: int64
		formatString: 0
		lineageTag: 8e2a785c-b341-4ba8-9cd5-2f80ed14af91
		summarizeBy: sum
		sourceColumn: P15SEC_INF

		annotation SummarizationSetBy = Automatic

	column P15SEC_INM
		dataType: int64
		formatString: 0
		lineageTag: 8d50c8a2-77bc-49cd-9174-b735d87b93e6
		summarizeBy: sum
		sourceColumn: P15SEC_INM

		annotation SummarizationSetBy = Automatic

	column P15SEC_CO
		dataType: int64
		formatString: 0
		lineageTag: 375aad54-8c14-4650-9c17-6de05eac746c
		summarizeBy: sum
		sourceColumn: P15SEC_CO

		annotation SummarizationSetBy = Automatic

	column P15SEC_COF
		dataType: int64
		formatString: 0
		lineageTag: e6b31f14-e0da-4c95-9491-30df5a717502
		summarizeBy: sum
		sourceColumn: P15SEC_COF

		annotation SummarizationSetBy = Automatic

	column P15SEC_COM
		dataType: int64
		formatString: 0
		lineageTag: 06a7b04a-6b09-4a65-b6f9-9ff1fea44e55
		summarizeBy: sum
		sourceColumn: P15SEC_COM

		annotation SummarizationSetBy = Automatic

	column P18YM_PB
		dataType: int64
		formatString: 0
		lineageTag: 79bd2a32-0ec4-4d4a-9078-c8f879a19b5b
		summarizeBy: sum
		sourceColumn: P18YM_PB

		annotation SummarizationSetBy = Automatic

	column P18YM_PB_F
		dataType: int64
		formatString: 0
		lineageTag: 8e5acf41-8a32-4d36-8f1b-c78d9639e094
		summarizeBy: sum
		sourceColumn: P18YM_PB_F

		annotation SummarizationSetBy = Automatic

	column P18YM_PB_M
		dataType: int64
		formatString: 0
		lineageTag: 89ad4205-b098-4a04-8571-be9ccd8aa48d
		summarizeBy: sum
		sourceColumn: P18YM_PB_M

		annotation SummarizationSetBy = Automatic

	column GRAPROES
		dataType: double
		lineageTag: 9d0df11f-de37-486f-b43c-168ed3063cc6
		summarizeBy: sum
		sourceColumn: GRAPROES

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column GRAPROES_F
		dataType: double
		lineageTag: a000aa5d-bb24-486c-9bab-9f926f94b7c6
		summarizeBy: sum
		sourceColumn: GRAPROES_F

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column GRAPROES_M
		dataType: double
		lineageTag: bd4360df-e229-44f2-a1cf-418c8e6dfd85
		summarizeBy: sum
		sourceColumn: GRAPROES_M

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column PEA
		dataType: int64
		formatString: 0
		lineageTag: 8b18ecd7-363a-45b7-b302-79d478025397
		summarizeBy: sum
		sourceColumn: PEA

		annotation SummarizationSetBy = Automatic

	column PEA_F
		dataType: int64
		formatString: 0
		lineageTag: 19553dfa-28ff-41c3-8f08-052c2a0b6e05
		summarizeBy: sum
		sourceColumn: PEA_F

		annotation SummarizationSetBy = Automatic

	column PEA_M
		dataType: int64
		formatString: 0
		lineageTag: af7f3449-411d-4d9c-9687-bb390a3bdd57
		summarizeBy: sum
		sourceColumn: PEA_M

		annotation SummarizationSetBy = Automatic

	column PE_INAC
		dataType: int64
		formatString: 0
		lineageTag: 723ae6b4-e0c7-4241-843b-723a940606b3
		summarizeBy: sum
		sourceColumn: PE_INAC

		annotation SummarizationSetBy = Automatic

	column PE_INAC_F
		dataType: int64
		formatString: 0
		lineageTag: 704aadbf-5840-4250-a26f-d368c424c353
		summarizeBy: sum
		sourceColumn: PE_INAC_F

		annotation SummarizationSetBy = Automatic

	column PE_INAC_M
		dataType: int64
		formatString: 0
		lineageTag: ea97e64c-381f-4cf4-9bc9-be4f0ed5173d
		summarizeBy: sum
		sourceColumn: PE_INAC_M

		annotation SummarizationSetBy = Automatic

	column POCUPADA
		dataType: int64
		formatString: 0
		lineageTag: 1db7e7d0-72df-4f47-b5ac-4d6f180456e5
		summarizeBy: sum
		sourceColumn: POCUPADA

		annotation SummarizationSetBy = Automatic

	column POCUPADA_F
		dataType: int64
		formatString: 0
		lineageTag: 1dbb1d58-1b2b-44ae-a850-869d32762f93
		summarizeBy: sum
		sourceColumn: POCUPADA_F

		annotation SummarizationSetBy = Automatic

	column POCUPADA_M
		dataType: int64
		formatString: 0
		lineageTag: 8aaeb29d-4d59-4507-9daa-1a69f53a0c2f
		summarizeBy: sum
		sourceColumn: POCUPADA_M

		annotation SummarizationSetBy = Automatic

	column PDESOCUP
		dataType: int64
		formatString: 0
		lineageTag: 754d0257-cdac-451c-9435-6668bc55c9c6
		summarizeBy: sum
		sourceColumn: PDESOCUP

		annotation SummarizationSetBy = Automatic

	column PDESOCUP_F
		dataType: int64
		formatString: 0
		lineageTag: d2151704-0432-4a67-b746-45e8f6ffa09e
		summarizeBy: sum
		sourceColumn: PDESOCUP_F

		annotation SummarizationSetBy = Automatic

	column PDESOCUP_M
		dataType: int64
		formatString: 0
		lineageTag: 97f59316-6dd2-4758-8628-7e33c4062568
		summarizeBy: sum
		sourceColumn: PDESOCUP_M

		annotation SummarizationSetBy = Automatic

	column PSINDER
		dataType: int64
		formatString: 0
		lineageTag: 6728299c-b75c-4853-9fea-6f6c6a176906
		summarizeBy: sum
		sourceColumn: PSINDER

		annotation SummarizationSetBy = Automatic

	column PDER_SS
		dataType: int64
		formatString: 0
		lineageTag: a1a6f871-5661-4d08-ba23-c473c75b5aaa
		summarizeBy: sum
		sourceColumn: PDER_SS

		annotation SummarizationSetBy = Automatic

	column PDER_IMSS
		dataType: int64
		formatString: 0
		lineageTag: ab36032b-0b53-485d-8b03-f052e0fd031a
		summarizeBy: sum
		sourceColumn: PDER_IMSS

		annotation SummarizationSetBy = Automatic

	column PDER_ISTE
		dataType: int64
		formatString: 0
		lineageTag: 012a1a43-b0ff-4b03-a209-5efe57ada9d7
		summarizeBy: sum
		sourceColumn: PDER_ISTE

		annotation SummarizationSetBy = Automatic

	column PDER_ISTEE
		dataType: int64
		formatString: 0
		lineageTag: a88e559d-53a3-41b1-9001-af76b9bd9041
		summarizeBy: sum
		sourceColumn: PDER_ISTEE

		annotation SummarizationSetBy = Automatic

	column PAFIL_PDOM
		dataType: int64
		formatString: 0
		lineageTag: 2b862b15-2f9a-4fde-8530-08473e40483d
		summarizeBy: sum
		sourceColumn: PAFIL_PDOM

		annotation SummarizationSetBy = Automatic

	column PDER_SEGP
		dataType: int64
		formatString: 0
		lineageTag: 8aa67b16-06b1-4190-8bee-932ca916dc0f
		summarizeBy: sum
		sourceColumn: PDER_SEGP

		annotation SummarizationSetBy = Automatic

	column PDER_IMSSB
		dataType: int64
		formatString: 0
		lineageTag: d98a322e-cb61-4c2f-b229-08d7821018ea
		summarizeBy: sum
		sourceColumn: PDER_IMSSB

		annotation SummarizationSetBy = Automatic

	column PAFIL_IPRIV
		dataType: int64
		formatString: 0
		lineageTag: 5049017b-05e7-4ee9-911a-cb9dfe7783c0
		summarizeBy: sum
		sourceColumn: PAFIL_IPRIV

		annotation SummarizationSetBy = Automatic

	column PAFIL_OTRAI
		dataType: int64
		formatString: 0
		lineageTag: 8f4622a5-e0d0-48f8-902f-008f8bd5019f
		summarizeBy: sum
		sourceColumn: PAFIL_OTRAI

		annotation SummarizationSetBy = Automatic

	column P12YM_SOLT
		dataType: int64
		formatString: 0
		lineageTag: 620ad8be-d3d9-402c-af21-117f2e2a12b2
		summarizeBy: sum
		sourceColumn: P12YM_SOLT

		annotation SummarizationSetBy = Automatic

	column P12YM_CASA
		dataType: int64
		formatString: 0
		lineageTag: e0a1f5e4-d03a-46ad-a104-7fd908b28dd7
		summarizeBy: sum
		sourceColumn: P12YM_CASA

		annotation SummarizationSetBy = Automatic

	column P12YM_SEPA
		dataType: int64
		formatString: 0
		lineageTag: 15a71f8d-a73c-4098-a29d-f71b7d05419d
		summarizeBy: sum
		sourceColumn: P12YM_SEPA

		annotation SummarizationSetBy = Automatic

	column PCATOLICA
		dataType: int64
		formatString: 0
		lineageTag: c4b56c8d-40dc-4363-9028-159efaae71d0
		summarizeBy: sum
		sourceColumn: PCATOLICA

		annotation SummarizationSetBy = Automatic

	column PRO_CRIEVA
		dataType: int64
		formatString: 0
		lineageTag: c60d6911-2eca-4de9-b158-4325a08a3f21
		summarizeBy: sum
		sourceColumn: PRO_CRIEVA

		annotation SummarizationSetBy = Automatic

	column POTRAS_REL
		dataType: int64
		formatString: 0
		lineageTag: 09492744-f7ac-4abd-8546-435f8d0b0fcc
		summarizeBy: sum
		sourceColumn: POTRAS_REL

		annotation SummarizationSetBy = Automatic

	column PSIN_RELIG
		dataType: int64
		formatString: 0
		lineageTag: c2a8990b-9b32-4860-a4ff-a0e177d8a76b
		summarizeBy: sum
		sourceColumn: PSIN_RELIG

		annotation SummarizationSetBy = Automatic

	column TOTHOG
		dataType: int64
		formatString: 0
		lineageTag: 60d8473d-2cbc-493f-84c0-d6c980fb20ed
		summarizeBy: sum
		sourceColumn: TOTHOG

		annotation SummarizationSetBy = Automatic

	column HOGJEF_F
		dataType: int64
		formatString: 0
		lineageTag: 510b4e67-dd7b-4380-88ef-c7f8b3ff9bcb
		summarizeBy: sum
		sourceColumn: HOGJEF_F

		annotation SummarizationSetBy = Automatic

	column HOGJEF_M
		dataType: int64
		formatString: 0
		lineageTag: c51ca08c-a074-4ee3-8017-930d745d15ca
		summarizeBy: sum
		sourceColumn: HOGJEF_M

		annotation SummarizationSetBy = Automatic

	column POBHOG
		dataType: int64
		formatString: 0
		lineageTag: 294bcad2-f403-4a9c-bef1-160160d8cf1f
		summarizeBy: sum
		sourceColumn: POBHOG

		annotation SummarizationSetBy = Automatic

	column PHOGJEF_F
		dataType: int64
		formatString: 0
		lineageTag: 3059e885-96b1-4131-bef7-7b0155440316
		summarizeBy: sum
		sourceColumn: PHOGJEF_F

		annotation SummarizationSetBy = Automatic

	column PHOGJEF_M
		dataType: int64
		formatString: 0
		lineageTag: 93a6d2c4-f2c0-4c44-b9b1-91eaf9fbe97e
		summarizeBy: sum
		sourceColumn: PHOGJEF_M

		annotation SummarizationSetBy = Automatic

	column VIVTOT
		dataType: int64
		formatString: 0
		lineageTag: 7dc8c594-2a60-401f-a6b8-775aa495dd4a
		summarizeBy: sum
		sourceColumn: VIVTOT

		annotation SummarizationSetBy = Automatic

	column TVIVHAB
		dataType: int64
		formatString: 0
		lineageTag: 0eea5785-c4c9-47d2-8eca-d768527f55fe
		summarizeBy: sum
		sourceColumn: TVIVHAB

		annotation SummarizationSetBy = Automatic

	column TVIVPAR
		dataType: int64
		formatString: 0
		lineageTag: 82b30aef-018b-42dc-a1fe-4dc86906c638
		summarizeBy: sum
		sourceColumn: TVIVPAR

		annotation SummarizationSetBy = Automatic

	column VIVPAR_HAB
		dataType: int64
		formatString: 0
		lineageTag: 3b0e2821-f703-4211-9c91-a73880bb6c85
		summarizeBy: sum
		sourceColumn: VIVPAR_HAB

		annotation SummarizationSetBy = Automatic

	column VIVPARH_CV
		dataType: int64
		formatString: 0
		lineageTag: e12e05be-95ce-4514-9dba-5ce4943c17f3
		summarizeBy: sum
		sourceColumn: VIVPARH_CV

		annotation SummarizationSetBy = Automatic

	column TVIVPARHAB
		dataType: int64
		formatString: 0
		lineageTag: d03bb19c-4b6e-4839-b075-53d4af2339e1
		summarizeBy: sum
		sourceColumn: TVIVPARHAB

		annotation SummarizationSetBy = Automatic

	column VIVPAR_DES
		dataType: int64
		formatString: 0
		lineageTag: 5c63800f-53e2-4735-9169-9b9675c69c08
		summarizeBy: sum
		sourceColumn: VIVPAR_DES

		annotation SummarizationSetBy = Automatic

	column VIVPAR_UT
		dataType: int64
		formatString: 0
		lineageTag: 45d89938-9043-40e5-ac97-b0476de8c736
		summarizeBy: sum
		sourceColumn: VIVPAR_UT

		annotation SummarizationSetBy = Automatic

	column OCUPVIVPAR
		dataType: int64
		formatString: 0
		lineageTag: a2f7d411-4e52-4fe0-a32e-4fede2a21745
		summarizeBy: sum
		sourceColumn: OCUPVIVPAR

		annotation SummarizationSetBy = Automatic

	column PROM_OCUP
		dataType: double
		lineageTag: ae0fa046-18f3-4c0c-b8d7-13ea1e643b45
		summarizeBy: sum
		sourceColumn: PROM_OCUP

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column PRO_OCUP_C
		dataType: double
		lineageTag: f11e3dc4-9827-406d-beaa-c3ab3dfd5f4b
		summarizeBy: sum
		sourceColumn: PRO_OCUP_C

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column VPH_PISODT
		dataType: int64
		formatString: 0
		lineageTag: bff39825-f6e5-4f1d-827a-c712ec22665c
		summarizeBy: sum
		sourceColumn: VPH_PISODT

		annotation SummarizationSetBy = Automatic

	column VPH_PISOTI
		dataType: int64
		formatString: 0
		lineageTag: 48ee8fae-51ae-4c5b-80a9-fa518c0f2fa5
		summarizeBy: sum
		sourceColumn: VPH_PISOTI

		annotation SummarizationSetBy = Automatic

	column VPH_1DOR
		dataType: int64
		formatString: 0
		lineageTag: f58d982c-d7a7-485a-8df8-661d3f785546
		summarizeBy: sum
		sourceColumn: VPH_1DOR

		annotation SummarizationSetBy = Automatic

	column VPH_2YMASD
		dataType: int64
		formatString: 0
		lineageTag: c7b83209-68c5-439c-8918-509782e09242
		summarizeBy: sum
		sourceColumn: VPH_2YMASD

		annotation SummarizationSetBy = Automatic

	column VPH_1CUART
		dataType: int64
		formatString: 0
		lineageTag: cb66ca5f-9a19-4327-9a92-4c998ca767cc
		summarizeBy: sum
		sourceColumn: VPH_1CUART

		annotation SummarizationSetBy = Automatic

	column VPH_2CUART
		dataType: int64
		formatString: 0
		lineageTag: 3a2c31f1-ad08-4655-8c0d-4491c91ef2bb
		summarizeBy: sum
		sourceColumn: VPH_2CUART

		annotation SummarizationSetBy = Automatic

	column VPH_3YMASC
		dataType: int64
		formatString: 0
		lineageTag: 613ddfbd-2dd5-4dd1-b6d6-761148904b6a
		summarizeBy: sum
		sourceColumn: VPH_3YMASC

		annotation SummarizationSetBy = Automatic

	column VPH_C_ELEC
		dataType: int64
		formatString: 0
		lineageTag: 2d06f527-5303-495a-b49e-9a3f8ceb863a
		summarizeBy: sum
		sourceColumn: VPH_C_ELEC

		annotation SummarizationSetBy = Automatic

	column VPH_S_ELEC
		dataType: int64
		formatString: 0
		lineageTag: ebf8d682-b7ca-4634-8661-0e9b3eafb34c
		summarizeBy: sum
		sourceColumn: VPH_S_ELEC

		annotation SummarizationSetBy = Automatic

	column VPH_AGUADV
		dataType: int64
		formatString: 0
		lineageTag: 63a5e83b-68cb-4e23-94f1-5ce92af92c43
		summarizeBy: sum
		sourceColumn: VPH_AGUADV

		annotation SummarizationSetBy = Automatic

	column VPH_AEASP
		dataType: int64
		formatString: 0
		lineageTag: 1a732333-12ed-43e0-87c1-2f4b3ced75e1
		summarizeBy: sum
		sourceColumn: VPH_AEASP

		annotation SummarizationSetBy = Automatic

	column VPH_AGUAFV
		dataType: int64
		formatString: 0
		lineageTag: 89578c6f-fa3a-4338-86cc-c87b8c8462b8
		summarizeBy: sum
		sourceColumn: VPH_AGUAFV

		annotation SummarizationSetBy = Automatic

	column VPH_TINACO
		dataType: int64
		formatString: 0
		lineageTag: 4e13b09a-cec4-4c5b-a2b9-cfe3122fda50
		summarizeBy: sum
		sourceColumn: VPH_TINACO

		annotation SummarizationSetBy = Automatic

	column VPH_CISTER
		dataType: int64
		formatString: 0
		lineageTag: 478c2abc-48d0-4ae1-b4c2-e222f6639b56
		summarizeBy: sum
		sourceColumn: VPH_CISTER

		annotation SummarizationSetBy = Automatic

	column VPH_EXCSA
		dataType: int64
		formatString: 0
		lineageTag: 8e2e5928-779d-4e95-bc4c-ac77c13489b9
		summarizeBy: sum
		sourceColumn: VPH_EXCSA

		annotation SummarizationSetBy = Automatic

	column VPH_LETR
		dataType: int64
		formatString: 0
		lineageTag: 4c001f0a-ee4a-4db0-98b4-c33264c6db2e
		summarizeBy: sum
		sourceColumn: VPH_LETR

		annotation SummarizationSetBy = Automatic

	column VPH_DRENAJ
		dataType: int64
		formatString: 0
		lineageTag: f805669b-5f96-4342-bd1a-6ef89c8dfdfe
		summarizeBy: sum
		sourceColumn: VPH_DRENAJ

		annotation SummarizationSetBy = Automatic

	column VPH_NODREN
		dataType: int64
		formatString: 0
		lineageTag: ad157ecc-93ee-4931-b556-c922ab063462
		summarizeBy: sum
		sourceColumn: VPH_NODREN

		annotation SummarizationSetBy = Automatic

	column VPH_C_SERV
		dataType: int64
		formatString: 0
		lineageTag: 7b2e8313-cce6-4607-9ce4-c088443a0e1f
		summarizeBy: sum
		sourceColumn: VPH_C_SERV

		annotation SummarizationSetBy = Automatic

	column VPH_NDEAED
		dataType: int64
		formatString: 0
		lineageTag: 3ffa5f1e-881d-4059-9c1c-c8155dd15a49
		summarizeBy: sum
		sourceColumn: VPH_NDEAED

		annotation SummarizationSetBy = Automatic

	column VPH_DSADMA
		dataType: int64
		formatString: 0
		lineageTag: 7f92090f-09f0-477e-8f94-b0d833025ad6
		summarizeBy: sum
		sourceColumn: VPH_DSADMA

		annotation SummarizationSetBy = Automatic

	column VPH_NDACMM
		dataType: int64
		formatString: 0
		lineageTag: 59447996-ccf1-4d4d-b5f3-27b718006b07
		summarizeBy: sum
		sourceColumn: VPH_NDACMM

		annotation SummarizationSetBy = Automatic

	column VPH_SNBIEN
		dataType: int64
		formatString: 0
		lineageTag: d096840b-2781-4647-9f2a-b118d17077aa
		summarizeBy: sum
		sourceColumn: VPH_SNBIEN

		annotation SummarizationSetBy = Automatic

	column VPH_REFRI
		dataType: int64
		formatString: 0
		lineageTag: 34d814a5-8ac8-4530-9485-ec1baeb60f6d
		summarizeBy: sum
		sourceColumn: VPH_REFRI

		annotation SummarizationSetBy = Automatic

	column VPH_LAVAD
		dataType: int64
		formatString: 0
		lineageTag: 7bffaa14-d35b-4a62-b787-bc6fa0f54017
		summarizeBy: sum
		sourceColumn: VPH_LAVAD

		annotation SummarizationSetBy = Automatic

	column VPH_HMICRO
		dataType: int64
		formatString: 0
		lineageTag: 7c12fe32-0368-4f9e-bb52-f7689b59593f
		summarizeBy: sum
		sourceColumn: VPH_HMICRO

		annotation SummarizationSetBy = Automatic

	column VPH_AUTOM
		dataType: int64
		formatString: 0
		lineageTag: f2dcccf6-c46d-4596-863b-1e3880bc1408
		summarizeBy: sum
		sourceColumn: VPH_AUTOM

		annotation SummarizationSetBy = Automatic

	column VPH_MOTO
		dataType: int64
		formatString: 0
		lineageTag: e1b21c75-22d1-4cbc-93fe-6ea861e7c637
		summarizeBy: sum
		sourceColumn: VPH_MOTO

		annotation SummarizationSetBy = Automatic

	column VPH_BICI
		dataType: int64
		formatString: 0
		lineageTag: 912e06d4-5f55-4be4-a739-d4d6a2973b23
		summarizeBy: sum
		sourceColumn: VPH_BICI

		annotation SummarizationSetBy = Automatic

	column VPH_RADIO
		dataType: int64
		formatString: 0
		lineageTag: d87a9459-ff0e-4a1b-8082-31a77a02fd96
		summarizeBy: sum
		sourceColumn: VPH_RADIO

		annotation SummarizationSetBy = Automatic

	column VPH_TV
		dataType: int64
		formatString: 0
		lineageTag: 799f462d-81d6-4468-b45c-1a58c39a9b80
		summarizeBy: sum
		sourceColumn: VPH_TV

		annotation SummarizationSetBy = Automatic

	column VPH_PC
		dataType: int64
		formatString: 0
		lineageTag: d4e3b0f5-815a-431b-b77e-3039b65cd1ea
		summarizeBy: sum
		sourceColumn: VPH_PC

		annotation SummarizationSetBy = Automatic

	column VPH_TELEF
		dataType: int64
		formatString: 0
		lineageTag: b403ae53-50e8-428f-90c3-9e7cf4f92e03
		summarizeBy: sum
		sourceColumn: VPH_TELEF

		annotation SummarizationSetBy = Automatic

	column VPH_CEL
		dataType: int64
		formatString: 0
		lineageTag: ddd08f52-bef0-42c2-8a6c-3d657957a4b4
		summarizeBy: sum
		sourceColumn: VPH_CEL

		annotation SummarizationSetBy = Automatic

	column VPH_INTER
		dataType: int64
		formatString: 0
		lineageTag: f4b51c08-04a1-4e51-a4b9-839f28937c4f
		summarizeBy: sum
		sourceColumn: VPH_INTER

		annotation SummarizationSetBy = Automatic

	column VPH_STVP
		dataType: int64
		formatString: 0
		lineageTag: 4acfa859-222f-4366-8643-2ea6e37dc969
		summarizeBy: sum
		sourceColumn: VPH_STVP

		annotation SummarizationSetBy = Automatic

	column VPH_SPMVPI
		dataType: int64
		formatString: 0
		lineageTag: 21e968f1-9221-4053-8bb5-8ed307e4f21e
		summarizeBy: sum
		sourceColumn: VPH_SPMVPI

		annotation SummarizationSetBy = Automatic

	column VPH_CVJ
		dataType: int64
		formatString: 0
		lineageTag: 48cfcb9d-2551-490f-8275-c8feae1cbedf
		summarizeBy: sum
		sourceColumn: VPH_CVJ

		annotation SummarizationSetBy = Automatic

	column VPH_SINRTV
		dataType: int64
		formatString: 0
		lineageTag: da9690ca-6a77-4fe9-aea3-578e4f2fcdc6
		summarizeBy: sum
		sourceColumn: VPH_SINRTV

		annotation SummarizationSetBy = Automatic

	column VPH_SINLTC
		dataType: int64
		formatString: 0
		lineageTag: adb6f768-ef16-4bca-99db-bbf3c14ae45b
		summarizeBy: sum
		sourceColumn: VPH_SINLTC

		annotation SummarizationSetBy = Automatic

	column VPH_SINCINT
		dataType: int64
		formatString: 0
		lineageTag: 667e9029-839c-4c33-8d2a-fb4609dd4c22
		summarizeBy: sum
		sourceColumn: VPH_SINCINT

		annotation SummarizationSetBy = Automatic

	column VPH_SINTIC
		dataType: int64
		formatString: 0
		lineageTag: 21e402dc-965d-4584-a6de-c12d9d12c93d
		summarizeBy: sum
		sourceColumn: VPH_SINTIC

		annotation SummarizationSetBy = Automatic

	column CVE_AGEB
		dataType: string
		lineageTag: 8db68448-c8fe-4546-a58a-5b6e39bb6263
		summarizeBy: none
		sourceColumn: CVE_AGEB

		annotation SummarizationSetBy = Automatic

	column CVE_MZA
		dataType: string
		lineageTag: 5e2a20c4-d255-448d-9f8f-0349a6e535ac
		summarizeBy: none
		sourceColumn: CVE_MZA

		annotation SummarizationSetBy = Automatic

	column clave_ageb_mza
		dataType: string
		lineageTag: 7ae68533-a45d-438e-9360-284be6c98f84
		summarizeBy: none
		sourceColumn: clave_ageb_mza

		annotation SummarizationSetBy = Automatic

	column CVE_GEO
		dataType: string
		lineageTag: b93a1a2f-4951-4c85-bd00-7d108424581d
		summarizeBy: none
		sourceColumn: CVE_GEO

		annotation SummarizationSetBy = Automatic

	column archivo_origen
		dataType: string
		lineageTag: c7c8e2d0-f3c8-47e0-a1e0-56871bf9a1e7
		summarizeBy: none
		sourceColumn: archivo_origen

		annotation SummarizationSetBy = Automatic

	column fecha_procesamiento
		dataType: dateTime
		formatString: General Date
		lineageTag: 2a53bdea-94c8-4279-bd7c-7a335e03aad0
		summarizeBy: none
		sourceColumn: fecha_procesamiento

		annotation SummarizationSetBy = Automatic

	column NOM_LOC_ITER
		dataType: string
		lineageTag: 6c17fa2e-c580-410a-bbba-b5cca948fc92
		summarizeBy: none
		sourceColumn: NOM_LOC_ITER

		annotation SummarizationSetBy = Automatic

	column LONGITUD
		dataType: double
		lineageTag: aa623572-3ebd-43df-afd8-0786161e698e
		summarizeBy: sum
		sourceColumn: LONGITUD

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column LATITUD
		dataType: double
		lineageTag: 4aa83493-6eaf-4cfc-b8b0-fcdea9924c1d
		summarizeBy: sum
		sourceColumn: LATITUD

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column ALTITUD
		dataType: string
		lineageTag: 84666945-05d2-42f8-9dbb-35a04bea9b8e
		summarizeBy: none
		sourceColumn: ALTITUD

		annotation SummarizationSetBy = Automatic

	partition censo_ageb_2020_nacional_coordenadas = m
		mode: import
		source =
				let
				    Source = Sql.Database("qihyhmenysou5otulys7x473hm-wmsh36vm2hsepif26nl54mytlu.datawarehouse.fabric.microsoft.com", "lh_lokus_censo_2020AGEB"),
				    dbo_censo_ageb_2020_nacional_coordenadas = Source{[Schema="dbo",Item="censo_ageb_2020_nacional_coordenadas"]}[Data],
				    #"Filtered Rows" = Table.SelectRows(dbo_censo_ageb_2020_nacional_coordenadas, each ([MUN] <> "000") and ([LOC] <> "0000") and ([MZA] <> "000")),
				    #"Renamed Columns" = Table.RenameColumns(#"Filtered Rows",{{"clave_ageb", "CVE_GEO"}})
				in
				    #"Renamed Columns"

	annotation PBI_NavigationStepName = Navigation

	annotation PBI_ResultType = Table

