table FACTDENUE2025
	lineageTag: 598eaa45-cc72-41cf-b428-61c13b3f2e6d

	measure 'Total Empresas' = COUNTROWS(FACTDENUE2025)
		formatString: 0
		lineageTag: 5559a944-df50-4ab4-91e8-64a2832676a3

	measure 'Total Estados' = DISTINCTCOUNT(FACTDENUE2025[cve_ent])
		formatString: 0
		lineageTag: 4772366d-6779-4e5a-8984-bca14044a1d5

	measure 'Total Municipios' = DISTINCTCOUNT(FACTDENUE2025[cve_mun_completa])
		formatString: 0
		lineageTag: 4dc4092b-ca25-4b80-9538-4e460b32a33e

	measure 'Total Actividades' = DISTINCTCOUNT(FACTDENUE2025[codigo_act])
		formatString: 0
		lineageTag: 56576123-7c35-47f9-b0d4-9d18b952e724

	measure 'Empresas Micro' = CALCULATE([Total Empresas], CATEGORIA_EMPRESA[categoria_empresa] = "Micro")
		formatString: 0.00
		lineageTag: c5b54189-3b9a-43ec-9009-438ff6c83526

	measure 'Empresas Pequeña' = CALCULATE([Total Empresas], CATEGORIA_EMPRESA[categoria_empresa] = "Pequeña")
		formatString: 0.00
		lineageTag: 75a1a390-8e2c-43ad-b1af-21fdcd654116

	measure 'Empresas Mediana' = CALCULATE([Total Empresas], CATEGORIA_EMPRESA[categoria_empresa] = "Mediana")
		formatString: 0
		lineageTag: 8eb2a655-c89e-443f-b46a-8f99cae1bbf4

	measure 'Empresas Grande' = CALCULATE([Total Empresas], CATEGORIA_EMPRESA[categoria_empresa] = "Grande")
		formatString: 0.0
		lineageTag: 54526e0d-355f-4359-8b83-a36e6fdd0f86

	measure 'Densidad Empresarial' =
			
			DIVIDE([Total Empresas], DISTINCTCOUNT(FACTDENUE2025[cve_mun]), 0)
		lineageTag: af5399fd-5298-4980-87ac-a4cac284e144

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure '% Empresas Micro' =
			
			DIVIDE([Empresas Micro], [Total Empresas], 0)
		lineageTag: 98878fee-97a5-4633-8eb3-f5542530f014

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure 'Municipios con Empresas' = DISTINCTCOUNT(FACTDENUE2025[cve_mun_completa])
		formatString: 0
		lineageTag: 4f4bcfc8-591e-4078-99c5-33a5c7f2f4c0

	measure 'Porcentaje Estado' = ```
			
			VAR TotalGeneral = 
			    CALCULATE(
			        [Total Empresas],
			        REMOVEFILTERS(entidad)
			    )
			RETURN
			    DIVIDE([Total Empresas], TotalGeneral, 0) * 100
			```
		lineageTag: e811a255-c9ff-43d3-b725-2ec537df8c21

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure 'Porcentaje de elementos primarios'
		lineageTag: 3d2fe4b0-00fb-48cb-a48a-735e769eeb3a

	column id
		dataType: string
		isHidden
		lineageTag: 8d191911-e9ea-4f51-98e2-6c9a8fad57f0
		summarizeBy: none
		sourceColumn: id

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

	column nom_estab
		dataType: string
		lineageTag: 9ce06a3d-ff15-4ec0-b361-244d1aaa027e
		summarizeBy: none
		sourceColumn: nom_estab

		annotation SummarizationSetBy = Automatic

	column raz_social
		dataType: string
		lineageTag: 61fd3b0f-9edf-4a0a-acb8-7c0e5b09ac01
		summarizeBy: none
		sourceColumn: raz_social

		annotation SummarizationSetBy = Automatic

	column codigo_act
		dataType: string
		lineageTag: e9d34766-346b-4438-8236-12e171979a5c
		summarizeBy: none
		sourceColumn: codigo_act

		annotation SummarizationSetBy = Automatic

	column nombre_act
		dataType: string
		lineageTag: be824fc8-658e-49b6-9b27-0626c196f248
		summarizeBy: none
		sourceColumn: nombre_act

		annotation SummarizationSetBy = Automatic

	column per_ocu
		dataType: string
		lineageTag: e6097427-4735-4835-894a-29dd7e9e3b7b
		summarizeBy: none
		sourceColumn: per_ocu

		annotation SummarizationSetBy = Automatic

	column tipo_asent
		dataType: string
		lineageTag: 400606c9-f6f1-4b4b-b888-0a87311e0717
		summarizeBy: none
		sourceColumn: tipo_asent

		annotation SummarizationSetBy = Automatic

	column nomb_asent
		dataType: string
		lineageTag: 778411fb-b7a3-49fa-9d3a-dd74e6f5c416
		summarizeBy: none
		sourceColumn: nomb_asent

		annotation SummarizationSetBy = Automatic

	column tipoCenCom
		dataType: string
		lineageTag: 7a1165d9-412a-4784-943f-cb052e105cc5
		summarizeBy: none
		sourceColumn: tipoCenCom

		annotation SummarizationSetBy = Automatic

	column cod_postal
		dataType: string
		lineageTag: 5c121de4-4efd-4861-a555-c55120c37307
		summarizeBy: none
		sourceColumn: cod_postal

		annotation SummarizationSetBy = Automatic

	column cve_ent
		dataType: string
		isHidden
		lineageTag: 9d2ae582-61fb-46b0-bbb4-72f0724b6909
		summarizeBy: none
		sourceColumn: cve_ent

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

	column entidad
		dataType: string
		lineageTag: 277eaede-bbaf-4d11-9126-cdbe286432cc
		summarizeBy: none
		sourceColumn: entidad

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

	column cve_mun
		dataType: string
		isHidden
		lineageTag: e1bb6c4b-0878-48cb-b8f0-f17c5799328b
		summarizeBy: none
		sourceColumn: cve_mun

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

	column municipio
		dataType: string
		lineageTag: d64e8e2c-c1aa-4116-999e-3cd7745ba5e3
		summarizeBy: none
		sourceColumn: municipio

		annotation SummarizationSetBy = Automatic

	column cve_loc
		dataType: string
		lineageTag: 810351d9-4398-4700-97fc-aa2dc4a51f2b
		summarizeBy: none
		sourceColumn: cve_loc

		annotation SummarizationSetBy = Automatic

	column localidad
		dataType: string
		lineageTag: aa062541-78d5-4e78-80f0-b4cb76316b11
		summarizeBy: none
		sourceColumn: localidad

		annotation SummarizationSetBy = Automatic

	column ageb
		dataType: string
		lineageTag: fb62dfe8-9605-48ff-9fd5-52af54dfae39
		summarizeBy: none
		sourceColumn: ageb

		annotation SummarizationSetBy = Automatic

	column manzana
		dataType: string
		lineageTag: 38aabecf-8c5a-4e1b-888a-b007120a1a43
		summarizeBy: none
		sourceColumn: manzana

		annotation SummarizationSetBy = Automatic

	column latitud
		dataType: double
		formatString: 0.00000000
		lineageTag: 61729e6b-c2a4-4617-9087-507b5366dd6e
		summarizeBy: sum
		sourceColumn: latitud

		annotation SummarizationSetBy = Automatic

	column longitud
		dataType: double
		formatString: 0.00000000
		lineageTag: d6b1e076-2842-4098-8f06-9cc1f3af0432
		summarizeBy: sum
		sourceColumn: longitud

		annotation SummarizationSetBy = Automatic

	column fecha_alta
		dataType: string
		isHidden
		lineageTag: 9b847259-0d5b-45bb-815a-7c39a8f5e739
		summarizeBy: none
		sourceColumn: fecha_alta

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

	column sector_codigo
		dataType: string
		lineageTag: 5b094a73-d952-40bd-bcf1-a0acb41acbda
		summarizeBy: none
		sourceColumn: sector_codigo

		annotation SummarizationSetBy = Automatic

	column sector_nombre
		dataType: string
		lineageTag: dded6977-13d2-4c3a-aa35-4ffd391bd88b
		summarizeBy: none
		sourceColumn: sector_nombre

		annotation SummarizationSetBy = Automatic

	column CVEGEO
		dataType: string
		lineageTag: a798d12e-1961-479c-8cb0-94cb658df0b3
		summarizeBy: none
		sourceColumn: CVEGEO

		annotation SummarizationSetBy = Automatic

	column CVEGEO_AGEB
		dataType: string
		lineageTag: 6bf8d3d4-d572-407b-8b0a-8a6ea1dc66d5
		summarizeBy: none
		sourceColumn: CVEGEO_AGEB

		annotation SummarizationSetBy = Automatic

	column cve_ent_key
		dataType: string
		lineageTag: d8240cec-970e-4b92-af01-c9c112058536
		summarizeBy: none
		sourceColumn: cve_ent_key

		annotation SummarizationSetBy = Automatic

	column cve_mun_key
		dataType: string
		lineageTag: 7ad2f4d7-33f1-4609-92d0-ee2b44d9d1f4
		summarizeBy: none
		sourceColumn: cve_mun_key

		annotation SummarizationSetBy = Automatic

	column cve_loc_key
		dataType: string
		lineageTag: 25a442fe-f1fa-4414-aaed-92b650dddf77
		summarizeBy: none
		sourceColumn: cve_loc_key

		annotation SummarizationSetBy = Automatic

	column manzana_key
		dataType: string
		lineageTag: 18369764-7cd5-4da2-9971-ab5d3160bf05
		summarizeBy: none
		sourceColumn: manzana_key

		annotation SummarizationSetBy = Automatic

	column cve_mun_completa
		dataType: string
		lineageTag: b802fabb-f123-4444-9f5d-117269b9e465
		summarizeBy: none
		sourceColumn: cve_mun_completa

		annotation SummarizationSetBy = Automatic

	partition FACTDENUE2025 = m
		mode: import
		source = ```
				let
				    Source = Sql.Database("qihyhmenysou5otulys7x473hm-wmsh36vm2hsepif26nl54mytlu.datawarehouse.fabric.microsoft.com", "lh_lokus_denue"),
				    dbo_denue_empresas_mexico_final = Source{[Schema="dbo",Item="denue_empresas_mexico_final"]}[Data],
				    #"Removed Columns" = Table.RemoveColumns(dbo_denue_empresas_mexico_final,{"tipo_vial", "nom_vial", "tipo_v_e_1", "nom_v_e_1", "tipo_v_e_2", "nom_v_e_2", "tipo_v_e_3", "nom_v_e_3", "numero_ext", "letra_ext", "edificio", "edificio_e", "numero_int", "letra_int", "archivo_origen", "nom_CenCom", "num_local", "telefono", "correoelec", "www", "tipoUniEco", "clee"}),
				    #"Added Custom" = Table.AddColumn(#"Removed Columns", "CVEGEO", each Text.PadStart(Text.From([cve_ent]), 2, "0") & 
				  Text.PadStart(Text.From([cve_mun]), 3, "0") & 
				  Text.PadStart(Text.From([cve_loc]), 4, "0") & 
				  [ageb] & 
				  Text.PadStart(Text.From([manzana]), 3, "0")),
				    #"Added Custom1" = Table.AddColumn(#"Added Custom", "CVEGEO_AGEB", each Text.PadStart(Text.From([cve_ent]), 2, "0") & 
				  Text.PadStart(Text.From([cve_mun]), 3, "0") & 
				  Text.PadStart(Text.From([cve_loc]), 4, "0") & 
				  [ageb]),
				    #"Changed Type" = Table.TransformColumnTypes(#"Added Custom1",{{"CVEGEO", type text}, {"CVEGEO_AGEB", type text}}),
				    #"Added Custom2" = Table.AddColumn(#"Changed Type", "cve_ent_key", each Text.PadStart(Text.From([cve_ent]), 2, "0")),
				    #"Added Custom3" = Table.AddColumn(#"Added Custom2", "cve_mun_key", each Text.PadStart(Text.From([cve_mun]), 3, "0")),
				    #"Added Custom4" = Table.AddColumn(#"Added Custom3", "cve_loc_key", each Text.PadStart(Text.From([cve_loc]), 4, "0")),
				    #"Added Custom5" = Table.AddColumn(#"Added Custom4", "manzana_key", each Text.PadStart(Text.From([manzana]), 3, "0")),
				    #"Added Custom6" = Table.AddColumn(#"Added Custom5", "cve_mun_completa", each [cve_ent_key] & [cve_mun_key]),
				    #"Changed Type1" = Table.TransformColumnTypes(#"Added Custom6",{{"cve_mun_completa", type text}, {"manzana_key", type text}, {"cve_loc_key", type text}, {"cve_mun_key", type text}, {"cve_ent_key", type text}})
				in
				    #"Changed Type1"
				```

	annotation PBI_NavigationStepName = Navigation

	annotation PBI_ResultType = Table

