table FECHA
	lineageTag: de6e32e9-b7bc-4986-b173-c8485a9f1009

	column fecha_alta
		dataType: string
		lineageTag: 85bafd00-3ee0-4d01-9dee-bdc3583b7ed3
		summarizeBy: none
		sourceColumn: fecha_alta

		annotation SummarizationSetBy = Automatic

	column AÑO
		dataType: int64
		formatString: 0
		lineageTag: 4f019633-cd45-4a82-9d29-654ad3561d9c
		summarizeBy: none
		sourceColumn: AÑO

		annotation SummarizationSetBy = Automatic

	column MES
		dataType: int64
		formatString: 0
		lineageTag: 29e54a52-c6df-4fd4-b72b-300feb53f465
		summarizeBy: none
		sourceColumn: MES

		annotation SummarizationSetBy = Automatic

	column TRIMESTRE
		dataType: string
		lineageTag: d51c4b4d-06fc-4817-bd06-58d8de392b21
		summarizeBy: none
		sourceColumn: TRIMESTRE

		annotation SummarizationSetBy = Automatic

	column NOMBRE_MES
		dataType: string
		lineageTag: e7ab20ad-7954-42bb-b78c-f92d5c1882dd
		summarizeBy: none
		sourceColumn: NOMBRE_MES

		annotation SummarizationSetBy = Automatic

	hierarchy Tiempo
		lineageTag: 2c71e82c-fbd5-4477-8196-16867fbd22fa

		level AÑO
			lineageTag: 5f1f5a7f-64b9-40bb-beed-679cb0364c40
			column: AÑO

		level TRIMESTRE
			lineageTag: 0bdd444f-d2dc-4ccf-9a4c-7ac0b44e075c
			column: TRIMESTRE

		level NOMBRE_MES
			lineageTag: 381b4c1d-1336-4195-bda8-a45289c232d6
			column: NOMBRE_MES

	partition FECHA = m
		mode: import
		source =
				let
				    Source = Sql.Database("qihyhmenysou5otulys7x473hm-wmsh36vm2hsepif26nl54mytlu.datawarehouse.fabric.microsoft.com", "lh_lokus_denue"),
				    dbo_denue_empresas_mexico_final = Source{[Schema="dbo",Item="denue_empresas_mexico_final"]}[Data],
				    #"Removed Columns" = Table.RemoveColumns(dbo_denue_empresas_mexico_final,{"tipo_vial", "nom_vial", "tipo_v_e_1", "nom_v_e_1", "tipo_v_e_2", "nom_v_e_2", "tipo_v_e_3", "nom_v_e_3", "numero_ext", "letra_ext", "edificio", "edificio_e", "numero_int", "letra_int", "archivo_origen", "nom_CenCom", "num_local", "telefono", "correoelec", "www", "tipoUniEco", "clee", "nom_estab", "raz_social", "codigo_act", "nombre_act", "per_ocu", "tipo_asent", "nomb_asent", "tipoCenCom", "cod_postal", "cve_ent", "entidad", "cve_mun", "municipio", "cve_loc", "localidad", "ageb", "manzana", "latitud", "longitud", "sector_codigo", "sector_nombre"}),
				    #"Added Custom" = Table.AddColumn(#"Removed Columns", "Personalizado", each Date.Year(Date.FromText([fecha_alta] & "-01"))),
				    #"Renamed Columns" = Table.RenameColumns(#"Added Custom",{{"Personalizado", "AÑO"}}),
				    #"Added Custom1" = Table.AddColumn(#"Renamed Columns", "Personalizado", each Date.Month(Date.FromText([fecha_alta] & "-01"))),
				    #"Renamed Columns1" = Table.RenameColumns(#"Added Custom1",{{"Personalizado", "MES"}}),
				    #"Added Custom2" = Table.AddColumn(#"Renamed Columns1", "Personalizado", each "Q" & Text.From(Number.RoundUp(Date.Month(Date.FromText([fecha_alta] & "-01"))/3))),
				    #"Renamed Columns2" = Table.RenameColumns(#"Added Custom2",{{"Personalizado", "TRIMESTRE"}}),
				    #"Added Custom3" = Table.AddColumn(#"Renamed Columns2", "Personalizado", each Date.MonthName(Date.FromText([fecha_alta] & "-01"), "es")),
				    #"Renamed Columns3" = Table.RenameColumns(#"Added Custom3",{{"Personalizado", "NOMBRE_MES"}}),
				    #"Removed Columns1" = Table.RemoveColumns(#"Renamed Columns3",{"id"}),
				    #"Changed Type" = Table.TransformColumnTypes(#"Removed Columns1",{{"NOMBRE_MES", type text}, {"TRIMESTRE", type text}, {"MES", Int64.Type}, {"AÑO", Int64.Type}}),
				    #"Removed Duplicates" = Table.Distinct(#"Changed Type", {"fecha_alta"})
				in
				    #"Removed Duplicates"

	annotation PBI_NavigationStepName = Navigation

	annotation PBI_ResultType = Table

