table resumen_estatal_informe_integral_2024
	lineageTag: 60b78389-41ad-40c8-acab-7a00b8357687

	column codigo_entidad
		dataType: string
		lineageTag: 8fba9886-1726-4cee-a04a-3e77db467b8b
		summarizeBy: none
		sourceColumn: codigo_entidad

		annotation SummarizationSetBy = Automatic

	column nombre_entidad
		dataType: string
		lineageTag: d965d987-d903-4043-a787-ee9029c21a52
		dataCategory: StateOrProvince
		summarizeBy: none
		sourceColumn: nombre_entidad

		annotation SummarizationSetBy = Automatic

	column total_hogares_reales
		dataType: int64
		formatString: 0
		lineageTag: 249ba4eb-e49f-4b72-8f4d-20d6fa39a911
		summarizeBy: sum
		sourceColumn: total_hogares_reales

		annotation SummarizationSetBy = Automatic

	column poblacion_total
		dataType: double
		lineageTag: 50f047e3-59fe-47b9-8981-e2ab363f2873
		summarizeBy: sum
		sourceColumn: poblacion_total

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column municipios_representados
		dataType: int64
		formatString: 0
		lineageTag: 47f38d00-0aa5-4cbb-8cc1-e795ba1b1ef2
		summarizeBy: sum
		sourceColumn: municipios_representados

		annotation SummarizationSetBy = Automatic

	column promedio_integrantes_hogar
		dataType: double
		lineageTag: 403b2b96-96cd-43b2-a7d4-3d0b8de0f58a
		summarizeBy: sum
		sourceColumn: promedio_integrantes_hogar

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column poblacion_hombres
		dataType: double
		lineageTag: 35ab66a5-5172-462d-8b65-8859545b48db
		summarizeBy: sum
		sourceColumn: poblacion_hombres

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column poblacion_mujeres
		dataType: double
		lineageTag: 0fa6e585-7bc5-49b0-82c4-15c430fcf3e5
		summarizeBy: sum
		sourceColumn: poblacion_mujeres

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column ingreso_promedio
		dataType: double
		lineageTag: 59a1aef4-75df-40f7-a6dd-572d3ae52d8b
		summarizeBy: sum
		sourceColumn: ingreso_promedio

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column gasto_promedio
		dataType: double
		lineageTag: 5995efb7-273a-4ed7-8a8b-e8ec7736772b
		summarizeBy: sum
		sourceColumn: gasto_promedio

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column ahorro_promedio
		dataType: double
		lineageTag: 203ce875-50eb-4a26-884c-5b177d5bea4c
		summarizeBy: sum
		sourceColumn: ahorro_promedio

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column propension_consumo_pct
		dataType: double
		lineageTag: dec20284-f661-4630-9574-436fc8b6326c
		summarizeBy: sum
		sourceColumn: propension_consumo_pct

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column ranking_ingreso
		dataType: int64
		formatString: 0
		lineageTag: 786cc9da-cb83-4570-ab96-8627517eb10f
		summarizeBy: sum
		sourceColumn: ranking_ingreso

		annotation SummarizationSetBy = Automatic

	column indice_ingreso_vs_nacional
		dataType: double
		lineageTag: 796a02e8-9e5e-4bae-80c6-2eab7328bcb3
		summarizeBy: sum
		sourceColumn: indice_ingreso_vs_nacional

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column nivel_desarrollo_economico
		dataType: string
		lineageTag: f703f223-82b0-4859-8b14-85b986f68970
		summarizeBy: none
		sourceColumn: nivel_desarrollo_economico

		annotation SummarizationSetBy = Automatic

	column gasto_alimentos_promedio
		dataType: double
		lineageTag: 5f6d477c-c952-443c-8d8b-11bcf7e8ee69
		summarizeBy: sum
		sourceColumn: gasto_alimentos_promedio

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column pct_gasto_alimentos
		dataType: double
		lineageTag: 985ef718-d6f8-4e76-9bc1-1fb6e745b6ab
		summarizeBy: sum
		sourceColumn: pct_gasto_alimentos

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column gasto_vivienda_promedio
		dataType: double
		lineageTag: ee30b50a-ea3f-4968-95eb-2afb7a11701d
		summarizeBy: sum
		sourceColumn: gasto_vivienda_promedio

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column gasto_transporte_promedio
		dataType: double
		lineageTag: 21475154-29eb-487e-8b3e-73465d5db5fb
		summarizeBy: sum
		sourceColumn: gasto_transporte_promedio

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column perfil_consumo_alimentario
		dataType: string
		lineageTag: 59842a4c-77c1-4ab7-82c4-1573244e9a75
		summarizeBy: none
		sourceColumn: perfil_consumo_alimentario

		annotation SummarizationSetBy = Automatic

	column entidad
		dataType: string
		lineageTag: 9700a73b-bd9f-4b31-9e31-60a572e43ffe
		summarizeBy: none
		sourceColumn: entidad

		annotation SummarizationSetBy = Automatic

	column ingreso_total_estatal
		dataType: double
		lineageTag: 06e03a8c-80b1-4eaa-b517-763fad49364f
		summarizeBy: sum
		sourceColumn: ingreso_total_estatal

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column ingreso_trabajo_promedio
		dataType: double
		lineageTag: c380e18d-3d61-42e3-9653-893f5400786d
		summarizeBy: sum
		sourceColumn: ingreso_trabajo_promedio

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column ingreso_mediano
		dataType: double
		lineageTag: f1e08366-8415-4301-ac03-1034ea7e7f5c
		summarizeBy: sum
		sourceColumn: ingreso_mediano

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column ingreso_desviacion_std
		dataType: double
		lineageTag: 98409e83-097a-4654-ac6d-34ebb4c7503b
		summarizeBy: sum
		sourceColumn: ingreso_desviacion_std

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column hogares_con_ahorro
		dataType: int64
		formatString: 0
		lineageTag: 6a4b8fe0-7359-47c3-9e87-b8597bd49ce8
		summarizeBy: sum
		sourceColumn: hogares_con_ahorro

		annotation SummarizationSetBy = Automatic

	column hogares_con_deficit
		dataType: int64
		formatString: 0
		lineageTag: 47d1ae00-1707-4867-836c-1a7069ca5d89
		summarizeBy: sum
		sourceColumn: hogares_con_deficit

		annotation SummarizationSetBy = Automatic

	column gasto_total_promedio
		dataType: double
		lineageTag: c29f2c8a-2907-430c-a089-e99c77436d46
		summarizeBy: sum
		sourceColumn: gasto_total_promedio

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column gasto_salud_promedio
		dataType: double
		lineageTag: d0402a12-abce-47e9-8e2c-491a0245c543
		summarizeBy: sum
		sourceColumn: gasto_salud_promedio

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column gasto_educacion_promedio
		dataType: double
		lineageTag: 07c960b2-acc4-4437-9208-f7b96a6878eb
		summarizeBy: sum
		sourceColumn: gasto_educacion_promedio

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column gasto_vestido_promedio
		dataType: double
		lineageTag: 5a850568-c03d-4da9-96d0-c815ce7752bf
		summarizeBy: sum
		sourceColumn: gasto_vestido_promedio

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column pct_gasto_vivienda
		dataType: double
		lineageTag: bc1e0c51-e12c-4af3-8684-f9b81437fef1
		summarizeBy: sum
		sourceColumn: pct_gasto_vivienda

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column pct_gasto_transporte
		dataType: double
		lineageTag: 67839682-5bee-4917-850b-38917a35ccbe
		summarizeBy: sum
		sourceColumn: pct_gasto_transporte

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column gasto_carnes_promedio
		dataType: double
		lineageTag: 7048e77e-4c9a-4ccb-8ee9-65e7122fa409
		summarizeBy: sum
		sourceColumn: gasto_carnes_promedio

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column gasto_cereales_promedio
		dataType: double
		lineageTag: 7499a53b-c761-4138-97e8-0a092d300f76
		summarizeBy: sum
		sourceColumn: gasto_cereales_promedio

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column gasto_verduras_promedio
		dataType: double
		lineageTag: 699a5135-f293-4ea5-ad46-fb947443dc02
		summarizeBy: sum
		sourceColumn: gasto_verduras_promedio

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column gasto_frutas_promedio
		dataType: double
		lineageTag: bc40c753-21f3-4e75-8137-9ce369123878
		summarizeBy: sum
		sourceColumn: gasto_frutas_promedio

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column diversidad_alimentaria_promedio
		dataType: double
		lineageTag: 13d2db34-9a4b-445a-b652-a4b9f8eb2b11
		summarizeBy: sum
		sourceColumn: diversidad_alimentaria_promedio

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column gasto_nutritivo_promedio
		dataType: double
		lineageTag: 1b00ec6b-94c2-4145-a391-9806ef416a6a
		summarizeBy: sum
		sourceColumn: gasto_nutritivo_promedio

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column pct_jefe_hombre
		dataType: double
		lineageTag: 4cc369ac-e5d1-47ec-a385-88fd69d686a3
		summarizeBy: sum
		sourceColumn: pct_jefe_hombre

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column pct_jefe_mujer
		dataType: double
		lineageTag: afb8100d-6f80-47cf-8f0b-e896199e0ed2
		summarizeBy: sum
		sourceColumn: pct_jefe_mujer

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column pct_poblacion_hombres
		dataType: double
		lineageTag: 3018c30b-fe2a-4512-82e7-6bf9ebf27b88
		summarizeBy: sum
		sourceColumn: pct_poblacion_hombres

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column pct_poblacion_mujeres
		dataType: double
		lineageTag: 933996ee-bfcb-4776-b197-a2a697a9e966
		summarizeBy: sum
		sourceColumn: pct_poblacion_mujeres

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column pct_hogares_nucleares
		dataType: double
		lineageTag: 78a180a2-5af6-4b09-8e0b-04c9207e14de
		summarizeBy: sum
		sourceColumn: pct_hogares_nucleares

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column pct_hogares_unipersonales
		dataType: double
		lineageTag: 6a792718-d04c-4cd0-8b5b-ccc325f833a7
		summarizeBy: sum
		sourceColumn: pct_hogares_unipersonales

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column pct_hogares_numerosos
		dataType: double
		lineageTag: 229c4d5b-53d4-4e4c-a95d-204aea28832b
		summarizeBy: sum
		sourceColumn: pct_hogares_numerosos

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column edad_promedio_jefe
		dataType: double
		lineageTag: 3797f9e0-72e4-44f4-b70a-7e845702fc89
		summarizeBy: sum
		sourceColumn: edad_promedio_jefe

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column gasto_vivienda_total_promedio
		dataType: double
		lineageTag: 70cb1a2b-40ba-4969-9c49-fb6caaa4d113
		summarizeBy: sum
		sourceColumn: gasto_vivienda_total_promedio

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column pct_ingreso_vivienda
		dataType: double
		lineageTag: 08aa7d38-53e4-4f8a-acc1-4a14c1afe9b3
		summarizeBy: sum
		sourceColumn: pct_ingreso_vivienda

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column gasto_agua_promedio
		dataType: double
		lineageTag: 795d9040-adcf-41c3-8f3b-9ac51b7aa641
		summarizeBy: sum
		sourceColumn: gasto_agua_promedio

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column gasto_energia_promedio
		dataType: double
		lineageTag: 326df491-a9d7-4701-a186-d3a0e5c1c390
		summarizeBy: sum
		sourceColumn: gasto_energia_promedio

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column gasto_educacion_total_promedio
		dataType: double
		lineageTag: 79552a10-bcdf-4f27-9e91-351de6d7ec34
		summarizeBy: sum
		sourceColumn: gasto_educacion_total_promedio

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column pct_ingreso_educacion
		dataType: double
		lineageTag: 414d13e8-f342-4550-8574-3e98777f8cbd
		summarizeBy: sum
		sourceColumn: pct_ingreso_educacion

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column pct_hogares_invierten_educacion
		dataType: double
		lineageTag: 0bfa1c07-f609-41f2-a991-227107572b0d
		summarizeBy: sum
		sourceColumn: pct_hogares_invierten_educacion

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column gasto_salud_total_promedio
		dataType: double
		lineageTag: 86202946-e334-4a2b-97d0-fdd6d5a718c7
		summarizeBy: sum
		sourceColumn: gasto_salud_total_promedio

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column pct_ingreso_salud
		dataType: double
		lineageTag: d0e81cfa-3994-40e5-96f4-70d410f2ea42
		summarizeBy: sum
		sourceColumn: pct_ingreso_salud

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column pct_hogares_gastan_salud
		dataType: double
		lineageTag: b927eef2-ff10-48bb-a9e1-10f2c698b934
		summarizeBy: sum
		sourceColumn: pct_hogares_gastan_salud

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column gasto_salud_per_capita
		dataType: double
		lineageTag: 4494e350-7933-410d-a444-5aecd4ddf3f2
		summarizeBy: sum
		sourceColumn: gasto_salud_per_capita

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column fecha_calculo
		dataType: dateTime
		formatString: General Date
		lineageTag: 9a51c12b-fe46-4c5b-b5dc-bfabf40bdc59
		summarizeBy: none
		sourceColumn: fecha_calculo

		annotation SummarizationSetBy = Automatic

	column fuente_datos
		dataType: string
		lineageTag: 1fc63715-035f-4ea1-8f00-db30ffb8f5c9
		summarizeBy: none
		sourceColumn: fuente_datos

		annotation SummarizationSetBy = Automatic

	column tipo_tabla
		dataType: string
		lineageTag: 0c5a4412-44d8-4089-b4b5-efd3536989aa
		summarizeBy: none
		sourceColumn: tipo_tabla

		annotation SummarizationSetBy = Automatic

	column registros_procesados
		dataType: int64
		formatString: 0
		lineageTag: 6def2e06-29c5-41ed-82a4-d720dcbedb5d
		summarizeBy: sum
		sourceColumn: registros_procesados

		annotation SummarizationSetBy = Automatic

	column ranking_poblacion
		dataType: int64
		formatString: 0
		lineageTag: c9f39014-8994-45c7-8f25-ca29c98d7de7
		summarizeBy: sum
		sourceColumn: ranking_poblacion

		annotation SummarizationSetBy = Automatic

	column ranking_gasto_alimentos
		dataType: int64
		formatString: 0
		lineageTag: 0a4b0ee3-49ce-4d66-a3db-256745dc40ef
		summarizeBy: sum
		sourceColumn: ranking_gasto_alimentos

		annotation SummarizationSetBy = Automatic

	column ranking_educacion
		dataType: int64
		formatString: 0
		lineageTag: c754d6f5-7c64-4362-bd03-9019ae96bde3
		summarizeBy: sum
		sourceColumn: ranking_educacion

		annotation SummarizationSetBy = Automatic

	column ranking_salud
		dataType: int64
		formatString: 0
		lineageTag: 09545591-e433-4372-b57f-c4927e34822a
		summarizeBy: sum
		sourceColumn: ranking_salud

		annotation SummarizationSetBy = Automatic

	column indice_gasto_alimentos_vs_nacional
		dataType: double
		lineageTag: 8f6a7b06-fd3a-4058-9edf-ad207d6c9907
		summarizeBy: sum
		sourceColumn: indice_gasto_alimentos_vs_nacional

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column indice_educacion_vs_nacional
		dataType: double
		lineageTag: 0287e908-3745-4fbc-aa3f-895933ac99bd
		summarizeBy: sum
		sourceColumn: indice_educacion_vs_nacional

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column indice_salud_vs_nacional
		dataType: double
		lineageTag: fadb95bc-6280-4706-afd8-7ecb06fe7144
		summarizeBy: sum
		sourceColumn: indice_salud_vs_nacional

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	partition resumen_estatal_informe_integral_2024 = m
		mode: import
		source =
				let
				    Source = Sql.Database("qihyhmenysou5otulys7x473hm-wmsh36vm2hsepif26nl54mytlu.datawarehouse.fabric.microsoft.com", "lh_lokus_enigh_2024"),
				    dbo_resumen_estatal_informe_integral_2024 = Source{[Schema="dbo",Item="resumen_estatal_informe_integral_2024"]}[Data],
				    #"Replaced Value" = Table.ReplaceValue(dbo_resumen_estatal_informe_integral_2024,"México","Estado de México",Replacer.ReplaceText,{"nombre_entidad"}),
				    #"Replaced Value1" = Table.ReplaceValue(#"Replaced Value","Ciudad de Estado de México","Ciudad de México",Replacer.ReplaceText,{"nombre_entidad"})
				in
				    #"Replaced Value1"

	annotation PBI_NavigationStepName = Navigation

	annotation PBI_ResultType = Table

