table Población
	lineageTag: 97b0195a-0e2c-468e-a674-04ea2a927f3e

	measure 'Población Total_2020' = ```
			
			CALCULATE(
			    SUM(CensoHechos[Valor]),
			    CensoHechos[id_indicador] = 1002000001,
			    CensoHechos[Año] = 2020
			)
			
			```
		lineageTag: acbfcec9-5332-4cec-bd34-7be558c05674

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure 'Población Total Hombres_2020' = ```
			
			CALCULATE(
			    SUM(CensoHechos[Valor]),
			    CensoHechos[id_indicador] = 1002000002,
			    CensoHechos[Año] = 2020
			)
			
			```
		lineageTag: 3d06c095-3191-4989-be1b-9817702dadf0

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure 'Población Total Mujeres_2020' = ```
			
			CALCULATE(
			    SUM(CensoHechos[Valor]),
			    CensoHechos[id_indicador] = 1002000003,
			    CensoHechos[Año] = 2020
			)
			
			```
		lineageTag: 34bbcfe1-ec05-410b-8f44-10c408aa21dd

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure 'Edad Mediana_2020' = ```
			
			CALCULATE(
			    SUM(CensoHechos[Valor]),
			    CensoHechos[id_indicador] = 1002000010,
			    CensoHechos[Año] = 2020
			)
			
			```
		formatString: 0
		lineageTag: f1dc026a-d992-4ac6-b640-4bc2268afef9

		annotation PBI_FormatHint = {"isDecimal":true}

	measure 'Relación Hombres Mujeres_2020' = ```
			
			CALCULATE(
			    SUM(CensoHechos[Valor]),
			    CensoHechos[id_indicador] = 1002000024,
			    CensoHechos[Año] = 2020
			)
			
			```
		lineageTag: 6e4835e3-32a9-4909-8807-980cd1dced8f

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure '% Relación Dependencia_2020' = ```
			
			CALCULATE(
			    SUM(CensoHechos[Valor]),
			    CensoHechos[id_indicador] = 1002000127,
			    CensoHechos[Año] = 2020
			)
			
			```
		lineageTag: c3ecc7f9-c33d-4a85-bf57-3e8d228b2b0e

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure 'Indice Envejecimiento_2020' = ```
			
			CALCULATE(
			    SUM(CensoHechos[Valor]),
			    CensoHechos[id_indicador] = 6200240407,
			    CensoHechos[Año] = 2020
			)
			
			```
		lineageTag: 7a04444b-7247-4158-9392-48c66e58975a

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure 'Densidad Poblacion_2020' = ```
			
			CALCULATE(
			    SUM(CensoHechos[Valor]),
			    CensoHechos[id_indicador] = 3105001001,
			    CensoHechos[Año] = 2020
			)
			
			```
		lineageTag: 16c89f7b-d3a6-45dd-8821-13b0058cb37a

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure '% Población Localidades Menos_2500_2020' = ```
			
			CALCULATE(
			    SUM(CensoHechos[Valor]),
			    CensoHechos[id_indicador] = 3105004001,
			    CensoHechos[Año] = 2020
			)
			
			```
		lineageTag: fcc9f55c-df76-4dc1-b0d9-4f7439116a72

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure 'Población Total' = ```
			
			CALCULATE(
			    SUM(CensoHechos[Valor]),
			    CensoHechos[id_indicador] = 1002000001
			)
			
			```
		lineageTag: e6234460-0a95-4463-a8a8-c946ca5f2b2d

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure 'Población Total Hombres' = ```
			
			CALCULATE(
			    SUM(CensoHechos[Valor]),
			    CensoHechos[id_indicador] = 1002000002
			)
			
			```
		lineageTag: 31ad1cf9-92dc-4950-8df7-0cd594f9ffbe

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure 'Población Total Mujeres' = ```
			
			CALCULATE(
			    SUM(CensoHechos[Valor]),
			    CensoHechos[id_indicador] = 1002000003
			)
			
			```
		lineageTag: 0407475a-cd6f-436f-b553-ac4021694ae4

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure 'Edad Mediana' = ```
			
			CALCULATE(
			    SUM(CensoHechos[Valor]),
			    CensoHechos[id_indicador] = 1002000010
			)
			
			```
		lineageTag: c2b27928-84b4-44cf-b96c-01ca9391c38f

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	partition Población = m
		mode: import
		source =
				let
				    Origen = Table.FromRows(Json.Document(Binary.Decompress(Binary.FromText("i44FAA==", BinaryEncoding.Base64), Compression.Deflate)), let _t = ((type nullable text) meta [Serialized.Text = true]) in type table [Columna1 = _t]),
				    #"Tipo cambiado" = Table.TransformColumnTypes(Origen,{{"Columna1", type text}}),
				    #"Columnas quitadas" = Table.RemoveColumns(#"Tipo cambiado",{"Columna1"})
				in
				    #"Columnas quitadas"

	annotation PBI_ResultType = Table

