CREATE TABLE [dbo].[DimProduct] (

	[ProductKey] bigint NULL, 
	[ProductAlternateKey] varchar(8000) NULL, 
	[ProductSubcategoryKey] varchar(8000) NULL, 
	[WeightUnitMeasureCode] varchar(8000) NULL, 
	[SizeUnitMeasureCode] varchar(8000) NULL, 
	[EnglishProductName] varchar(8000) NULL, 
	[StandardCost] varchar(8000) NULL, 
	[FinishedGoodsFlag] bigint NULL, 
	[Color] varchar(8000) NULL, 
	[SafetyStockLevel] bigint NULL, 
	[ReorderPoint] bigint NULL, 
	[ListPrice] varchar(8000) NULL, 
	[Size] varchar(8000) NULL, 
	[SizeRange] varchar(8000) NULL, 
	[DaysToManufacture] bigint NULL, 
	[ProductLine] varchar(8000) NULL, 
	[DealerPrice] varchar(8000) NULL, 
	[Class] varchar(8000) NULL, 
	[Style] varchar(8000) NULL, 
	[ModelName] varchar(8000) NULL, 
	[LargePhoto] varchar(8000) NULL, 
	[EnglishDescription] varchar(8000) NULL, 
	[FrenchDescription] varchar(8000) NULL, 
	[ChineseDescription] varchar(8000) NULL, 
	[ArabicDescription] varchar(8000) NULL, 
	[HebrewDescription] varchar(8000) NULL, 
	[ThaiDescription] varchar(8000) NULL, 
	[GermanDescription] varchar(8000) NULL, 
	[JapaneseDescription] varchar(8000) NULL, 
	[TurkishDescription] varchar(8000) NULL, 
	[StartDate] datetime2(6) NULL, 
	[EndDate] varchar(8000) NULL, 
	[Status] varchar(8000) NULL
);