table MEDIDAD
	lineageTag: 3d28cdf4-2896-4a21-aa00-153354e489c6

	measure Claves_Unicas_DIM = DISTINCTCOUNT(DIM_GEOGRAFIA[CLAVE_GEOGRAFIA])
		formatString: 0.000
		lineageTag: a003c756-de9b-46c4-9511-f86ea9121d35

	measure Filas_DIM_GEOGRAFIA = COUNTROWS(DIM_GEOGRAFIA)
		formatString: 0.000
		lineageTag: 364ae455-5cef-43f7-aab4-56bdf4c5fae0

	measure Claves_Unicas_FACT = DISTINCTCOUNT(FACT_CENSO[CLAVE_GEOGRAFIA])
		formatString: 0.0
		lineageTag: 3e55126a-4398-413a-af9c-cdab9f6589e3

	measure Filas_FACT_CENSO = COUNTROWS(FACT_CENSO)
		formatString: 0.0
		lineageTag: eb596918-b8fd-45ba-8bd2-3308319fc587

	measure Poblacion_Total = SUM(FACT_CENSO[POBTOT])
		formatString: 0
		lineageTag: 0522be43-8761-4036-acc0-7d3c2489026e

		annotation PBI_FormatHint = {"isDecimal":true}

	measure Total_Viviendas = ```
			SUM(FACT_CENSO[TVIVHAB]) 
			```
		formatString: 0
		lineageTag: 7520a944-b4dd-468c-9bff-ba805875bcb2

	measure Densidad_Promedio = DIVIDE([Poblacion_Total], [Total_Localidades])
		lineageTag: 0e5f1c46-43f1-456f-b5a3-5e06ddabe3cb

	measure Total_Localidades = DISTINCTCOUNT(FACT_CENSO[CLAVE_GEOGRAFIA])
		formatString: 0
		lineageTag: 2f899ced-ef27-4ba4-93ca-a16e3eafcfb0

	measure Porcentaje_Mujeres = DIVIDE(SUM(FACT_CENSO[POBFEM]), [Poblacion_Total]) * 100
		lineageTag: 885ffe67-f002-4e40-a6e5-7591c4c2b389

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure Indice_Masculinidad = DIVIDE(SUM(FACT_CENSO[POBMAS]), SUM(FACT_CENSO[POBFEM])) * 100
		lineageTag: 1e949885-a3fa-4c3e-83b5-7cc44906e9d8

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure Tasa_Analfabetismo = DIVIDE(SUM(FACT_CENSO[P15YM_AN]), SUM(FACT_CENSO[P_15YMAS])) * 100
		lineageTag: 2da0fd81-b1a6-450a-91a2-4f7d730ba4bb

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure Servicios_Completos =
			
			VAR Elec = DIVIDE(SUM(FACT_CENSO[VPH_C_ELEC]), SUM(FACT_CENSO[TVIVHAB]), 0)
			VAR Agua = DIVIDE(SUM(FACT_CENSO[VPH_AGUADV]), SUM(FACT_CENSO[TVIVHAB]), 0)
			VAR Dren = DIVIDE(SUM(FACT_CENSO[VPH_DRENAJ]), SUM(FACT_CENSO[TVIVHAB]), 0)
			RETURN (Elec + Agua + Dren) / 3 * 100
		lineageTag: b5d608c1-ffdb-406b-a51c-b5e0dc8295c3

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure Brecha_Digital = 100 - [Penetracion_Internet]
		lineageTag: 62185851-b8da-429b-ad8e-f9bb6a8fbd6b

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure Escolaridad_Promedio = AVERAGE(FACT_CENSO[GRAPROES])
		lineageTag: c057a276-43e0-4d57-8311-a84ec021feea

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure IDH_Municipal =
			
			VAR EducacionIndex = DIVIDE([Escolaridad_Promedio], 15, 0) // Normalizar a 15 años max
			VAR SaludIndex = DIVIDE([Servicios_Completos], 100, 0) // Ya está en %
			VAR IngresoIndex = DIVIDE([Penetracion_Internet], 100, 0) // Proxy de ingresos
			RETURN (EducacionIndex + SaludIndex + IngresoIndex) / 3
		lineageTag: adeb4be6-0660-4283-b082-4f8db09c4f74

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure Vulnerabilidad_Social =
			
			VAR AnalfabetismoWeight = [Tasa_Analfabetismo] * 0.30
			VAR PobrezaWeight = (100 - [Servicios_Completos]) * 0.40
			VAR BrechaDigitalWeight = [Brecha_Digital] * 0.30
			RETURN AnalfabetismoWeight + PobrezaWeight + BrechaDigitalWeight
		lineageTag: 68c1c728-43d7-4847-801c-e1f2be0a82e0

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure 'Índice de Equidad de GéneroEquidad_Genero' =
			
			100 - ABS([Porcentaje_Mujeres] - 50)
		lineageTag: b83a4dde-79b2-4685-ae78-5f08aa79c8db

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure Ranking_Desarrollo =
			
			RANKX(
			    ALL(DIM_GEOGRAFIA[NOM_ENT]),
			    [IDH_Municipal],
			    ,DESC,DENSE
			)
		formatString: 0
		lineageTag: a10b42e8-913d-46e6-8144-a6ced1a0a6b8

	measure Percentil_Desarrollo =
			
			VAR CurrentIDH = [IDH_Municipal]
			VAR TotalEntidades = COUNTROWS(ALL(DIM_GEOGRAFIA[NOM_ENT]))
			VAR Ranking = [Ranking_Desarrollo]
			RETURN ROUND((TotalEntidades - Ranking + 1) / TotalEntidades * 100, 0)
		lineageTag: 5d741c7d-d127-4b5f-82e1-98b3b1c235da

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure Brecha_vs_Nacional =
			
			VAR PromedioNacional = CALCULATE([IDH_Municipal], ALL(DIM_GEOGRAFIA))
			VAR ValorLocal = [IDH_Municipal]
			RETURN ValorLocal - PromedioNacional
		lineageTag: d8102a20-67a7-4950-81e3-81b6df22733d

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure Concentracion_Urbana = ```
			
			VAR PobUrbana = CALCULATE([Poblacion_Total], 
			    DIM_GEOGRAFIA[TIPO_LOCALIDAD] IN {"Urbana_Grande", "Urbana_Media"})
			VAR PobTotal = [Poblacion_Total]
			RETURN DIVIDE(PobUrbana, PobTotal, 0) * 100
			```
		lineageTag: 6103d7ca-4c28-4ca0-8095-f9afd6555861

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure Indice_Dispersion =
			
			VAR LocalidadesRurales = CALCULATE(COUNTROWS(DIM_GEOGRAFIA),
			    DIM_GEOGRAFIA[TIPO_LOCALIDAD] = "Rural")
			VAR TotalLocalidades = COUNTROWS(DIM_GEOGRAFIA)
			RETURN DIVIDE(LocalidadesRurales, TotalLocalidades, 0) * 100
		lineageTag: 89196533-a24a-4447-9a1c-441948e0a92e

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure Crecimiento_Estimado =
			
			VAR PoblacionJoven = SUM(FACT_CENSO[POB0_14]) + SUM(FACT_CENSO[POB15_64])
			VAR PoblacionMayor = SUM(FACT_CENSO[POB65_MAS])
			VAR PoblacionTotal = [Poblacion_Total]
			VAR JovenesAdultos = DIVIDE(PoblacionJoven, PoblacionTotal, 0)
			VAR FactorEconomico = DIVIDE([Penetracion_Internet], 100, 0)
			RETURN (JovenesAdultos * 0.7 + FactorEconomico * 0.3) * 2
		lineageTag: ffb9ba13-8f06-49b9-9a5b-7a651d6b2bdd

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure Poblacion_Adultos_Mayores = SUM(FACT_CENSO[POB65_MAS])
		formatString: 0
		lineageTag: 512072dd-e9f0-401e-ac55-5836dcbbc6a8

	measure Poblacion_Adultos_Mayores_60 = SUM(FACT_CENSO[P_60YMAS])
		formatString: 0
		lineageTag: 740121eb-e499-4fe3-b847-f3132415ce43

	measure Proyeccion_2030 =
			
			[Poblacion_Total] * POWER(0.98, 10)
		lineageTag: 95182f98-8cbc-4186-8800-a8157586d96b

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure Indice_Envejecimiento =
			
			DIVIDE(SUM(FACT_CENSO[POB65_MAS]), SUM(FACT_CENSO[POB0_14]), 0) * 100
		lineageTag: b7418841-a5d5-4612-8a1f-a32835456706

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure Bono_Demografico =
			
			VAR PoblacionProductiva = SUM(FACT_CENSO[POB15_64])
			VAR PoblacionDependiente = SUM(FACT_CENSO[POB0_14]) + SUM(FACT_CENSO[POB65_MAS])
			RETURN DIVIDE(PoblacionProductiva, PoblacionDependiente, 0) * 100
		lineageTag: 33f28288-3440-4a83-9c26-a04483f61295

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure Meta_ODS_Educacion =
			
			IF([Tasa_Analfabetismo] <= 2, "✅ Cumplida", "❌ Pendiente")
		lineageTag: 7a1990dc-9288-4f8a-bb8d-bfe33356626e

	measure Alert_Desarrollo = ```
			
			IF([Vulnerabilidad_Social] > 70, "🚨 CRÍTICO", 
			   IF([Vulnerabilidad_Social] > 50, "⚠️ ATENCIÓN", "✅ NORMAL"))
			```
		lineageTag: 4c5e451e-963a-4551-bfdd-7cf73558107a

	measure Potencial_Crecimiento =
			
			VAR FactorJoven = DIVIDE([Poblacion_Total] - [Poblacion_Adultos_Mayores], [Poblacion_Total])
			VAR FactorDigital = [Penetracion_Internet] / 100
			RETURN (FactorJoven * 0.6 + FactorDigital * 0.4) * 100
		lineageTag: f3cb1279-2e1c-4b89-b404-16f38df6a76f

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure Electricidad_Pct = DIVIDE(SUM(FACT_CENSO[VPH_C_ELEC]), SUM(FACT_CENSO[TVIVHAB])) * 100
		lineageTag: d9662617-31d6-42fe-8174-e1479a1e1d71

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure Agua_Pct = DIVIDE(SUM(FACT_CENSO[VPH_AGUADV]), SUM(FACT_CENSO[TVIVHAB])) * 100
		lineageTag: 251894c6-acbb-4108-9d26-07526b0a79ea

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure Drenaje_Pct = DIVIDE(SUM(FACT_CENSO[VPH_DRENAJ]), SUM(FACT_CENSO[TVIVHAB])) * 100
		lineageTag: af2ef593-9772-431c-8298-27281e53751c

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure POB_0_14 = SUM(FACT_CENSO[POB0_14])
		formatString: 0
		lineageTag: d1defea4-2e0e-4bd1-aad2-eb53859253f8

	measure POB_15_64 = ```
			SUM(FACT_CENSO[POB15_64])  
			```
		formatString: 0
		lineageTag: 9b50723a-cfc8-4eed-a379-46fc2664f109

	measure POB_65_MAS = SUM(FACT_CENSO[POB65_MAS])
		formatString: 0
		lineageTag: b7aa45d6-2821-4d54-9162-5afb310b7ec7

	measure Proyeccion_2030_IA = ```
			
			VAR PoblacionBase2020 = [Poblacion_Total]
			-- Tasas anuales AJUSTADAS para crecimiento positivo
			VAR TasaFecundidad = 1.008   -- +0.8% anual (más realista)
			VAR TasaMigracionExterna = 0.999  -- -0.1% anual (menos migración)
			VAR TasaEnvejecimientoMortalidad = 0.998  -- -0.2% anual (menos impacto)
			VAR TasaMigracionInterna = 1.002  -- +0.2% (igual)
			
			-- Cálculo de crecimiento anual neto 
			VAR CrecimientoAnualNeto = 
			    1 + 
			    (TasaFecundidad - 1) + 
			    (TasaMigracionExterna - 1) + 
			    (TasaEnvejecimientoMortalidad - 1) +
			    (TasaMigracionInterna - 1)
			
			VAR Proyeccion = 
			    PoblacionBase2020 * POWER(CrecimientoAnualNeto, 10)
			
			RETURN 
			    IF(Proyeccion < 0, 0, ROUND(Proyeccion, 0))
			```
		lineageTag: c35e9fb0-ce2e-4cef-b5c6-5569aa3e920f

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure Atractivo_Migratorio = ```
			
			VAR AtractividadEconomica = [Penetracion_Internet] * 0.4 + [Servicios_Completos] * 0.6
			VAR FactorExpulsion = [Vulnerabilidad_Social] / 100
			RETURN 
			    IF(AtractividadEconomica - (FactorExpulsion * 50) > 60, "🔥 ATRAE POBLACIÓN",
			    IF(AtractividadEconomica - (FactorExpulsion * 50) > 40, "📈 CRECIMIENTO ESTABLE",
			    IF(AtractividadEconomica - (FactorExpulsion * 50) > 20, "📉 PÉRDIDA MODERADA", "🚨 ÉXODO POBLACIONAL")))
			```
		lineageTag: db8cf04b-34dd-42db-a9f1-81b5df6121fe

	measure Años_Para_Cerrar_Brecha_Digital = ```
			
			VAR BrechaActual = [Brecha_Digital]
			VAR VelocidadCrecimiento = ([Escolaridad_Promedio] / 15) * 0.05 + 0.03
			RETURN 
			    IF(BrechaActual <= 10, "✅ YA CERRADA",
			    IF(VelocidadCrecimiento > 0, ROUNDUP(BrechaActual / (VelocidadCrecimiento * 100), 0),
			    "⚠️ SIN PROGRESO"))
			```
		lineageTag: 09d90e5e-cf6e-42c0-8733-c36a8a7edaf0

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure Municipio_Gemelo_Score =
			
			VAR CurrentPop = IF([Poblacion_Total] > 0, [Poblacion_Total], 1)
			VAR CurrentIDH = IF([IDH_Municipal] <> BLANK(), [IDH_Municipal], 0)
			VAR CurrentTech = IF([Penetracion_Internet] <> BLANK(), [Penetracion_Internet], 0)
			-- Esta medida funciona mejor como tabla calculada o en contexto de comparación
			VAR Similitud = 1 -- Placeholder - necesita contexto de comparación específico
			RETURN Similitud
		formatString: 0
		lineageTag: 500946c0-3b72-4c75-9ca6-e5499750cb04

	measure Competitividad_Score =
			
			VAR InfraestructuraWeight = [Servicios_Completos] * 0.25
			VAR CapitalHumanoWeight = ([Escolaridad_Promedio] / 15 * 100) * 0.30
			VAR TecnologiaWeight = [Penetracion_Internet] * 0.25
			VAR DemografiaWeight = ([Bono_Demografico] / 200 * 100) * 0.20
			RETURN InfraestructuraWeight + CapitalHumanoWeight + TecnologiaWeight + DemografiaWeight
		lineageTag: 62cd4abf-4993-4794-9002-3d682554ae1d

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure Potencial_Inversion = ```
			
			VAR DemografiaFactor = [Bono_Demografico] / 200 * 100
			VAR TecnologiaFactor = [Penetracion_Internet]
			VAR EducacionFactor = [Escolaridad_Promedio] / 15 * 100
			VAR InfraestructuraFactor = [Servicios_Completos]
			VAR Score = (DemografiaFactor * 0.3 + TecnologiaFactor * 0.3 + 
			             EducacionFactor * 0.2 + InfraestructuraFactor * 0.2)
			RETURN 
			    IF(Score >= 80, "🔥 INVERSIÓN PREMIUM",
			    IF(Score >= 65, "💎 ALTA OPORTUNIDAD", 
			    IF(Score >= 50, "📈 POTENCIAL MEDIO",
			    IF(Score >= 35, "⚠️ RIESGO MODERADO", "🚨 ALTO RIESGO"))))
			```
		lineageTag: b1123ac8-5642-4184-99a6-ab64e86252f6

	measure Alerta_Demografica_V2 = ```
			
			// 1. Cálculo gradual de riesgos (sin cortes abruptos)
			VAR RiesgoEnvejecimiento = MIN([Indice_Envejecimiento] * 0.4, 25)  // 60 → 24 pts
			VAR RiesgoMigracion = MIN([Vulnerabilidad_Social] * 0.46, 30)      // 65 → 30 pts
			VAR RiesgoDigital = MIN([Brecha_Digital] * 0.27, 20)               // 75 → 20 pts
			VAR RiesgoEducativo = MIN([Tasa_Analfabetismo] * 2.5, 25)          // 10% → 25 pts
			
			// 2. Suma total (máximo posible = 100)
			VAR RiesgoTotal = RiesgoEnvejecimiento + RiesgoMigracion + RiesgoDigital + RiesgoEducativo
			
			// 3. Clasificación con ajuste estadístico (opcional)
			VAR Percentil75 = 60  // Ejemplo: El 75% de las regiones tienen RiesgoTotal < 60
			VAR Percentil50 = 40
			VAR Percentil25 = 20
			
			// 4. Retorno con niveles de alerta
			RETURN 
			    SWITCH(
			        TRUE(),
			        RiesgoTotal >= Percentil75, "🚨 CRISIS INMINENTE",
			        RiesgoTotal >= Percentil50, "⚠️ ATENCIÓN URGENTE",
			        RiesgoTotal >= Percentil25, "🟡 MONITOREAR",
			        "✅ ESTABLE"
			    )
			```
		lineageTag: 799638e7-bb24-4f0d-9d73-665b8a84ec9c

	measure Prioridad_Intervencion = ```
			
			VAR VulnScore = IF([Vulnerabilidad_Social] <> BLANK(), [Vulnerabilidad_Social], 0)
			VAR ServiciosScore = IF([Servicios_Completos] <> BLANK(), [Servicios_Completos], 100)
			VAR BrechaScore = IF([Brecha_Digital] <> BLANK(), [Brecha_Digital], 0)
			VAR UrgenciaScore = (VulnScore * 0.4) + ((100 - ServiciosScore) * 0.3) + (BrechaScore * 0.3)
			VAR PobTotal = IF([Poblacion_Total] > 0, [Poblacion_Total], 1)
			VAR ImpactoScore = LOG(PobTotal, 10) * 10
			RETURN 
			    IF(UrgenciaScore >= 60 && ImpactoScore >= 40, "🔴 MÁXIMA PRIORIDAD",
			    IF(UrgenciaScore >= 45 && ImpactoScore >= 30, "🟠 ALTA PRIORIDAD",
			    IF(UrgenciaScore >= 30, "🟡 PRIORIDAD MEDIA", "🟢 BAJA PRIORIDAD")))
			```
		lineageTag: c9e99924-47f4-4e53-ac04-01204b725c30

	measure Hotspot_Crecimiento = ```
			
			VAR FactorJuventud = (100 - ([Poblacion_Adultos_Mayores] / [Poblacion_Total] * 100))
			VAR FactorConectividad = [Penetracion_Internet]
			VAR FactorEducacion = [Escolaridad_Promedio] * 10
			VAR Score = (FactorJuventud * 0.4 + FactorConectividad * 0.4 + FactorEducacion * 0.2)
			RETURN 
			    IF(Score >= 80, "🔥 HOTSPOT EXPLOSIVO",
			    IF(Score >= 65, "📈 ZONA EMERGENTE",
			    IF(Score >= 50, "🌱 POTENCIAL LATENTE", "😴 ZONA ESTABLE")))
			```
		lineageTag: 07feeb9d-5591-4870-bb79-143eb525fa72

	measure Sostenibilidad_Score =
			
			VAR EquilibrioEtario = 100 - ABS([Indice_Envejecimiento] - 35)
			VAR SostenibilidadEconomica = [Bono_Demografico] / 2
			VAR SostenibilidadAmbiental = [Servicios_Completos]
			RETURN (EquilibrioEtario * 0.4 + SostenibilidadEconomica * 0.3 + SostenibilidadAmbiental * 0.3)
		lineageTag: a5c34948-931b-44f5-a12d-0a8a40482064

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure Simulador_Inversion = ```
			
			VAR InversionEducacion = 0 -- Cambiar por parámetro si existe tabla Simulador
			VAR InversionTecnologia = 0 -- Cambiar por parámetro si existe tabla Simulador  
			VAR EscolaridadActual = IF([Escolaridad_Promedio] <> BLANK(), [Escolaridad_Promedio], 0)
			VAR TechActual = IF([Penetracion_Internet] <> BLANK(), [Penetracion_Internet], 0)
			VAR ServiciosActual = IF([Servicios_Completos] <> BLANK(), [Servicios_Completos], 0)
			VAR MejorGRAD = EscolaridadActual + (InversionEducacion / 1000)
			VAR MejorTECH = TechActual + (InversionTecnologia / 500)
			VAR NuevoIDH = (MejorGRAD/15 + MejorTECH/100 + ServiciosActual/100) / 3
			RETURN IF(NuevoIDH > 0, NuevoIDH, 0)
			```
		lineageTag: 9c53adcf-5d9c-48c1-ab6e-0a29875a943c

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure Tipo_Localidad_IA =
			
			IF([IDH_Municipal] >= 0.75 && [Penetracion_Internet] >= 70, "🚀 POLO DE DESARROLLO",
			IF([IDH_Municipal] >= 0.65 && [Penetracion_Internet] >= 60, "🏙️ URBANO DESARROLLADO",
			IF([Penetracion_Internet] >= 50, "💻 DIGITAL EMERGENTE",
			IF([IDH_Municipal] <= 0.45, "🆘 ALTA PRIORIDAD", "📈 EN TRANSICIÓN"))))
		lineageTag: 0500607e-b5d6-4ef6-b1e7-7af11ddf9b4d

	measure Alertas_Criticas =
			
			COUNTROWS(
			    FILTER(
			        VALUES(DIM_GEOGRAFIA[NOM_LOC]),
			        [Alerta_Demografica_V2] IN {"🚨 CRISIS INMINENTE", "⚠️ ATENCIÓN URGENTE"}
			    )
			)
		formatString: 0
		lineageTag: a514355b-e528-4939-81e2-022cb0c2dc13

	measure Numero_Polos =
			
			COUNTROWS(
			    FILTER(
			        VALUES(DIM_GEOGRAFIA[NOM_LOC]),
			        [Tipo_Localidad_IA] = "🚀 POLO DE DESARROLLO"
			    )
			)
		formatString: 0
		lineageTag: 685f9b14-0d1c-42e4-87b6-f0b5454f93a7

	measure Top_Inversion_Score =
			
			VAR TopScore = MAXX(ALL(DIM_GEOGRAFIA[NOM_LOC]), [Potencial_Inversion])
			RETURN TopScore
		lineageTag: faa829b5-e7ab-46a2-94f0-e2b2c6b6b4e0

	measure Penetracion_Internet = DIVIDE(SUM(FACT_CENSO[VPH_INTER]), SUM(FACT_CENSO[TVIVHAB])) * 100
		lineageTag: 6408ae5a-6043-46e5-8f67-21b8964a92df

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure Años_Bono_Demografico = ```
			
			VAR BonoActual = [Bono_Demografico]
			VAR PoblacionPEA = [POB_15_64]
			VAR PoblacionTotal = [Poblacion_Total]
			
			// Calculamos el ratio de dependencia demográfica
			VAR RatioDependencia = 
			    DIVIDE(
			        PoblacionTotal - PoblacionPEA,
			        PoblacionPEA,
			        0
			    ) * 100
			
			// Proyección más realista
			VAR AnosRestantesBono = 
			    IF(
			        RatioDependencia < 50,
			        (50 - RatioDependencia) * 0.5,
			        0
			    )
			
			RETURN 
			    ROUND(2020 + AnosRestantesBono, 0)
			```
		lineageTag: 3044c2d2-0ef4-4d51-96a6-85bbc13fcbfc

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure Recomendacion_IA =
			
			IF([Competitividad_Score] >= 80,
			    IF([Potencial_Crecimiento] >= 80, "💎 ÉLITE", "⭐ LÍDER ESTABLE"),
			    IF([Potencial_Crecimiento] >= 80, "🚀 DIAMANTE BRUTO", "📈 EMERGENTE")
			)
		lineageTag: 70093327-32b1-41df-a955-6d1bbb7d39c6

	measure Medida = COUNTROWS(FACT_CENSO)
		formatString: 0
		lineageTag: feff287e-c12b-4c67-aa66-ec35d8b820eb

	partition MEDIDAD = m
		mode: import
		source =
				let
				    Source = Table.FromRows(Json.Document(Binary.Decompress(Binary.FromText("i44FAA==", BinaryEncoding.Base64), Compression.Deflate)), let _t = ((type nullable text) meta [Serialized.Text = true]) in type table [Columna1 = _t]),
				    #"Removed Columns" = Table.RemoveColumns(Source,{"Columna1"})
				in
				    #"Removed Columns"

	annotation PBI_ResultType = Table

	annotation PBI_NavigationStepName = Navigation

