table 'Actividad Económica'
	lineageTag: 6de1b49e-0b38-4d80-93da-c8c79618341b

	measure PorcentajePoblacionEconomicamenteActiva = ```
			
			CALCULATE(
			    SUM(CensoHechos[Valor]),
			    CensoHechos[id_indicador] = 6207019030
			)
			
			```
		formatString: 0
		lineageTag: de655b21-2a9e-4df7-914a-e679232443a0

	measure PorcentajePoblacionNoEconomicamenteActiva = ```
			
			CALCULATE(
			    SUM(CensoHechos[Valor]),
			    CensoHechos[id_indicador] = 6207019035
			)
			
			```
		formatString: 0
		lineageTag: 97307337-d789-41c4-9cdb-836e87cad397

	measure PorcentajePoblacionEconomicamenteActivaOcupada = ```
			
			CALCULATE(
			    SUM(CensoHechos[Valor]),
			    CensoHechos[id_indicador] = 6207019039
			)
			
			```
		formatString: 0
		lineageTag: a7baad4f-08c2-434f-95a0-eb6ef5cb7461

	measure PoblacionLimitacionActividad = ```
			
			CALCULATE(
			    SUM(CensoHechos[Valor]),
			    CensoHechos[id_indicador] = 6200205271
			)
			
			```
		formatString: 0
		lineageTag: dfaf1a0e-bbb7-4267-b929-ff5361ae76a4

	measure PorcentajeEconomicamenteActivaFemenina = ```
			
			CALCULATE(
			    SUM(CensoHechos[Valor]),
			    CensoHechos[id_indicador] = 6207019040
			)
			
			```
		lineageTag: 2047b70c-a0d1-4ec5-8902-28fc3f2d17fe

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure PorcentajeEconomicamenteActivaMasculina = ```
			
			CALCULATE(
			    SUM(CensoHechos[Valor]),
			    CensoHechos[id_indicador] = 6207019043
			)
			
			```
		lineageTag: 8627f47b-88d8-462a-a1c1-8d757ba8e4e0

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure PorcentajeEconomicamenteActivaOcupadaFemenina = ```
			
			CALCULATE(
			    SUM(CensoHechos[Valor]),
			    CensoHechos[id_indicador] = 6207019054
			)
			
			```
		lineageTag: fe38822b-7eea-40a8-bfcf-866a23ccf658

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure PorcentajeEconomicamenteActivaOcupadaMasculina = ```
			
			CALCULATE(
			    SUM(CensoHechos[Valor]),
			    CensoHechos[id_indicador] = 6207019056
			)
			
			```
		lineageTag: 015ba9a3-6903-4cb3-8185-5e9fe6a11800

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure '% Activa Femenina' = ```
			
			CALCULATE(
			    SUM(CensoHechos[Valor]),
			    CensoHechos[id_indicador] = 6207019040,
			    CensoHechos[Año] = 2020
			)
			
			```
		lineageTag: 5cdffef0-bf75-4b36-b73a-a6f22aa5ab19

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure '% Activa Masculina' = ```
			
			CALCULATE(
			    SUM(CensoHechos[Valor]),
			    CensoHechos[id_indicador] = 6207019043,
			    CensoHechos[Año] = 2020
			)
			
			```
		lineageTag: a5d690c9-518d-4643-968a-68f377735e28

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure '% No Econ. Activa Estudia' = ```
			
			CALCULATE(
			    SUM(CensoHechos[Valor]),
			    CensoHechos[id_indicador] = 6207019047,
			    CensoHechos[Año] = 2020
			)
			
			```
		lineageTag: 0617ffdf-cc7a-4580-9ea2-35397362e8dd

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure '% No Econ. Activa Quehaceres' = ```
			
			CALCULATE(
			    SUM(CensoHechos[Valor]),
			    CensoHechos[id_indicador] = 6207019064,
			    CensoHechos[Año] = 2020
			)
			
			```
		lineageTag: 875fd7ff-69c6-4b62-a67a-16429035cb3b

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure '% No Econ. Activa Otras' = ```
			
			CALCULATE(
			    SUM(CensoHechos[Valor]),
			    CensoHechos[id_indicador] = 6207019065,
			    CensoHechos[Año] = 2020
			)
			
			```
		lineageTag: 7569ecc4-d8d2-4f8c-84ee-36b01cf90fec

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure '% No Econ. Activa No Especificada' = ```
			
			CALCULATE(
			    SUM(CensoHechos[Valor]),
			    CensoHechos[id_indicador] = 6207019059,
			    CensoHechos[Año] = 2020
			)
			
			```
		lineageTag: 31acfff4-40dd-46e0-9486-eaaf0901f50a

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure '% No Econ. Activa Pensionada' = ```
			
			CALCULATE(
			    SUM(CensoHechos[Valor]),
			    CensoHechos[id_indicador] = 6207019060,
			    CensoHechos[Año] = 2020
			)
			
			```
		lineageTag: e449d039-5f9b-475c-a602-a4abac127b75

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure '% No Econ. Activa Limitación Fisica' = ```
			
			CALCULATE(
			    SUM(CensoHechos[Valor]),
			    CensoHechos[id_indicador] = 6207019070,
			    CensoHechos[Año] = 2020
			)
			
			```
		lineageTag: 14e8b6e0-1408-4ec6-8a4b-94bf4189669b

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure PorcentajeAcumuladoNoEconActiva2020 = ```
			
			[% No Econ. Activa Estudia] +
			[% No Econ. Activa Quehaceres] +
			[% No Econ. Activa Otras] +
			[% No Econ. Activa Limitación Fisica] +
			[% No Econ. Activa Pensionada] +
			[% No Econ. Activa No Especificada]
			
			```
		lineageTag: cceb1173-e3f9-4465-b96f-8d0c4ee5b93e

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure PorcentajeEconomicamenteActiva2020 =
			
			CALCULATE(
			    SUM(CensoHechos[Valor]),
			    FILTER(
			        CensoHechos,
			        CensoHechos[id_indicador] = 6207019030 && CensoHechos[Año] = 2020
			    )
			)
		lineageTag: 49ce1930-2dc3-4782-9477-4ff4302fb7c1

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure 'PorcentajeNoEconomicamenteActiva 2020' =
			
			CALCULATE(
			    SUM(CensoHechos[Valor]),
			    FILTER(
			        CensoHechos,
			        CensoHechos[id_indicador] = 6207019035 && CensoHechos[Año] = 2020
			    )
			)
		lineageTag: 2dca56ed-ea19-4eb1-b5a2-0ed4d656c9f0

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	partition 'Actividad Económica' = m
		mode: import
		source =
				let
				    Origen = Table.FromRows(Json.Document(Binary.Decompress(Binary.FromText("i44FAA==", BinaryEncoding.Base64), Compression.Deflate)), let _t = ((type nullable text) meta [Serialized.Text = true]) in type table [Columna1 = _t]),
				    #"Tipo cambiado" = Table.TransformColumnTypes(Origen,{{"Columna1", type text}}),
				    #"Columnas quitadas" = Table.RemoveColumns(#"Tipo cambiado",{"Columna1"})
				in
				    #"Columnas quitadas"

	annotation PBI_ResultType = Table

	annotation PBI_NavigationStepName = Navegación

