table 'Características de la Vivienda'
	lineageTag: 4001284e-150d-4896-a9e7-180f50d76b85

	measure 'Sanitario 2020' = ```
			
			CALCULATE(
			    SUM(CensoHechos[Valor]),
			    CensoHechos[id_indicador] = 1003000020
			)
			
			```
		lineageTag: 0cabb304-80f0-476a-a44e-b2f56231ed15

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure 'Lavadora 2020' = ```
			
			CALCULATE(
			    SUM(CensoHechos[Valor]),
			    CensoHechos[id_indicador] = 1003000023
			)
			
			```
		lineageTag: a6b76e98-92e7-4b10-8839-401af4d03e4b

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure 'Computadora 2020' = ```
			
			CALCULATE(
			    SUM(CensoHechos[Valor]),
			    CensoHechos[id_indicador] = 1003000024
			)
			
			```
		lineageTag: d36e0605-1b70-49bf-89e8-16b09364ab5b

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure '% Viviendas Con Internet' = ```
			
			CALCULATE(
			    SUM(CensoHechos[Valor]),
			    CensoHechos[id_indicador] = 6207019042
			)
			
			```
		lineageTag: 0a342b4e-1e72-4bd2-b50e-ecfd4359d99f

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure '% Viv. Con Computadora' = ```
			
			CALCULATE(
			    SUM(CensoHechos[Valor]),
			    CensoHechos[id_indicador] = 6207019046
			)
			
			```
		lineageTag: 93ba9121-f510-4b5f-9f0f-2403aee0c365

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure '% Viviendas Con Teléfono Fijo' = ```
			
			CALCULATE(
			    SUM(CensoHechos[Valor]),
			    CensoHechos[id_indicador] = 6207019050
			)
			
			```
		lineageTag: 7b118c6d-af75-4128-bab9-0eb94b6c58ec

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure '% Viviendas Con Celular' = ```
			
			CALCULATE(
			    SUM(CensoHechos[Valor]),
			    CensoHechos[id_indicador] = 6207019055
			)
			
			```
		lineageTag: 03f0034e-c3fe-4136-af6d-5ccdd1b7df42

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure '% Viviendas Con TV-Paga' = ```
			
			CALCULATE(
			    SUM(CensoHechos[Valor]),
			    CensoHechos[id_indicador] = 6207019057
			)
			
			```
		lineageTag: c116bb7e-b33a-4c57-9f77-6732ba9d184c

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure PorcentajeViviendasConTinaco = ```
			
			CALCULATE(
			    SUM(CensoHechos[Valor]),
			    CensoHechos[id_indicador] = 6207129631
			)
			
			```
		lineageTag: b7282c7a-dc9f-4e64-82de-a915b7a0153f

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure PorcentajeViviendasConCisterna = ```
			
			CALCULATE(
			    SUM(CensoHechos[Valor]),
			    CensoHechos[id_indicador] = 6207129632
			)
			
			```
		lineageTag: b885fc7f-4636-48d0-bdda-a2c3df27314e

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure '% Automóvil' = ```
			
			CALCULATE(
			    SUM(CensoHechos[Valor]),
			    CensoHechos[id_indicador] = 6207129635
			)
			
			```
		formatString: 0.0
		lineageTag: 4ee80926-e078-4a4d-85de-99555b2a9000

	measure '% Motocicleta' = ```
			
			CALCULATE(
			    SUM(CensoHechos[Valor]),
			    CensoHechos[id_indicador] = 6207129636
			)
			
			```
		formatString: 0.0
		lineageTag: 36b73aa0-6d33-4f6b-9de1-0b5154578c8c

	measure '% Bicicleta' = ```
			
			CALCULATE(
			    SUM(CensoHechos[Valor]),
			    CensoHechos[id_indicador] = 6207129637
			)
			
			```
		formatString: 0.0
		lineageTag: da035e5a-125e-4fc9-a8e1-caf48fe553bf

	measure PorcentajeViviendasConRefrigerador = ```
			
			CALCULATE(
			    SUM(CensoHechos[Valor]),
			    CensoHechos[id_indicador] = 6207129812
			)
			
			```
		lineageTag: f950986e-ff03-4df2-8220-4dc68d0676cc

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure PorcentajeViviendasConLavadora = ```
			
			CALCULATE(
			    SUM(CensoHechos[Valor]),
			    CensoHechos[id_indicador] = 6207129813
			)
			
			```
		lineageTag: a8ed5249-8de4-4b79-8c7d-af38d0dbcfcd

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure PorcentajeViviendasTinaco2020 = ```
			
			CALCULATE(
			    SUM(CensoHechos[Valor]),
			    CensoHechos[id_indicador] = 6207129631,
			    CensoHechos[Año] = 2020
			)
			
			```
		lineageTag: d5bb24ff-850f-4403-88f6-41504ad57716

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure PorcentajeViviendasCisterna2020 = ```
			
			CALCULATE(
			    SUM(CensoHechos[Valor]),
			    CensoHechos[id_indicador] = 6207129632,
			    CensoHechos[Año] = 2020
			)
			
			```
		lineageTag: 47844b9a-3f6a-4d80-9398-211e074f2df5

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	partition 'Características de la Vivienda' = m
		mode: import
		source =
				let
				    Origen = Table.FromRows(Json.Document(Binary.Decompress(Binary.FromText("i44FAA==", BinaryEncoding.Base64), Compression.Deflate)), let _t = ((type nullable text) meta [Serialized.Text = true]) in type table [Columna1 = _t]),
				    #"Tipo cambiado" = Table.TransformColumnTypes(Origen,{{"Columna1", type text}}),
				    #"Columnas quitadas" = Table.RemoveColumns(#"Tipo cambiado",{"Columna1"})
				in
				    #"Columnas quitadas"

	annotation PBI_ResultType = Table

